// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: tiny-auth-service/v1/admin-roles-service.proto

package tiny_auth_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminRolesService_Find_FullMethodName       = "/auth.service.AdminRolesService/Find"
	AdminRolesService_FindByName_FullMethodName = "/auth.service.AdminRolesService/FindByName"
	AdminRolesService_List_FullMethodName       = "/auth.service.AdminRolesService/List"
	AdminRolesService_Save_FullMethodName       = "/auth.service.AdminRolesService/Save"
	AdminRolesService_Delete_FullMethodName     = "/auth.service.AdminRolesService/Delete"
)

// AdminRolesServiceClient is the client API for AdminRolesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminRolesServiceClient interface {
	Find(ctx context.Context, in *AdminRolesFindRequest, opts ...grpc.CallOption) (*AdminRolesInstanceResponse, error)
	FindByName(ctx context.Context, in *AdminRolesFindByNameRequest, opts ...grpc.CallOption) (*AdminRolesInstanceResponse, error)
	List(ctx context.Context, in *AdminRolesListRequest, opts ...grpc.CallOption) (*AdminRolesInstancesResponse, error)
	Save(ctx context.Context, in *AdminRolesSaveRequest, opts ...grpc.CallOption) (*AdminRolesInstanceResponse, error)
	Delete(ctx context.Context, in *AdminRolesDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type adminRolesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminRolesServiceClient(cc grpc.ClientConnInterface) AdminRolesServiceClient {
	return &adminRolesServiceClient{cc}
}

func (c *adminRolesServiceClient) Find(ctx context.Context, in *AdminRolesFindRequest, opts ...grpc.CallOption) (*AdminRolesInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminRolesInstanceResponse)
	err := c.cc.Invoke(ctx, AdminRolesService_Find_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRolesServiceClient) FindByName(ctx context.Context, in *AdminRolesFindByNameRequest, opts ...grpc.CallOption) (*AdminRolesInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminRolesInstanceResponse)
	err := c.cc.Invoke(ctx, AdminRolesService_FindByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRolesServiceClient) List(ctx context.Context, in *AdminRolesListRequest, opts ...grpc.CallOption) (*AdminRolesInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminRolesInstancesResponse)
	err := c.cc.Invoke(ctx, AdminRolesService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRolesServiceClient) Save(ctx context.Context, in *AdminRolesSaveRequest, opts ...grpc.CallOption) (*AdminRolesInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminRolesInstanceResponse)
	err := c.cc.Invoke(ctx, AdminRolesService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRolesServiceClient) Delete(ctx context.Context, in *AdminRolesDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AdminRolesService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminRolesServiceServer is the server API for AdminRolesService service.
// All implementations must embed UnimplementedAdminRolesServiceServer
// for forward compatibility.
type AdminRolesServiceServer interface {
	Find(context.Context, *AdminRolesFindRequest) (*AdminRolesInstanceResponse, error)
	FindByName(context.Context, *AdminRolesFindByNameRequest) (*AdminRolesInstanceResponse, error)
	List(context.Context, *AdminRolesListRequest) (*AdminRolesInstancesResponse, error)
	Save(context.Context, *AdminRolesSaveRequest) (*AdminRolesInstanceResponse, error)
	Delete(context.Context, *AdminRolesDeleteRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAdminRolesServiceServer()
}

// UnimplementedAdminRolesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminRolesServiceServer struct{}

func (UnimplementedAdminRolesServiceServer) Find(context.Context, *AdminRolesFindRequest) (*AdminRolesInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedAdminRolesServiceServer) FindByName(context.Context, *AdminRolesFindByNameRequest) (*AdminRolesInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByName not implemented")
}
func (UnimplementedAdminRolesServiceServer) List(context.Context, *AdminRolesListRequest) (*AdminRolesInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAdminRolesServiceServer) Save(context.Context, *AdminRolesSaveRequest) (*AdminRolesInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedAdminRolesServiceServer) Delete(context.Context, *AdminRolesDeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAdminRolesServiceServer) mustEmbedUnimplementedAdminRolesServiceServer() {}
func (UnimplementedAdminRolesServiceServer) testEmbeddedByValue()                           {}

// UnsafeAdminRolesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminRolesServiceServer will
// result in compilation errors.
type UnsafeAdminRolesServiceServer interface {
	mustEmbedUnimplementedAdminRolesServiceServer()
}

func RegisterAdminRolesServiceServer(s grpc.ServiceRegistrar, srv AdminRolesServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminRolesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminRolesService_ServiceDesc, srv)
}

func _AdminRolesService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRolesFindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRolesServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRolesService_Find_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRolesServiceServer).Find(ctx, req.(*AdminRolesFindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRolesService_FindByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRolesFindByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRolesServiceServer).FindByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRolesService_FindByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRolesServiceServer).FindByName(ctx, req.(*AdminRolesFindByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRolesService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRolesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRolesServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRolesService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRolesServiceServer).List(ctx, req.(*AdminRolesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRolesService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRolesSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRolesServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRolesService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRolesServiceServer).Save(ctx, req.(*AdminRolesSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRolesService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRolesDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRolesServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRolesService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRolesServiceServer).Delete(ctx, req.(*AdminRolesDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminRolesService_ServiceDesc is the grpc.ServiceDesc for AdminRolesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminRolesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.service.AdminRolesService",
	HandlerType: (*AdminRolesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Find",
			Handler:    _AdminRolesService_Find_Handler,
		},
		{
			MethodName: "FindByName",
			Handler:    _AdminRolesService_FindByName_Handler,
		},
		{
			MethodName: "List",
			Handler:    _AdminRolesService_List_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _AdminRolesService_Save_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AdminRolesService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tiny-auth-service/v1/admin-roles-service.proto",
}
