// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: tiny-auth-service/v1/admin-users-service.proto

package tiny_auth_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminUsersFindRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminUsersFindRequest) Reset() {
	*x = AdminUsersFindRequest{}
	mi := &file_tiny_auth_service_v1_admin_users_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUsersFindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUsersFindRequest) ProtoMessage() {}

func (x *AdminUsersFindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_auth_service_v1_admin_users_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminUsersFindRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *AdminUsersFindRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *AdminUsersFindRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AdminUsersFindRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type AdminUsersFindRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 AdminUsersFindRequest_builder) Build() *AdminUsersFindRequest {
	m0 := &AdminUsersFindRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type AdminUsersFindByNameRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminUsersFindByNameRequest) Reset() {
	*x = AdminUsersFindByNameRequest{}
	mi := &file_tiny_auth_service_v1_admin_users_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUsersFindByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUsersFindByNameRequest) ProtoMessage() {}

func (x *AdminUsersFindByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_auth_service_v1_admin_users_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminUsersFindByNameRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *AdminUsersFindByNameRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *AdminUsersFindByNameRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AdminUsersFindByNameRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

type AdminUsersFindByNameRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
}

func (b0 AdminUsersFindByNameRequest_builder) Build() *AdminUsersFindByNameRequest {
	m0 := &AdminUsersFindByNameRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

type AdminUsersListRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Limit       uint32                 `protobuf:"varint,1,opt,name=limit"`
	xxx_hidden_Offset      uint32                 `protobuf:"varint,2,opt,name=offset"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminUsersListRequest) Reset() {
	*x = AdminUsersListRequest{}
	mi := &file_tiny_auth_service_v1_admin_users_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUsersListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUsersListRequest) ProtoMessage() {}

func (x *AdminUsersListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_auth_service_v1_admin_users_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminUsersListRequest) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *AdminUsersListRequest) GetOffset() uint32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *AdminUsersListRequest) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *AdminUsersListRequest) SetOffset(v uint32) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *AdminUsersListRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AdminUsersListRequest) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AdminUsersListRequest) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Limit = 0
}

func (x *AdminUsersListRequest) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Offset = 0
}

type AdminUsersListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Limit  *uint32
	Offset *uint32
}

func (b0 AdminUsersListRequest_builder) Build() *AdminUsersListRequest {
	m0 := &AdminUsersListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Limit = *b.Limit
	}
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Offset = *b.Offset
	}
	return m0
}

type AdminUsersSaveRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance *User                  `protobuf:"bytes,1,opt,name=instance"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AdminUsersSaveRequest) Reset() {
	*x = AdminUsersSaveRequest{}
	mi := &file_tiny_auth_service_v1_admin_users_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUsersSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUsersSaveRequest) ProtoMessage() {}

func (x *AdminUsersSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_auth_service_v1_admin_users_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminUsersSaveRequest) GetInstance() *User {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *AdminUsersSaveRequest) SetInstance(v *User) {
	x.xxx_hidden_Instance = v
}

func (x *AdminUsersSaveRequest) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *AdminUsersSaveRequest) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

type AdminUsersSaveRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Instance *User
}

func (b0 AdminUsersSaveRequest_builder) Build() *AdminUsersSaveRequest {
	m0 := &AdminUsersSaveRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	return m0
}

type AdminUsersDeleteRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminUsersDeleteRequest) Reset() {
	*x = AdminUsersDeleteRequest{}
	mi := &file_tiny_auth_service_v1_admin_users_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUsersDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUsersDeleteRequest) ProtoMessage() {}

func (x *AdminUsersDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_auth_service_v1_admin_users_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminUsersDeleteRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *AdminUsersDeleteRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *AdminUsersDeleteRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AdminUsersDeleteRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type AdminUsersDeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 AdminUsersDeleteRequest_builder) Build() *AdminUsersDeleteRequest {
	m0 := &AdminUsersDeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type AdminUsersInstanceResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance *User                  `protobuf:"bytes,1,opt,name=instance"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AdminUsersInstanceResponse) Reset() {
	*x = AdminUsersInstanceResponse{}
	mi := &file_tiny_auth_service_v1_admin_users_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUsersInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUsersInstanceResponse) ProtoMessage() {}

func (x *AdminUsersInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_auth_service_v1_admin_users_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminUsersInstanceResponse) GetInstance() *User {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *AdminUsersInstanceResponse) SetInstance(v *User) {
	x.xxx_hidden_Instance = v
}

func (x *AdminUsersInstanceResponse) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *AdminUsersInstanceResponse) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

type AdminUsersInstanceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Instance *User
}

func (b0 AdminUsersInstanceResponse_builder) Build() *AdminUsersInstanceResponse {
	m0 := &AdminUsersInstanceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	return m0
}

type AdminUsersInstancesResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Offset      uint32                 `protobuf:"varint,1,opt,name=offset"`
	xxx_hidden_Limit       uint32                 `protobuf:"varint,2,opt,name=limit"`
	xxx_hidden_Instances   *[]*User               `protobuf:"bytes,3,rep,name=instances"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminUsersInstancesResponse) Reset() {
	*x = AdminUsersInstancesResponse{}
	mi := &file_tiny_auth_service_v1_admin_users_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUsersInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUsersInstancesResponse) ProtoMessage() {}

func (x *AdminUsersInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_auth_service_v1_admin_users_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminUsersInstancesResponse) GetOffset() uint32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *AdminUsersInstancesResponse) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *AdminUsersInstancesResponse) GetInstances() []*User {
	if x != nil {
		if x.xxx_hidden_Instances != nil {
			return *x.xxx_hidden_Instances
		}
	}
	return nil
}

func (x *AdminUsersInstancesResponse) SetOffset(v uint32) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *AdminUsersInstancesResponse) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *AdminUsersInstancesResponse) SetInstances(v []*User) {
	x.xxx_hidden_Instances = &v
}

func (x *AdminUsersInstancesResponse) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AdminUsersInstancesResponse) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AdminUsersInstancesResponse) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Offset = 0
}

func (x *AdminUsersInstancesResponse) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Limit = 0
}

type AdminUsersInstancesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Offset    *uint32
	Limit     *uint32
	Instances []*User
}

func (b0 AdminUsersInstancesResponse_builder) Build() *AdminUsersInstancesResponse {
	m0 := &AdminUsersInstancesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Offset = *b.Offset
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Limit = *b.Limit
	}
	x.xxx_hidden_Instances = &b.Instances
	return m0
}

var File_tiny_auth_service_v1_admin_users_service_proto protoreflect.FileDescriptor

const file_tiny_auth_service_v1_admin_users_service_proto_rawDesc = "" +
	"\n" +
	".tiny-auth-service/v1/admin-users-service.proto\x12\fauth.service\x1a\x1bgoogle/protobuf/empty.proto\x1a#tiny-auth-service/v1/messages.proto\"'\n" +
	"\x15AdminUsersFindRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x1bAdminUsersFindByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"E\n" +
	"\x15AdminUsersListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\"G\n" +
	"\x15AdminUsersSaveRequest\x12.\n" +
	"\binstance\x18\x01 \x01(\v2\x12.auth.service.UserR\binstance\")\n" +
	"\x17AdminUsersDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x1aAdminUsersInstanceResponse\x12.\n" +
	"\binstance\x18\x01 \x01(\v2\x12.auth.service.UserR\binstance\"}\n" +
	"\x1bAdminUsersInstancesResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x120\n" +
	"\tinstances\x18\x03 \x03(\v2\x12.auth.service.UserR\tinstances2\xc5\x03\n" +
	"\x11AdminUsersService\x12U\n" +
	"\x04Find\x12#.auth.service.AdminUsersFindRequest\x1a(.auth.service.AdminUsersInstanceResponse\x12a\n" +
	"\n" +
	"FindByName\x12).auth.service.AdminUsersFindByNameRequest\x1a(.auth.service.AdminUsersInstanceResponse\x12V\n" +
	"\x04List\x12#.auth.service.AdminUsersListRequest\x1a).auth.service.AdminUsersInstancesResponse\x12U\n" +
	"\x04Save\x12#.auth.service.AdminUsersSaveRequest\x1a(.auth.service.AdminUsersInstanceResponse\x12G\n" +
	"\x06Delete\x12%.auth.service.AdminUsersDeleteRequest\x1a\x16.google.protobuf.EmptyB*Z(tiny-auth-service/grpc/tiny-auth-serviceb\beditionsp\xe8\a"

var file_tiny_auth_service_v1_admin_users_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tiny_auth_service_v1_admin_users_service_proto_goTypes = []any{
	(*AdminUsersFindRequest)(nil),       // 0: auth.service.AdminUsersFindRequest
	(*AdminUsersFindByNameRequest)(nil), // 1: auth.service.AdminUsersFindByNameRequest
	(*AdminUsersListRequest)(nil),       // 2: auth.service.AdminUsersListRequest
	(*AdminUsersSaveRequest)(nil),       // 3: auth.service.AdminUsersSaveRequest
	(*AdminUsersDeleteRequest)(nil),     // 4: auth.service.AdminUsersDeleteRequest
	(*AdminUsersInstanceResponse)(nil),  // 5: auth.service.AdminUsersInstanceResponse
	(*AdminUsersInstancesResponse)(nil), // 6: auth.service.AdminUsersInstancesResponse
	(*User)(nil),                        // 7: auth.service.User
	(*emptypb.Empty)(nil),               // 8: google.protobuf.Empty
}
var file_tiny_auth_service_v1_admin_users_service_proto_depIdxs = []int32{
	7, // 0: auth.service.AdminUsersSaveRequest.instance:type_name -> auth.service.User
	7, // 1: auth.service.AdminUsersInstanceResponse.instance:type_name -> auth.service.User
	7, // 2: auth.service.AdminUsersInstancesResponse.instances:type_name -> auth.service.User
	0, // 3: auth.service.AdminUsersService.Find:input_type -> auth.service.AdminUsersFindRequest
	1, // 4: auth.service.AdminUsersService.FindByName:input_type -> auth.service.AdminUsersFindByNameRequest
	2, // 5: auth.service.AdminUsersService.List:input_type -> auth.service.AdminUsersListRequest
	3, // 6: auth.service.AdminUsersService.Save:input_type -> auth.service.AdminUsersSaveRequest
	4, // 7: auth.service.AdminUsersService.Delete:input_type -> auth.service.AdminUsersDeleteRequest
	5, // 8: auth.service.AdminUsersService.Find:output_type -> auth.service.AdminUsersInstanceResponse
	5, // 9: auth.service.AdminUsersService.FindByName:output_type -> auth.service.AdminUsersInstanceResponse
	6, // 10: auth.service.AdminUsersService.List:output_type -> auth.service.AdminUsersInstancesResponse
	5, // 11: auth.service.AdminUsersService.Save:output_type -> auth.service.AdminUsersInstanceResponse
	8, // 12: auth.service.AdminUsersService.Delete:output_type -> google.protobuf.Empty
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tiny_auth_service_v1_admin_users_service_proto_init() }
func file_tiny_auth_service_v1_admin_users_service_proto_init() {
	if File_tiny_auth_service_v1_admin_users_service_proto != nil {
		return
	}
	file_tiny_auth_service_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tiny_auth_service_v1_admin_users_service_proto_rawDesc), len(file_tiny_auth_service_v1_admin_users_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tiny_auth_service_v1_admin_users_service_proto_goTypes,
		DependencyIndexes: file_tiny_auth_service_v1_admin_users_service_proto_depIdxs,
		MessageInfos:      file_tiny_auth_service_v1_admin_users_service_proto_msgTypes,
	}.Build()
	File_tiny_auth_service_v1_admin_users_service_proto = out.File
	file_tiny_auth_service_v1_admin_users_service_proto_goTypes = nil
	file_tiny_auth_service_v1_admin_users_service_proto_depIdxs = nil
}
