// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: tiny-auth-service/v1/auth-service.proto

package tiny_auth_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthLoginRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Username    *string                `protobuf:"bytes,1,opt,name=username"`
	xxx_hidden_Password    *string                `protobuf:"bytes,2,opt,name=password"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuthLoginRequest) Reset() {
	*x = AuthLoginRequest{}
	mi := &file_tiny_auth_service_v1_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLoginRequest) ProtoMessage() {}

func (x *AuthLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_auth_service_v1_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthLoginRequest) GetUsername() string {
	if x != nil {
		if x.xxx_hidden_Username != nil {
			return *x.xxx_hidden_Username
		}
		return ""
	}
	return ""
}

func (x *AuthLoginRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *AuthLoginRequest) SetUsername(v string) {
	x.xxx_hidden_Username = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *AuthLoginRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *AuthLoginRequest) HasUsername() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuthLoginRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AuthLoginRequest) ClearUsername() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Username = nil
}

func (x *AuthLoginRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

type AuthLoginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Username *string
	Password *string
}

func (b0 AuthLoginRequest_builder) Build() *AuthLoginRequest {
	m0 := &AuthLoginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Username != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Username = b.Username
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Password = b.Password
	}
	return m0
}

type AuthLoginResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token        *string                `protobuf:"bytes,1,opt,name=token"`
	xxx_hidden_RefreshToken *string                `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AuthLoginResponse) Reset() {
	*x = AuthLoginResponse{}
	mi := &file_tiny_auth_service_v1_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLoginResponse) ProtoMessage() {}

func (x *AuthLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_auth_service_v1_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthLoginResponse) GetToken() string {
	if x != nil {
		if x.xxx_hidden_Token != nil {
			return *x.xxx_hidden_Token
		}
		return ""
	}
	return ""
}

func (x *AuthLoginResponse) GetRefreshToken() string {
	if x != nil {
		if x.xxx_hidden_RefreshToken != nil {
			return *x.xxx_hidden_RefreshToken
		}
		return ""
	}
	return ""
}

func (x *AuthLoginResponse) SetToken(v string) {
	x.xxx_hidden_Token = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *AuthLoginResponse) SetRefreshToken(v string) {
	x.xxx_hidden_RefreshToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *AuthLoginResponse) HasToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuthLoginResponse) HasRefreshToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AuthLoginResponse) ClearToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Token = nil
}

func (x *AuthLoginResponse) ClearRefreshToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_RefreshToken = nil
}

type AuthLoginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token        *string
	RefreshToken *string
}

func (b0 AuthLoginResponse_builder) Build() *AuthLoginResponse {
	m0 := &AuthLoginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Token != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Token = b.Token
	}
	if b.RefreshToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_RefreshToken = b.RefreshToken
	}
	return m0
}

type AuthChangePasswordRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OldPassword *string                `protobuf:"bytes,1,opt,name=old_password,json=oldPassword"`
	xxx_hidden_NewPassword *string                `protobuf:"bytes,2,opt,name=new_password,json=newPassword"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuthChangePasswordRequest) Reset() {
	*x = AuthChangePasswordRequest{}
	mi := &file_tiny_auth_service_v1_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthChangePasswordRequest) ProtoMessage() {}

func (x *AuthChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_auth_service_v1_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		if x.xxx_hidden_OldPassword != nil {
			return *x.xxx_hidden_OldPassword
		}
		return ""
	}
	return ""
}

func (x *AuthChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		if x.xxx_hidden_NewPassword != nil {
			return *x.xxx_hidden_NewPassword
		}
		return ""
	}
	return ""
}

func (x *AuthChangePasswordRequest) SetOldPassword(v string) {
	x.xxx_hidden_OldPassword = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *AuthChangePasswordRequest) SetNewPassword(v string) {
	x.xxx_hidden_NewPassword = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *AuthChangePasswordRequest) HasOldPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuthChangePasswordRequest) HasNewPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AuthChangePasswordRequest) ClearOldPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_OldPassword = nil
}

func (x *AuthChangePasswordRequest) ClearNewPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NewPassword = nil
}

type AuthChangePasswordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OldPassword *string
	NewPassword *string
}

func (b0 AuthChangePasswordRequest_builder) Build() *AuthChangePasswordRequest {
	m0 := &AuthChangePasswordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.OldPassword != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_OldPassword = b.OldPassword
	}
	if b.NewPassword != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_NewPassword = b.NewPassword
	}
	return m0
}

type AuthGetInfoResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Info *User                  `protobuf:"bytes,1,opt,name=info"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthGetInfoResponse) Reset() {
	*x = AuthGetInfoResponse{}
	mi := &file_tiny_auth_service_v1_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthGetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthGetInfoResponse) ProtoMessage() {}

func (x *AuthGetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_auth_service_v1_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthGetInfoResponse) GetInfo() *User {
	if x != nil {
		return x.xxx_hidden_Info
	}
	return nil
}

func (x *AuthGetInfoResponse) SetInfo(v *User) {
	x.xxx_hidden_Info = v
}

func (x *AuthGetInfoResponse) HasInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Info != nil
}

func (x *AuthGetInfoResponse) ClearInfo() {
	x.xxx_hidden_Info = nil
}

type AuthGetInfoResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Info *User
}

func (b0 AuthGetInfoResponse_builder) Build() *AuthGetInfoResponse {
	m0 := &AuthGetInfoResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Info = b.Info
	return m0
}

type AuthChangeKeysResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PublicKey   *string                `protobuf:"bytes,1,opt,name=public_key,json=publicKey"`
	xxx_hidden_PrivateKey  *string                `protobuf:"bytes,2,opt,name=private_key,json=privateKey"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuthChangeKeysResponse) Reset() {
	*x = AuthChangeKeysResponse{}
	mi := &file_tiny_auth_service_v1_auth_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthChangeKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthChangeKeysResponse) ProtoMessage() {}

func (x *AuthChangeKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_auth_service_v1_auth_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthChangeKeysResponse) GetPublicKey() string {
	if x != nil {
		if x.xxx_hidden_PublicKey != nil {
			return *x.xxx_hidden_PublicKey
		}
		return ""
	}
	return ""
}

func (x *AuthChangeKeysResponse) GetPrivateKey() string {
	if x != nil {
		if x.xxx_hidden_PrivateKey != nil {
			return *x.xxx_hidden_PrivateKey
		}
		return ""
	}
	return ""
}

func (x *AuthChangeKeysResponse) SetPublicKey(v string) {
	x.xxx_hidden_PublicKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *AuthChangeKeysResponse) SetPrivateKey(v string) {
	x.xxx_hidden_PrivateKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *AuthChangeKeysResponse) HasPublicKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuthChangeKeysResponse) HasPrivateKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AuthChangeKeysResponse) ClearPublicKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PublicKey = nil
}

func (x *AuthChangeKeysResponse) ClearPrivateKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PrivateKey = nil
}

type AuthChangeKeysResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PublicKey  *string
	PrivateKey *string
}

func (b0 AuthChangeKeysResponse_builder) Build() *AuthChangeKeysResponse {
	m0 := &AuthChangeKeysResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PublicKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_PublicKey = b.PublicKey
	}
	if b.PrivateKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_PrivateKey = b.PrivateKey
	}
	return m0
}

var File_tiny_auth_service_v1_auth_service_proto protoreflect.FileDescriptor

const file_tiny_auth_service_v1_auth_service_proto_rawDesc = "" +
	"\n" +
	"'tiny-auth-service/v1/auth-service.proto\x12\fauth.service\x1a\x1bgoogle/protobuf/empty.proto\x1a#tiny-auth-service/v1/messages.proto\"J\n" +
	"\x10AuthLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"N\n" +
	"\x11AuthLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"a\n" +
	"\x19AuthChangePasswordRequest\x12!\n" +
	"\fold_password\x18\x01 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"=\n" +
	"\x13AuthGetInfoResponse\x12&\n" +
	"\x04info\x18\x01 \x01(\v2\x12.auth.service.UserR\x04info\"X\n" +
	"\x16AuthChangeKeysResponse\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vprivate_key\x18\x02 \x01(\tR\n" +
	"privateKey2\xbc\x02\n" +
	"\vAuthService\x12H\n" +
	"\x05Login\x12\x1e.auth.service.AuthLoginRequest\x1a\x1f.auth.service.AuthLoginResponse\x12D\n" +
	"\aGetInfo\x12\x16.google.protobuf.Empty\x1a!.auth.service.AuthGetInfoResponse\x12Q\n" +
	"\x0eChangePassword\x12'.auth.service.AuthChangePasswordRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\n" +
	"ChangeKeys\x12\x16.google.protobuf.Empty\x1a$.auth.service.AuthChangeKeysResponseB*Z(tiny-auth-service/grpc/tiny-auth-serviceb\beditionsp\xe8\a"

var file_tiny_auth_service_v1_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_tiny_auth_service_v1_auth_service_proto_goTypes = []any{
	(*AuthLoginRequest)(nil),          // 0: auth.service.AuthLoginRequest
	(*AuthLoginResponse)(nil),         // 1: auth.service.AuthLoginResponse
	(*AuthChangePasswordRequest)(nil), // 2: auth.service.AuthChangePasswordRequest
	(*AuthGetInfoResponse)(nil),       // 3: auth.service.AuthGetInfoResponse
	(*AuthChangeKeysResponse)(nil),    // 4: auth.service.AuthChangeKeysResponse
	(*User)(nil),                      // 5: auth.service.User
	(*emptypb.Empty)(nil),             // 6: google.protobuf.Empty
}
var file_tiny_auth_service_v1_auth_service_proto_depIdxs = []int32{
	5, // 0: auth.service.AuthGetInfoResponse.info:type_name -> auth.service.User
	0, // 1: auth.service.AuthService.Login:input_type -> auth.service.AuthLoginRequest
	6, // 2: auth.service.AuthService.GetInfo:input_type -> google.protobuf.Empty
	2, // 3: auth.service.AuthService.ChangePassword:input_type -> auth.service.AuthChangePasswordRequest
	6, // 4: auth.service.AuthService.ChangeKeys:input_type -> google.protobuf.Empty
	1, // 5: auth.service.AuthService.Login:output_type -> auth.service.AuthLoginResponse
	3, // 6: auth.service.AuthService.GetInfo:output_type -> auth.service.AuthGetInfoResponse
	6, // 7: auth.service.AuthService.ChangePassword:output_type -> google.protobuf.Empty
	4, // 8: auth.service.AuthService.ChangeKeys:output_type -> auth.service.AuthChangeKeysResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tiny_auth_service_v1_auth_service_proto_init() }
func file_tiny_auth_service_v1_auth_service_proto_init() {
	if File_tiny_auth_service_v1_auth_service_proto != nil {
		return
	}
	file_tiny_auth_service_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tiny_auth_service_v1_auth_service_proto_rawDesc), len(file_tiny_auth_service_v1_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tiny_auth_service_v1_auth_service_proto_goTypes,
		DependencyIndexes: file_tiny_auth_service_v1_auth_service_proto_depIdxs,
		MessageInfos:      file_tiny_auth_service_v1_auth_service_proto_msgTypes,
	}.Build()
	File_tiny_auth_service_v1_auth_service_proto = out.File
	file_tiny_auth_service_v1_auth_service_proto_goTypes = nil
	file_tiny_auth_service_v1_auth_service_proto_depIdxs = nil
}
