// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: tiny-auth-service/v1/user-service.proto

package tiny_auth_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangePasswordRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OldPassword *string                `protobuf:"bytes,1,opt,name=old_password,json=oldPassword"`
	xxx_hidden_NewPassword *string                `protobuf:"bytes,2,opt,name=new_password,json=newPassword"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_tiny_auth_service_v1_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_auth_service_v1_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		if x.xxx_hidden_OldPassword != nil {
			return *x.xxx_hidden_OldPassword
		}
		return ""
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		if x.xxx_hidden_NewPassword != nil {
			return *x.xxx_hidden_NewPassword
		}
		return ""
	}
	return ""
}

func (x *ChangePasswordRequest) SetOldPassword(v string) {
	x.xxx_hidden_OldPassword = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ChangePasswordRequest) SetNewPassword(v string) {
	x.xxx_hidden_NewPassword = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ChangePasswordRequest) HasOldPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ChangePasswordRequest) HasNewPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ChangePasswordRequest) ClearOldPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_OldPassword = nil
}

func (x *ChangePasswordRequest) ClearNewPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NewPassword = nil
}

type ChangePasswordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OldPassword *string
	NewPassword *string
}

func (b0 ChangePasswordRequest_builder) Build() *ChangePasswordRequest {
	m0 := &ChangePasswordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.OldPassword != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_OldPassword = b.OldPassword
	}
	if b.NewPassword != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_NewPassword = b.NewPassword
	}
	return m0
}

type ProfileResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Info *User                  `protobuf:"bytes,1,opt,name=info"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_tiny_auth_service_v1_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_auth_service_v1_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfileResponse) GetInfo() *User {
	if x != nil {
		return x.xxx_hidden_Info
	}
	return nil
}

func (x *ProfileResponse) SetInfo(v *User) {
	x.xxx_hidden_Info = v
}

func (x *ProfileResponse) HasInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Info != nil
}

func (x *ProfileResponse) ClearInfo() {
	x.xxx_hidden_Info = nil
}

type ProfileResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Info *User
}

func (b0 ProfileResponse_builder) Build() *ProfileResponse {
	m0 := &ProfileResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Info = b.Info
	return m0
}

type ChangeKeysResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PublicKey   *string                `protobuf:"bytes,1,opt,name=public_key,json=publicKey"`
	xxx_hidden_PrivateKey  *string                `protobuf:"bytes,2,opt,name=private_key,json=privateKey"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ChangeKeysResponse) Reset() {
	*x = ChangeKeysResponse{}
	mi := &file_tiny_auth_service_v1_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeKeysResponse) ProtoMessage() {}

func (x *ChangeKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_auth_service_v1_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChangeKeysResponse) GetPublicKey() string {
	if x != nil {
		if x.xxx_hidden_PublicKey != nil {
			return *x.xxx_hidden_PublicKey
		}
		return ""
	}
	return ""
}

func (x *ChangeKeysResponse) GetPrivateKey() string {
	if x != nil {
		if x.xxx_hidden_PrivateKey != nil {
			return *x.xxx_hidden_PrivateKey
		}
		return ""
	}
	return ""
}

func (x *ChangeKeysResponse) SetPublicKey(v string) {
	x.xxx_hidden_PublicKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ChangeKeysResponse) SetPrivateKey(v string) {
	x.xxx_hidden_PrivateKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ChangeKeysResponse) HasPublicKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ChangeKeysResponse) HasPrivateKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ChangeKeysResponse) ClearPublicKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PublicKey = nil
}

func (x *ChangeKeysResponse) ClearPrivateKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PrivateKey = nil
}

type ChangeKeysResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PublicKey  *string
	PrivateKey *string
}

func (b0 ChangeKeysResponse_builder) Build() *ChangeKeysResponse {
	m0 := &ChangeKeysResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PublicKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_PublicKey = b.PublicKey
	}
	if b.PrivateKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_PrivateKey = b.PrivateKey
	}
	return m0
}

var File_tiny_auth_service_v1_user_service_proto protoreflect.FileDescriptor

const file_tiny_auth_service_v1_user_service_proto_rawDesc = "" +
	"\n" +
	"'tiny-auth-service/v1/user-service.proto\x12\fauth.service\x1a\x1bgoogle/protobuf/empty.proto\x1a#tiny-auth-service/v1/messages.proto\"]\n" +
	"\x15ChangePasswordRequest\x12!\n" +
	"\fold_password\x18\x01 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"9\n" +
	"\x0fProfileResponse\x12&\n" +
	"\x04info\x18\x01 \x01(\v2\x12.auth.service.UserR\x04info\"T\n" +
	"\x12ChangeKeysResponse\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vprivate_key\x18\x02 \x01(\tR\n" +
	"privateKey2\xe6\x01\n" +
	"\vUserService\x12@\n" +
	"\aProfile\x12\x16.google.protobuf.Empty\x1a\x1d.auth.service.ProfileResponse\x12M\n" +
	"\x0eChangePassword\x12#.auth.service.ChangePasswordRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\n" +
	"ChangeKeys\x12\x16.google.protobuf.Empty\x1a .auth.service.ChangeKeysResponseB*Z(tiny-auth-service/grpc/tiny-auth-serviceb\beditionsp\xe8\a"

var file_tiny_auth_service_v1_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tiny_auth_service_v1_user_service_proto_goTypes = []any{
	(*ChangePasswordRequest)(nil), // 0: auth.service.ChangePasswordRequest
	(*ProfileResponse)(nil),       // 1: auth.service.ProfileResponse
	(*ChangeKeysResponse)(nil),    // 2: auth.service.ChangeKeysResponse
	(*User)(nil),                  // 3: auth.service.User
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_tiny_auth_service_v1_user_service_proto_depIdxs = []int32{
	3, // 0: auth.service.ProfileResponse.info:type_name -> auth.service.User
	4, // 1: auth.service.UserService.Profile:input_type -> google.protobuf.Empty
	0, // 2: auth.service.UserService.ChangePassword:input_type -> auth.service.ChangePasswordRequest
	4, // 3: auth.service.UserService.ChangeKeys:input_type -> google.protobuf.Empty
	1, // 4: auth.service.UserService.Profile:output_type -> auth.service.ProfileResponse
	4, // 5: auth.service.UserService.ChangePassword:output_type -> google.protobuf.Empty
	2, // 6: auth.service.UserService.ChangeKeys:output_type -> auth.service.ChangeKeysResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tiny_auth_service_v1_user_service_proto_init() }
func file_tiny_auth_service_v1_user_service_proto_init() {
	if File_tiny_auth_service_v1_user_service_proto != nil {
		return
	}
	file_tiny_auth_service_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tiny_auth_service_v1_user_service_proto_rawDesc), len(file_tiny_auth_service_v1_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tiny_auth_service_v1_user_service_proto_goTypes,
		DependencyIndexes: file_tiny_auth_service_v1_user_service_proto_depIdxs,
		MessageInfos:      file_tiny_auth_service_v1_user_service_proto_msgTypes,
	}.Build()
	File_tiny_auth_service_v1_user_service_proto = out.File
	file_tiny_auth_service_v1_user_service_proto_goTypes = nil
	file_tiny_auth_service_v1_user_service_proto_depIdxs = nil
}
