// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/tiny-auth-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRoleAdminRepository creates a new instance of MockRoleAdminRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleAdminRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleAdminRepository {
	mock := &MockRoleAdminRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoleAdminRepository is an autogenerated mock type for the RoleAdminRepository type
type MockRoleAdminRepository struct {
	mock.Mock
}

type MockRoleAdminRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleAdminRepository) EXPECT() *MockRoleAdminRepository_Expecter {
	return &MockRoleAdminRepository_Expecter{mock: &_m.Mock}
}

// Change provides a mock function for the type MockRoleAdminRepository
func (_mock *MockRoleAdminRepository) Change(ctx context.Context, entity *domain.Role) (*domain.Role, error) {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Change")
	}

	var r0 *domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Role) (*domain.Role, error)); ok {
		return returnFunc(ctx, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Role) *domain.Role); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Role) error); ok {
		r1 = returnFunc(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleAdminRepository_Change_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Change'
type MockRoleAdminRepository_Change_Call struct {
	*mock.Call
}

// Change is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *domain.Role
func (_e *MockRoleAdminRepository_Expecter) Change(ctx interface{}, entity interface{}) *MockRoleAdminRepository_Change_Call {
	return &MockRoleAdminRepository_Change_Call{Call: _e.mock.On("Change", ctx, entity)}
}

func (_c *MockRoleAdminRepository_Change_Call) Run(run func(ctx context.Context, entity *domain.Role)) *MockRoleAdminRepository_Change_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Role
		if args[1] != nil {
			arg1 = args[1].(*domain.Role)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleAdminRepository_Change_Call) Return(role *domain.Role, err error) *MockRoleAdminRepository_Change_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockRoleAdminRepository_Change_Call) RunAndReturn(run func(ctx context.Context, entity *domain.Role) (*domain.Role, error)) *MockRoleAdminRepository_Change_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRoleAdminRepository
func (_mock *MockRoleAdminRepository) Create(ctx context.Context, entity *domain.Role) (*domain.Role, error) {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Role) (*domain.Role, error)); ok {
		return returnFunc(ctx, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Role) *domain.Role); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Role) error); ok {
		r1 = returnFunc(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleAdminRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoleAdminRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *domain.Role
func (_e *MockRoleAdminRepository_Expecter) Create(ctx interface{}, entity interface{}) *MockRoleAdminRepository_Create_Call {
	return &MockRoleAdminRepository_Create_Call{Call: _e.mock.On("Create", ctx, entity)}
}

func (_c *MockRoleAdminRepository_Create_Call) Run(run func(ctx context.Context, entity *domain.Role)) *MockRoleAdminRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Role
		if args[1] != nil {
			arg1 = args[1].(*domain.Role)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleAdminRepository_Create_Call) Return(role *domain.Role, err error) *MockRoleAdminRepository_Create_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockRoleAdminRepository_Create_Call) RunAndReturn(run func(ctx context.Context, entity *domain.Role) (*domain.Role, error)) *MockRoleAdminRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRoleAdminRepository
func (_mock *MockRoleAdminRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoleAdminRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRoleAdminRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRoleAdminRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRoleAdminRepository_Delete_Call {
	return &MockRoleAdminRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRoleAdminRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockRoleAdminRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleAdminRepository_Delete_Call) Return(err error) *MockRoleAdminRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoleAdminRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockRoleAdminRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockRoleAdminRepository
func (_mock *MockRoleAdminRepository) Find(ctx context.Context, id string) (*domain.Role, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Role, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Role); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleAdminRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockRoleAdminRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRoleAdminRepository_Expecter) Find(ctx interface{}, id interface{}) *MockRoleAdminRepository_Find_Call {
	return &MockRoleAdminRepository_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockRoleAdminRepository_Find_Call) Run(run func(ctx context.Context, id string)) *MockRoleAdminRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleAdminRepository_Find_Call) Return(role *domain.Role, err error) *MockRoleAdminRepository_Find_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockRoleAdminRepository_Find_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Role, error)) *MockRoleAdminRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function for the type MockRoleAdminRepository
func (_mock *MockRoleAdminRepository) FindByName(ctx context.Context, login string) (*domain.Role, error) {
	ret := _mock.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Role, error)); ok {
		return returnFunc(ctx, login)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Role); ok {
		r0 = returnFunc(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleAdminRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockRoleAdminRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *MockRoleAdminRepository_Expecter) FindByName(ctx interface{}, login interface{}) *MockRoleAdminRepository_FindByName_Call {
	return &MockRoleAdminRepository_FindByName_Call{Call: _e.mock.On("FindByName", ctx, login)}
}

func (_c *MockRoleAdminRepository_FindByName_Call) Run(run func(ctx context.Context, login string)) *MockRoleAdminRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleAdminRepository_FindByName_Call) Return(role *domain.Role, err error) *MockRoleAdminRepository_FindByName_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockRoleAdminRepository_FindByName_Call) RunAndReturn(run func(ctx context.Context, login string) (*domain.Role, error)) *MockRoleAdminRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRoleAdminRepository
func (_mock *MockRoleAdminRepository) List(ctx context.Context, limit int, offset int) ([]*domain.Role, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain.Role, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*domain.Role); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleAdminRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRoleAdminRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockRoleAdminRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *MockRoleAdminRepository_List_Call {
	return &MockRoleAdminRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockRoleAdminRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockRoleAdminRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRoleAdminRepository_List_Call) Return(roles []*domain.Role, err error) *MockRoleAdminRepository_List_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *MockRoleAdminRepository_List_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*domain.Role, error)) *MockRoleAdminRepository_List_Call {
	_c.Call.Return(run)
	return _c
}
