// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/tiny-auth-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserAdminRepository creates a new instance of MockUserAdminRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserAdminRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserAdminRepository {
	mock := &MockUserAdminRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserAdminRepository is an autogenerated mock type for the UserAdminRepository type
type MockUserAdminRepository struct {
	mock.Mock
}

type MockUserAdminRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserAdminRepository) EXPECT() *MockUserAdminRepository_Expecter {
	return &MockUserAdminRepository_Expecter{mock: &_m.Mock}
}

// Change provides a mock function for the type MockUserAdminRepository
func (_mock *MockUserAdminRepository) Change(ctx context.Context, entity *domain.User) (*domain.User, error) {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Change")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) (*domain.User, error)); ok {
		return returnFunc(ctx, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) *domain.User); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.User) error); ok {
		r1 = returnFunc(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAdminRepository_Change_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Change'
type MockUserAdminRepository_Change_Call struct {
	*mock.Call
}

// Change is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *domain.User
func (_e *MockUserAdminRepository_Expecter) Change(ctx interface{}, entity interface{}) *MockUserAdminRepository_Change_Call {
	return &MockUserAdminRepository_Change_Call{Call: _e.mock.On("Change", ctx, entity)}
}

func (_c *MockUserAdminRepository_Change_Call) Run(run func(ctx context.Context, entity *domain.User)) *MockUserAdminRepository_Change_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserAdminRepository_Change_Call) Return(user *domain.User, err error) *MockUserAdminRepository_Change_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserAdminRepository_Change_Call) RunAndReturn(run func(ctx context.Context, entity *domain.User) (*domain.User, error)) *MockUserAdminRepository_Change_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockUserAdminRepository
func (_mock *MockUserAdminRepository) Create(ctx context.Context, entity *domain.User) (*domain.User, error) {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) (*domain.User, error)); ok {
		return returnFunc(ctx, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) *domain.User); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.User) error); ok {
		r1 = returnFunc(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAdminRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserAdminRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *domain.User
func (_e *MockUserAdminRepository_Expecter) Create(ctx interface{}, entity interface{}) *MockUserAdminRepository_Create_Call {
	return &MockUserAdminRepository_Create_Call{Call: _e.mock.On("Create", ctx, entity)}
}

func (_c *MockUserAdminRepository_Create_Call) Run(run func(ctx context.Context, entity *domain.User)) *MockUserAdminRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserAdminRepository_Create_Call) Return(user *domain.User, err error) *MockUserAdminRepository_Create_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserAdminRepository_Create_Call) RunAndReturn(run func(ctx context.Context, entity *domain.User) (*domain.User, error)) *MockUserAdminRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserAdminRepository
func (_mock *MockUserAdminRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserAdminRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserAdminRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserAdminRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockUserAdminRepository_Delete_Call {
	return &MockUserAdminRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUserAdminRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockUserAdminRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserAdminRepository_Delete_Call) Return(err error) *MockUserAdminRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserAdminRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockUserAdminRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockUserAdminRepository
func (_mock *MockUserAdminRepository) Find(ctx context.Context, id string) (*domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAdminRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockUserAdminRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserAdminRepository_Expecter) Find(ctx interface{}, id interface{}) *MockUserAdminRepository_Find_Call {
	return &MockUserAdminRepository_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockUserAdminRepository_Find_Call) Run(run func(ctx context.Context, id string)) *MockUserAdminRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserAdminRepository_Find_Call) Return(user *domain.User, err error) *MockUserAdminRepository_Find_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserAdminRepository_Find_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.User, error)) *MockUserAdminRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function for the type MockUserAdminRepository
func (_mock *MockUserAdminRepository) FindByName(context1 context.Context, s string) (*domain.User, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAdminRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockUserAdminRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockUserAdminRepository_Expecter) FindByName(context1 interface{}, s interface{}) *MockUserAdminRepository_FindByName_Call {
	return &MockUserAdminRepository_FindByName_Call{Call: _e.mock.On("FindByName", context1, s)}
}

func (_c *MockUserAdminRepository_FindByName_Call) Run(run func(context1 context.Context, s string)) *MockUserAdminRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserAdminRepository_FindByName_Call) Return(user *domain.User, err error) *MockUserAdminRepository_FindByName_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserAdminRepository_FindByName_Call) RunAndReturn(run func(context1 context.Context, s string) (*domain.User, error)) *MockUserAdminRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockUserAdminRepository
func (_mock *MockUserAdminRepository) List(ctx context.Context, limit int, offset int) ([]*domain.User, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain.User, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*domain.User); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAdminRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUserAdminRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockUserAdminRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *MockUserAdminRepository_List_Call {
	return &MockUserAdminRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockUserAdminRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockUserAdminRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserAdminRepository_List_Call) Return(users []*domain.User, err error) *MockUserAdminRepository_List_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserAdminRepository_List_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*domain.User, error)) *MockUserAdminRepository_List_Call {
	_c.Call.Return(run)
	return _c
}
