// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/tiny-auth-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRoleRepository creates a new instance of MockRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleRepository {
	mock := &MockRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoleRepository is an autogenerated mock type for the RoleRepository type
type MockRoleRepository struct {
	mock.Mock
}

type MockRoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleRepository) EXPECT() *MockRoleRepository_Expecter {
	return &MockRoleRepository_Expecter{mock: &_m.Mock}
}

// Change provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) Change(ctx context.Context, entity *domain.Role) (*domain.Role, error) {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Change")
	}

	var r0 *domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Role) (*domain.Role, error)); ok {
		return returnFunc(ctx, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Role) *domain.Role); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Role) error); ok {
		r1 = returnFunc(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleRepository_Change_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Change'
type MockRoleRepository_Change_Call struct {
	*mock.Call
}

// Change is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *domain.Role
func (_e *MockRoleRepository_Expecter) Change(ctx interface{}, entity interface{}) *MockRoleRepository_Change_Call {
	return &MockRoleRepository_Change_Call{Call: _e.mock.On("Change", ctx, entity)}
}

func (_c *MockRoleRepository_Change_Call) Run(run func(ctx context.Context, entity *domain.Role)) *MockRoleRepository_Change_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Role
		if args[1] != nil {
			arg1 = args[1].(*domain.Role)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_Change_Call) Return(role *domain.Role, err error) *MockRoleRepository_Change_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockRoleRepository_Change_Call) RunAndReturn(run func(ctx context.Context, entity *domain.Role) (*domain.Role, error)) *MockRoleRepository_Change_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) Create(ctx context.Context, entity *domain.Role) (*domain.Role, error) {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Role) (*domain.Role, error)); ok {
		return returnFunc(ctx, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Role) *domain.Role); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Role) error); ok {
		r1 = returnFunc(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *domain.Role
func (_e *MockRoleRepository_Expecter) Create(ctx interface{}, entity interface{}) *MockRoleRepository_Create_Call {
	return &MockRoleRepository_Create_Call{Call: _e.mock.On("Create", ctx, entity)}
}

func (_c *MockRoleRepository_Create_Call) Run(run func(ctx context.Context, entity *domain.Role)) *MockRoleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Role
		if args[1] != nil {
			arg1 = args[1].(*domain.Role)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_Create_Call) Return(role *domain.Role, err error) *MockRoleRepository_Create_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockRoleRepository_Create_Call) RunAndReturn(run func(ctx context.Context, entity *domain.Role) (*domain.Role, error)) *MockRoleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRoleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRoleRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRoleRepository_Delete_Call {
	return &MockRoleRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRoleRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockRoleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_Delete_Call) Return(err error) *MockRoleRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoleRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockRoleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) Find(ctx context.Context, id string) (*domain.Role, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Role, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Role); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockRoleRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRoleRepository_Expecter) Find(ctx interface{}, id interface{}) *MockRoleRepository_Find_Call {
	return &MockRoleRepository_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockRoleRepository_Find_Call) Run(run func(ctx context.Context, id string)) *MockRoleRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_Find_Call) Return(role *domain.Role, err error) *MockRoleRepository_Find_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockRoleRepository_Find_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Role, error)) *MockRoleRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) FindByName(context1 context.Context, s string) (*domain.Role, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Role, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Role); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockRoleRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockRoleRepository_Expecter) FindByName(context1 interface{}, s interface{}) *MockRoleRepository_FindByName_Call {
	return &MockRoleRepository_FindByName_Call{Call: _e.mock.On("FindByName", context1, s)}
}

func (_c *MockRoleRepository_FindByName_Call) Run(run func(context1 context.Context, s string)) *MockRoleRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_FindByName_Call) Return(role *domain.Role, err error) *MockRoleRepository_FindByName_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockRoleRepository_FindByName_Call) RunAndReturn(run func(context1 context.Context, s string) (*domain.Role, error)) *MockRoleRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) List(ctx context.Context, limit int, offset int) ([]*domain.Role, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain.Role, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*domain.Role); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRoleRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockRoleRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *MockRoleRepository_List_Call {
	return &MockRoleRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockRoleRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockRoleRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRoleRepository_List_Call) Return(roles []*domain.Role, err error) *MockRoleRepository_List_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *MockRoleRepository_List_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*domain.Role, error)) *MockRoleRepository_List_Call {
	_c.Call.Return(run)
	return _c
}
