// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/tiny-auth-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRolesAdminRepository creates a new instance of MockUserRolesAdminRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRolesAdminRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRolesAdminRepository {
	mock := &MockUserRolesAdminRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRolesAdminRepository is an autogenerated mock type for the UserRolesAdminRepository type
type MockUserRolesAdminRepository struct {
	mock.Mock
}

type MockUserRolesAdminRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRolesAdminRepository) EXPECT() *MockUserRolesAdminRepository_Expecter {
	return &MockUserRolesAdminRepository_Expecter{mock: &_m.Mock}
}

// Change provides a mock function for the type MockUserRolesAdminRepository
func (_mock *MockUserRolesAdminRepository) Change(ctx context.Context, ownerID string, entity *domain.Role) (*domain.Role, error) {
	ret := _mock.Called(ctx, ownerID, entity)

	if len(ret) == 0 {
		panic("no return value specified for Change")
	}

	var r0 *domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *domain.Role) (*domain.Role, error)); ok {
		return returnFunc(ctx, ownerID, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *domain.Role) *domain.Role); ok {
		r0 = returnFunc(ctx, ownerID, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *domain.Role) error); ok {
		r1 = returnFunc(ctx, ownerID, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRolesAdminRepository_Change_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Change'
type MockUserRolesAdminRepository_Change_Call struct {
	*mock.Call
}

// Change is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - entity *domain.Role
func (_e *MockUserRolesAdminRepository_Expecter) Change(ctx interface{}, ownerID interface{}, entity interface{}) *MockUserRolesAdminRepository_Change_Call {
	return &MockUserRolesAdminRepository_Change_Call{Call: _e.mock.On("Change", ctx, ownerID, entity)}
}

func (_c *MockUserRolesAdminRepository_Change_Call) Run(run func(ctx context.Context, ownerID string, entity *domain.Role)) *MockUserRolesAdminRepository_Change_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *domain.Role
		if args[2] != nil {
			arg2 = args[2].(*domain.Role)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRolesAdminRepository_Change_Call) Return(role *domain.Role, err error) *MockUserRolesAdminRepository_Change_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockUserRolesAdminRepository_Change_Call) RunAndReturn(run func(ctx context.Context, ownerID string, entity *domain.Role) (*domain.Role, error)) *MockUserRolesAdminRepository_Change_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockUserRolesAdminRepository
func (_mock *MockUserRolesAdminRepository) Create(ctx context.Context, ownerID string, entity *domain.Role) (*domain.Role, error) {
	ret := _mock.Called(ctx, ownerID, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *domain.Role) (*domain.Role, error)); ok {
		return returnFunc(ctx, ownerID, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *domain.Role) *domain.Role); ok {
		r0 = returnFunc(ctx, ownerID, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *domain.Role) error); ok {
		r1 = returnFunc(ctx, ownerID, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRolesAdminRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRolesAdminRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - entity *domain.Role
func (_e *MockUserRolesAdminRepository_Expecter) Create(ctx interface{}, ownerID interface{}, entity interface{}) *MockUserRolesAdminRepository_Create_Call {
	return &MockUserRolesAdminRepository_Create_Call{Call: _e.mock.On("Create", ctx, ownerID, entity)}
}

func (_c *MockUserRolesAdminRepository_Create_Call) Run(run func(ctx context.Context, ownerID string, entity *domain.Role)) *MockUserRolesAdminRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *domain.Role
		if args[2] != nil {
			arg2 = args[2].(*domain.Role)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRolesAdminRepository_Create_Call) Return(role *domain.Role, err error) *MockUserRolesAdminRepository_Create_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockUserRolesAdminRepository_Create_Call) RunAndReturn(run func(ctx context.Context, ownerID string, entity *domain.Role) (*domain.Role, error)) *MockUserRolesAdminRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserRolesAdminRepository
func (_mock *MockUserRolesAdminRepository) Delete(ctx context.Context, ownerID string, id string) error {
	ret := _mock.Called(ctx, ownerID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, ownerID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRolesAdminRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserRolesAdminRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - id string
func (_e *MockUserRolesAdminRepository_Expecter) Delete(ctx interface{}, ownerID interface{}, id interface{}) *MockUserRolesAdminRepository_Delete_Call {
	return &MockUserRolesAdminRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, ownerID, id)}
}

func (_c *MockUserRolesAdminRepository_Delete_Call) Run(run func(ctx context.Context, ownerID string, id string)) *MockUserRolesAdminRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRolesAdminRepository_Delete_Call) Return(err error) *MockUserRolesAdminRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRolesAdminRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, ownerID string, id string) error) *MockUserRolesAdminRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAll provides a mock function for the type MockUserRolesAdminRepository
func (_mock *MockUserRolesAdminRepository) DeleteAll(ctx context.Context, ownerID string) error {
	ret := _mock.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, ownerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRolesAdminRepository_DeleteAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAll'
type MockUserRolesAdminRepository_DeleteAll_Call struct {
	*mock.Call
}

// DeleteAll is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
func (_e *MockUserRolesAdminRepository_Expecter) DeleteAll(ctx interface{}, ownerID interface{}) *MockUserRolesAdminRepository_DeleteAll_Call {
	return &MockUserRolesAdminRepository_DeleteAll_Call{Call: _e.mock.On("DeleteAll", ctx, ownerID)}
}

func (_c *MockUserRolesAdminRepository_DeleteAll_Call) Run(run func(ctx context.Context, ownerID string)) *MockUserRolesAdminRepository_DeleteAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRolesAdminRepository_DeleteAll_Call) Return(err error) *MockUserRolesAdminRepository_DeleteAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRolesAdminRepository_DeleteAll_Call) RunAndReturn(run func(ctx context.Context, ownerID string) error) *MockUserRolesAdminRepository_DeleteAll_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockUserRolesAdminRepository
func (_mock *MockUserRolesAdminRepository) Find(ctx context.Context, ownerID string, id string) (*domain.Role, error) {
	ret := _mock.Called(ctx, ownerID, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Role, error)); ok {
		return returnFunc(ctx, ownerID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.Role); ok {
		r0 = returnFunc(ctx, ownerID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ownerID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRolesAdminRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockUserRolesAdminRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - id string
func (_e *MockUserRolesAdminRepository_Expecter) Find(ctx interface{}, ownerID interface{}, id interface{}) *MockUserRolesAdminRepository_Find_Call {
	return &MockUserRolesAdminRepository_Find_Call{Call: _e.mock.On("Find", ctx, ownerID, id)}
}

func (_c *MockUserRolesAdminRepository_Find_Call) Run(run func(ctx context.Context, ownerID string, id string)) *MockUserRolesAdminRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRolesAdminRepository_Find_Call) Return(role *domain.Role, err error) *MockUserRolesAdminRepository_Find_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockUserRolesAdminRepository_Find_Call) RunAndReturn(run func(ctx context.Context, ownerID string, id string) (*domain.Role, error)) *MockUserRolesAdminRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockUserRolesAdminRepository
func (_mock *MockUserRolesAdminRepository) List(ctx context.Context, ownerID string, limit int, offset int) ([]*domain.Role, error) {
	ret := _mock.Called(ctx, ownerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*domain.Role, error)); ok {
		return returnFunc(ctx, ownerID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []*domain.Role); ok {
		r0 = returnFunc(ctx, ownerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, ownerID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRolesAdminRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUserRolesAdminRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - limit int
//   - offset int
func (_e *MockUserRolesAdminRepository_Expecter) List(ctx interface{}, ownerID interface{}, limit interface{}, offset interface{}) *MockUserRolesAdminRepository_List_Call {
	return &MockUserRolesAdminRepository_List_Call{Call: _e.mock.On("List", ctx, ownerID, limit, offset)}
}

func (_c *MockUserRolesAdminRepository_List_Call) Run(run func(ctx context.Context, ownerID string, limit int, offset int)) *MockUserRolesAdminRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserRolesAdminRepository_List_Call) Return(roles []*domain.Role, err error) *MockUserRolesAdminRepository_List_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *MockUserRolesAdminRepository_List_Call) RunAndReturn(run func(ctx context.Context, ownerID string, limit int, offset int) ([]*domain.Role, error)) *MockUserRolesAdminRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function for the type MockUserRolesAdminRepository
func (_mock *MockUserRolesAdminRepository) ListAll(ctx context.Context, ownerID string) ([]*domain.Role, error) {
	ret := _mock.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []*domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Role, error)); ok {
		return returnFunc(ctx, ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.Role); ok {
		r0 = returnFunc(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRolesAdminRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockUserRolesAdminRepository_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
func (_e *MockUserRolesAdminRepository_Expecter) ListAll(ctx interface{}, ownerID interface{}) *MockUserRolesAdminRepository_ListAll_Call {
	return &MockUserRolesAdminRepository_ListAll_Call{Call: _e.mock.On("ListAll", ctx, ownerID)}
}

func (_c *MockUserRolesAdminRepository_ListAll_Call) Run(run func(ctx context.Context, ownerID string)) *MockUserRolesAdminRepository_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRolesAdminRepository_ListAll_Call) Return(roles []*domain.Role, err error) *MockUserRolesAdminRepository_ListAll_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *MockUserRolesAdminRepository_ListAll_Call) RunAndReturn(run func(ctx context.Context, ownerID string) ([]*domain.Role, error)) *MockUserRolesAdminRepository_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// ListAllByOwners provides a mock function for the type MockUserRolesAdminRepository
func (_mock *MockUserRolesAdminRepository) ListAllByOwners(ctx context.Context, ownerIDs ...string) (map[string][]*domain.Role, error) {
	var tmpRet mock.Arguments
	if len(ownerIDs) > 0 {
		tmpRet = _mock.Called(ctx, ownerIDs)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListAllByOwners")
	}

	var r0 map[string][]*domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) (map[string][]*domain.Role, error)); ok {
		return returnFunc(ctx, ownerIDs...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) map[string][]*domain.Role); ok {
		r0 = returnFunc(ctx, ownerIDs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]*domain.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, ownerIDs...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRolesAdminRepository_ListAllByOwners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllByOwners'
type MockUserRolesAdminRepository_ListAllByOwners_Call struct {
	*mock.Call
}

// ListAllByOwners is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerIDs ...string
func (_e *MockUserRolesAdminRepository_Expecter) ListAllByOwners(ctx interface{}, ownerIDs ...interface{}) *MockUserRolesAdminRepository_ListAllByOwners_Call {
	return &MockUserRolesAdminRepository_ListAllByOwners_Call{Call: _e.mock.On("ListAllByOwners",
		append([]interface{}{ctx}, ownerIDs...)...)}
}

func (_c *MockUserRolesAdminRepository_ListAllByOwners_Call) Run(run func(ctx context.Context, ownerIDs ...string)) *MockUserRolesAdminRepository_ListAllByOwners_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockUserRolesAdminRepository_ListAllByOwners_Call) Return(stringToRoles map[string][]*domain.Role, err error) *MockUserRolesAdminRepository_ListAllByOwners_Call {
	_c.Call.Return(stringToRoles, err)
	return _c
}

func (_c *MockUserRolesAdminRepository_ListAllByOwners_Call) RunAndReturn(run func(ctx context.Context, ownerIDs ...string) (map[string][]*domain.Role, error)) *MockUserRolesAdminRepository_ListAllByOwners_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockUserRolesAdminRepository
func (_mock *MockUserRolesAdminRepository) Save(ctx context.Context, ownerID string, owned []*domain.Role) ([]*domain.Role, error) {
	ret := _mock.Called(ctx, ownerID, owned)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 []*domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []*domain.Role) ([]*domain.Role, error)); ok {
		return returnFunc(ctx, ownerID, owned)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []*domain.Role) []*domain.Role); ok {
		r0 = returnFunc(ctx, ownerID, owned)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []*domain.Role) error); ok {
		r1 = returnFunc(ctx, ownerID, owned)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRolesAdminRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockUserRolesAdminRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - owned []*domain.Role
func (_e *MockUserRolesAdminRepository_Expecter) Save(ctx interface{}, ownerID interface{}, owned interface{}) *MockUserRolesAdminRepository_Save_Call {
	return &MockUserRolesAdminRepository_Save_Call{Call: _e.mock.On("Save", ctx, ownerID, owned)}
}

func (_c *MockUserRolesAdminRepository_Save_Call) Run(run func(ctx context.Context, ownerID string, owned []*domain.Role)) *MockUserRolesAdminRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*domain.Role
		if args[2] != nil {
			arg2 = args[2].([]*domain.Role)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRolesAdminRepository_Save_Call) Return(roles []*domain.Role, err error) *MockUserRolesAdminRepository_Save_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *MockUserRolesAdminRepository_Save_Call) RunAndReturn(run func(ctx context.Context, ownerID string, owned []*domain.Role) ([]*domain.Role, error)) *MockUserRolesAdminRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
