# Выбор проверяемых правил
# "inherit" означает взять дефолтный набор правил staticcheck
# Знаки минус "-" отключают конкретные проверки
checks = ["all", "-ST1000", "-ST1020", "-ST1021", "-ST1022"]

# Указание целевой версии Go для вашего проекта
go_version = "1.26"
