// Code generated by go-swagger; DO NOT EDIT.

package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1AdminRolesIDParams creates a new GetAPIV1AdminRolesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1AdminRolesIDParams() *GetAPIV1AdminRolesIDParams {
	return &GetAPIV1AdminRolesIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1AdminRolesIDParamsWithTimeout creates a new GetAPIV1AdminRolesIDParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1AdminRolesIDParamsWithTimeout(timeout time.Duration) *GetAPIV1AdminRolesIDParams {
	return &GetAPIV1AdminRolesIDParams{
		timeout: timeout,
	}
}

// NewGetAPIV1AdminRolesIDParamsWithContext creates a new GetAPIV1AdminRolesIDParams object
// with the ability to set a context for a request.
func NewGetAPIV1AdminRolesIDParamsWithContext(ctx context.Context) *GetAPIV1AdminRolesIDParams {
	return &GetAPIV1AdminRolesIDParams{
		Context: ctx,
	}
}

// NewGetAPIV1AdminRolesIDParamsWithHTTPClient creates a new GetAPIV1AdminRolesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1AdminRolesIDParamsWithHTTPClient(client *http.Client) *GetAPIV1AdminRolesIDParams {
	return &GetAPIV1AdminRolesIDParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1AdminRolesIDParams contains all the parameters to send to the API endpoint

	for the get API v1 admin roles ID operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1AdminRolesIDParams struct {

	/* ID.

	   ID записи

	   Format: string
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 admin roles ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1AdminRolesIDParams) WithDefaults() *GetAPIV1AdminRolesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 admin roles ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1AdminRolesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v1 admin roles ID params
func (o *GetAPIV1AdminRolesIDParams) WithTimeout(timeout time.Duration) *GetAPIV1AdminRolesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 admin roles ID params
func (o *GetAPIV1AdminRolesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 admin roles ID params
func (o *GetAPIV1AdminRolesIDParams) WithContext(ctx context.Context) *GetAPIV1AdminRolesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 admin roles ID params
func (o *GetAPIV1AdminRolesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 admin roles ID params
func (o *GetAPIV1AdminRolesIDParams) WithHTTPClient(client *http.Client) *GetAPIV1AdminRolesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 admin roles ID params
func (o *GetAPIV1AdminRolesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get API v1 admin roles ID params
func (o *GetAPIV1AdminRolesIDParams) WithID(id string) *GetAPIV1AdminRolesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get API v1 admin roles ID params
func (o *GetAPIV1AdminRolesIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1AdminRolesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
