// Code generated by go-swagger; DO NOT EDIT.

package role

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1AdminRolesSearchParams creates a new GetAPIV1AdminRolesSearchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1AdminRolesSearchParams() *GetAPIV1AdminRolesSearchParams {
	return &GetAPIV1AdminRolesSearchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1AdminRolesSearchParamsWithTimeout creates a new GetAPIV1AdminRolesSearchParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1AdminRolesSearchParamsWithTimeout(timeout time.Duration) *GetAPIV1AdminRolesSearchParams {
	return &GetAPIV1AdminRolesSearchParams{
		timeout: timeout,
	}
}

// NewGetAPIV1AdminRolesSearchParamsWithContext creates a new GetAPIV1AdminRolesSearchParams object
// with the ability to set a context for a request.
func NewGetAPIV1AdminRolesSearchParamsWithContext(ctx context.Context) *GetAPIV1AdminRolesSearchParams {
	return &GetAPIV1AdminRolesSearchParams{
		Context: ctx,
	}
}

// NewGetAPIV1AdminRolesSearchParamsWithHTTPClient creates a new GetAPIV1AdminRolesSearchParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1AdminRolesSearchParamsWithHTTPClient(client *http.Client) *GetAPIV1AdminRolesSearchParams {
	return &GetAPIV1AdminRolesSearchParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1AdminRolesSearchParams contains all the parameters to send to the API endpoint

	for the get API v1 admin roles search operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1AdminRolesSearchParams struct {

	/* Name.

	   name записи

	   Format: string
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 admin roles search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1AdminRolesSearchParams) WithDefaults() *GetAPIV1AdminRolesSearchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 admin roles search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1AdminRolesSearchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v1 admin roles search params
func (o *GetAPIV1AdminRolesSearchParams) WithTimeout(timeout time.Duration) *GetAPIV1AdminRolesSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 admin roles search params
func (o *GetAPIV1AdminRolesSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 admin roles search params
func (o *GetAPIV1AdminRolesSearchParams) WithContext(ctx context.Context) *GetAPIV1AdminRolesSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 admin roles search params
func (o *GetAPIV1AdminRolesSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 admin roles search params
func (o *GetAPIV1AdminRolesSearchParams) WithHTTPClient(client *http.Client) *GetAPIV1AdminRolesSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 admin roles search params
func (o *GetAPIV1AdminRolesSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get API v1 admin roles search params
func (o *GetAPIV1AdminRolesSearchParams) WithName(name string) *GetAPIV1AdminRolesSearchParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get API v1 admin roles search params
func (o *GetAPIV1AdminRolesSearchParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1AdminRolesSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param name
	qrName := o.Name
	qName := qrName
	if qName != "" {

		if err := r.SetQueryParam("name", qName); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
