// Code generated by go-swagger; DO NOT EDIT.

package role

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-auth-service/pkg/api/http/auth/v1/models"
)

// GetAPIV1AdminRolesIDReader is a Reader for the GetAPIV1AdminRolesID structure.
type GetAPIV1AdminRolesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1AdminRolesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1AdminRolesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetAPIV1AdminRolesIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV1AdminRolesIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1AdminRolesIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/admin/roles/{id}] GetAPIV1AdminRolesID", response, response.Code())
	}
}

// NewGetAPIV1AdminRolesIDOK creates a GetAPIV1AdminRolesIDOK with default headers values
func NewGetAPIV1AdminRolesIDOK() *GetAPIV1AdminRolesIDOK {
	return &GetAPIV1AdminRolesIDOK{}
}

/*
GetAPIV1AdminRolesIDOK describes a response with status code 200, with default header values.

Роль
*/
type GetAPIV1AdminRolesIDOK struct {
	Payload *models.RoleDTO
}

// IsSuccess returns true when this get Api v1 admin roles Id o k response has a 2xx status code
func (o *GetAPIV1AdminRolesIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 admin roles Id o k response has a 3xx status code
func (o *GetAPIV1AdminRolesIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 admin roles Id o k response has a 4xx status code
func (o *GetAPIV1AdminRolesIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 admin roles Id o k response has a 5xx status code
func (o *GetAPIV1AdminRolesIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 admin roles Id o k response a status code equal to that given
func (o *GetAPIV1AdminRolesIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 admin roles Id o k response
func (o *GetAPIV1AdminRolesIDOK) Code() int {
	return 200
}

func (o *GetAPIV1AdminRolesIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/admin/roles/{id}][%d] getApiV1AdminRolesIdOK %s", 200, payload)
}

func (o *GetAPIV1AdminRolesIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/admin/roles/{id}][%d] getApiV1AdminRolesIdOK %s", 200, payload)
}

func (o *GetAPIV1AdminRolesIDOK) GetPayload() *models.RoleDTO {
	return o.Payload
}

func (o *GetAPIV1AdminRolesIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RoleDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1AdminRolesIDForbidden creates a GetAPIV1AdminRolesIDForbidden with default headers values
func NewGetAPIV1AdminRolesIDForbidden() *GetAPIV1AdminRolesIDForbidden {
	return &GetAPIV1AdminRolesIDForbidden{}
}

/*
GetAPIV1AdminRolesIDForbidden describes a response with status code 403, with default header values.

В доступе отказано
*/
type GetAPIV1AdminRolesIDForbidden struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this get Api v1 admin roles Id forbidden response has a 2xx status code
func (o *GetAPIV1AdminRolesIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 admin roles Id forbidden response has a 3xx status code
func (o *GetAPIV1AdminRolesIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 admin roles Id forbidden response has a 4xx status code
func (o *GetAPIV1AdminRolesIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 admin roles Id forbidden response has a 5xx status code
func (o *GetAPIV1AdminRolesIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 admin roles Id forbidden response a status code equal to that given
func (o *GetAPIV1AdminRolesIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get Api v1 admin roles Id forbidden response
func (o *GetAPIV1AdminRolesIDForbidden) Code() int {
	return 403
}

func (o *GetAPIV1AdminRolesIDForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/admin/roles/{id}][%d] getApiV1AdminRolesIdForbidden %s", 403, payload)
}

func (o *GetAPIV1AdminRolesIDForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/admin/roles/{id}][%d] getApiV1AdminRolesIdForbidden %s", 403, payload)
}

func (o *GetAPIV1AdminRolesIDForbidden) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *GetAPIV1AdminRolesIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1AdminRolesIDNotFound creates a GetAPIV1AdminRolesIDNotFound with default headers values
func NewGetAPIV1AdminRolesIDNotFound() *GetAPIV1AdminRolesIDNotFound {
	return &GetAPIV1AdminRolesIDNotFound{}
}

/*
GetAPIV1AdminRolesIDNotFound describes a response with status code 404, with default header values.

Запись не найдена
*/
type GetAPIV1AdminRolesIDNotFound struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this get Api v1 admin roles Id not found response has a 2xx status code
func (o *GetAPIV1AdminRolesIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 admin roles Id not found response has a 3xx status code
func (o *GetAPIV1AdminRolesIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 admin roles Id not found response has a 4xx status code
func (o *GetAPIV1AdminRolesIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 admin roles Id not found response has a 5xx status code
func (o *GetAPIV1AdminRolesIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 admin roles Id not found response a status code equal to that given
func (o *GetAPIV1AdminRolesIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api v1 admin roles Id not found response
func (o *GetAPIV1AdminRolesIDNotFound) Code() int {
	return 404
}

func (o *GetAPIV1AdminRolesIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/admin/roles/{id}][%d] getApiV1AdminRolesIdNotFound %s", 404, payload)
}

func (o *GetAPIV1AdminRolesIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/admin/roles/{id}][%d] getApiV1AdminRolesIdNotFound %s", 404, payload)
}

func (o *GetAPIV1AdminRolesIDNotFound) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *GetAPIV1AdminRolesIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1AdminRolesIDInternalServerError creates a GetAPIV1AdminRolesIDInternalServerError with default headers values
func NewGetAPIV1AdminRolesIDInternalServerError() *GetAPIV1AdminRolesIDInternalServerError {
	return &GetAPIV1AdminRolesIDInternalServerError{}
}

/*
GetAPIV1AdminRolesIDInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера (пустое тело)
*/
type GetAPIV1AdminRolesIDInternalServerError struct {
}

// IsSuccess returns true when this get Api v1 admin roles Id internal server error response has a 2xx status code
func (o *GetAPIV1AdminRolesIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 admin roles Id internal server error response has a 3xx status code
func (o *GetAPIV1AdminRolesIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 admin roles Id internal server error response has a 4xx status code
func (o *GetAPIV1AdminRolesIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 admin roles Id internal server error response has a 5xx status code
func (o *GetAPIV1AdminRolesIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 admin roles Id internal server error response a status code equal to that given
func (o *GetAPIV1AdminRolesIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 admin roles Id internal server error response
func (o *GetAPIV1AdminRolesIDInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1AdminRolesIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/admin/roles/{id}][%d] getApiV1AdminRolesIdInternalServerError", 500)
}

func (o *GetAPIV1AdminRolesIDInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v1/admin/roles/{id}][%d] getApiV1AdminRolesIdInternalServerError", 500)
}

func (o *GetAPIV1AdminRolesIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
