// Code generated by go-swagger; DO NOT EDIT.

package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIV1AdminRolesParams creates a new GetAPIV1AdminRolesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1AdminRolesParams() *GetAPIV1AdminRolesParams {
	return &GetAPIV1AdminRolesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1AdminRolesParamsWithTimeout creates a new GetAPIV1AdminRolesParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1AdminRolesParamsWithTimeout(timeout time.Duration) *GetAPIV1AdminRolesParams {
	return &GetAPIV1AdminRolesParams{
		timeout: timeout,
	}
}

// NewGetAPIV1AdminRolesParamsWithContext creates a new GetAPIV1AdminRolesParams object
// with the ability to set a context for a request.
func NewGetAPIV1AdminRolesParamsWithContext(ctx context.Context) *GetAPIV1AdminRolesParams {
	return &GetAPIV1AdminRolesParams{
		Context: ctx,
	}
}

// NewGetAPIV1AdminRolesParamsWithHTTPClient creates a new GetAPIV1AdminRolesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1AdminRolesParamsWithHTTPClient(client *http.Client) *GetAPIV1AdminRolesParams {
	return &GetAPIV1AdminRolesParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1AdminRolesParams contains all the parameters to send to the API endpoint

	for the get API v1 admin roles operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1AdminRolesParams struct {

	/* Limit.

	   limit row count, max 1000

	   Format: int
	*/
	Limit *int64

	/* Offset.

	   offset, min 0, max n

	   Format: int
	*/
	Offset *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 admin roles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1AdminRolesParams) WithDefaults() *GetAPIV1AdminRolesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 admin roles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1AdminRolesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v1 admin roles params
func (o *GetAPIV1AdminRolesParams) WithTimeout(timeout time.Duration) *GetAPIV1AdminRolesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 admin roles params
func (o *GetAPIV1AdminRolesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 admin roles params
func (o *GetAPIV1AdminRolesParams) WithContext(ctx context.Context) *GetAPIV1AdminRolesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 admin roles params
func (o *GetAPIV1AdminRolesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 admin roles params
func (o *GetAPIV1AdminRolesParams) WithHTTPClient(client *http.Client) *GetAPIV1AdminRolesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 admin roles params
func (o *GetAPIV1AdminRolesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get API v1 admin roles params
func (o *GetAPIV1AdminRolesParams) WithLimit(limit *int64) *GetAPIV1AdminRolesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get API v1 admin roles params
func (o *GetAPIV1AdminRolesParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get API v1 admin roles params
func (o *GetAPIV1AdminRolesParams) WithOffset(offset *int64) *GetAPIV1AdminRolesParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get API v1 admin roles params
func (o *GetAPIV1AdminRolesParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1AdminRolesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
