// Code generated by go-swagger; DO NOT EDIT.

package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-auth-service/pkg/api/http/auth/v1/models"
)

// NewPostAPIV1AdminRolesParams creates a new PostAPIV1AdminRolesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1AdminRolesParams() *PostAPIV1AdminRolesParams {
	return &PostAPIV1AdminRolesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1AdminRolesParamsWithTimeout creates a new PostAPIV1AdminRolesParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1AdminRolesParamsWithTimeout(timeout time.Duration) *PostAPIV1AdminRolesParams {
	return &PostAPIV1AdminRolesParams{
		timeout: timeout,
	}
}

// NewPostAPIV1AdminRolesParamsWithContext creates a new PostAPIV1AdminRolesParams object
// with the ability to set a context for a request.
func NewPostAPIV1AdminRolesParamsWithContext(ctx context.Context) *PostAPIV1AdminRolesParams {
	return &PostAPIV1AdminRolesParams{
		Context: ctx,
	}
}

// NewPostAPIV1AdminRolesParamsWithHTTPClient creates a new PostAPIV1AdminRolesParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1AdminRolesParamsWithHTTPClient(client *http.Client) *PostAPIV1AdminRolesParams {
	return &PostAPIV1AdminRolesParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1AdminRolesParams contains all the parameters to send to the API endpoint

	for the post API v1 admin roles operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1AdminRolesParams struct {

	/* Input.

	   Роль
	*/
	Input *models.RoleDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 admin roles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AdminRolesParams) WithDefaults() *PostAPIV1AdminRolesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 admin roles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AdminRolesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 admin roles params
func (o *PostAPIV1AdminRolesParams) WithTimeout(timeout time.Duration) *PostAPIV1AdminRolesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 admin roles params
func (o *PostAPIV1AdminRolesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 admin roles params
func (o *PostAPIV1AdminRolesParams) WithContext(ctx context.Context) *PostAPIV1AdminRolesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 admin roles params
func (o *PostAPIV1AdminRolesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 admin roles params
func (o *PostAPIV1AdminRolesParams) WithHTTPClient(client *http.Client) *PostAPIV1AdminRolesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 admin roles params
func (o *PostAPIV1AdminRolesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInput adds the input to the post API v1 admin roles params
func (o *PostAPIV1AdminRolesParams) WithInput(input *models.RoleDTO) *PostAPIV1AdminRolesParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the post API v1 admin roles params
func (o *PostAPIV1AdminRolesParams) SetInput(input *models.RoleDTO) {
	o.Input = input
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1AdminRolesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
