// Code generated by go-swagger; DO NOT EDIT.

package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-auth-service/pkg/api/http/auth/v1/models"
)

// PostAPIV1AdminRolesReader is a Reader for the PostAPIV1AdminRoles structure.
type PostAPIV1AdminRolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1AdminRolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewPostAPIV1AdminRolesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1AdminRolesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostAPIV1AdminRolesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPostAPIV1AdminRolesConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1AdminRolesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/admin/roles] PostAPIV1AdminRoles", response, response.Code())
	}
}

// NewPostAPIV1AdminRolesCreated creates a PostAPIV1AdminRolesCreated with default headers values
func NewPostAPIV1AdminRolesCreated() *PostAPIV1AdminRolesCreated {
	return &PostAPIV1AdminRolesCreated{}
}

/*
PostAPIV1AdminRolesCreated describes a response with status code 201, with default header values.

Created
*/
type PostAPIV1AdminRolesCreated struct {
	Payload *models.RoleDTO
}

// IsSuccess returns true when this post Api v1 admin roles created response has a 2xx status code
func (o *PostAPIV1AdminRolesCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 admin roles created response has a 3xx status code
func (o *PostAPIV1AdminRolesCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 admin roles created response has a 4xx status code
func (o *PostAPIV1AdminRolesCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 admin roles created response has a 5xx status code
func (o *PostAPIV1AdminRolesCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 admin roles created response a status code equal to that given
func (o *PostAPIV1AdminRolesCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post Api v1 admin roles created response
func (o *PostAPIV1AdminRolesCreated) Code() int {
	return 201
}

func (o *PostAPIV1AdminRolesCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/admin/roles][%d] postApiV1AdminRolesCreated %s", 201, payload)
}

func (o *PostAPIV1AdminRolesCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/admin/roles][%d] postApiV1AdminRolesCreated %s", 201, payload)
}

func (o *PostAPIV1AdminRolesCreated) GetPayload() *models.RoleDTO {
	return o.Payload
}

func (o *PostAPIV1AdminRolesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RoleDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AdminRolesBadRequest creates a PostAPIV1AdminRolesBadRequest with default headers values
func NewPostAPIV1AdminRolesBadRequest() *PostAPIV1AdminRolesBadRequest {
	return &PostAPIV1AdminRolesBadRequest{}
}

/*
PostAPIV1AdminRolesBadRequest describes a response with status code 400, with default header values.

Кривые данные
*/
type PostAPIV1AdminRolesBadRequest struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 admin roles bad request response has a 2xx status code
func (o *PostAPIV1AdminRolesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 admin roles bad request response has a 3xx status code
func (o *PostAPIV1AdminRolesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 admin roles bad request response has a 4xx status code
func (o *PostAPIV1AdminRolesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 admin roles bad request response has a 5xx status code
func (o *PostAPIV1AdminRolesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 admin roles bad request response a status code equal to that given
func (o *PostAPIV1AdminRolesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 admin roles bad request response
func (o *PostAPIV1AdminRolesBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1AdminRolesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/admin/roles][%d] postApiV1AdminRolesBadRequest %s", 400, payload)
}

func (o *PostAPIV1AdminRolesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/admin/roles][%d] postApiV1AdminRolesBadRequest %s", 400, payload)
}

func (o *PostAPIV1AdminRolesBadRequest) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AdminRolesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AdminRolesForbidden creates a PostAPIV1AdminRolesForbidden with default headers values
func NewPostAPIV1AdminRolesForbidden() *PostAPIV1AdminRolesForbidden {
	return &PostAPIV1AdminRolesForbidden{}
}

/*
PostAPIV1AdminRolesForbidden describes a response with status code 403, with default header values.

В доступе отказано
*/
type PostAPIV1AdminRolesForbidden struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 admin roles forbidden response has a 2xx status code
func (o *PostAPIV1AdminRolesForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 admin roles forbidden response has a 3xx status code
func (o *PostAPIV1AdminRolesForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 admin roles forbidden response has a 4xx status code
func (o *PostAPIV1AdminRolesForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 admin roles forbidden response has a 5xx status code
func (o *PostAPIV1AdminRolesForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 admin roles forbidden response a status code equal to that given
func (o *PostAPIV1AdminRolesForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the post Api v1 admin roles forbidden response
func (o *PostAPIV1AdminRolesForbidden) Code() int {
	return 403
}

func (o *PostAPIV1AdminRolesForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/admin/roles][%d] postApiV1AdminRolesForbidden %s", 403, payload)
}

func (o *PostAPIV1AdminRolesForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/admin/roles][%d] postApiV1AdminRolesForbidden %s", 403, payload)
}

func (o *PostAPIV1AdminRolesForbidden) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AdminRolesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AdminRolesConflict creates a PostAPIV1AdminRolesConflict with default headers values
func NewPostAPIV1AdminRolesConflict() *PostAPIV1AdminRolesConflict {
	return &PostAPIV1AdminRolesConflict{}
}

/*
PostAPIV1AdminRolesConflict describes a response with status code 409, with default header values.

Уже существует
*/
type PostAPIV1AdminRolesConflict struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 admin roles conflict response has a 2xx status code
func (o *PostAPIV1AdminRolesConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 admin roles conflict response has a 3xx status code
func (o *PostAPIV1AdminRolesConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 admin roles conflict response has a 4xx status code
func (o *PostAPIV1AdminRolesConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 admin roles conflict response has a 5xx status code
func (o *PostAPIV1AdminRolesConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 admin roles conflict response a status code equal to that given
func (o *PostAPIV1AdminRolesConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the post Api v1 admin roles conflict response
func (o *PostAPIV1AdminRolesConflict) Code() int {
	return 409
}

func (o *PostAPIV1AdminRolesConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/admin/roles][%d] postApiV1AdminRolesConflict %s", 409, payload)
}

func (o *PostAPIV1AdminRolesConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/admin/roles][%d] postApiV1AdminRolesConflict %s", 409, payload)
}

func (o *PostAPIV1AdminRolesConflict) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AdminRolesConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AdminRolesInternalServerError creates a PostAPIV1AdminRolesInternalServerError with default headers values
func NewPostAPIV1AdminRolesInternalServerError() *PostAPIV1AdminRolesInternalServerError {
	return &PostAPIV1AdminRolesInternalServerError{}
}

/*
PostAPIV1AdminRolesInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера (пустое тело)
*/
type PostAPIV1AdminRolesInternalServerError struct {
}

// IsSuccess returns true when this post Api v1 admin roles internal server error response has a 2xx status code
func (o *PostAPIV1AdminRolesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 admin roles internal server error response has a 3xx status code
func (o *PostAPIV1AdminRolesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 admin roles internal server error response has a 4xx status code
func (o *PostAPIV1AdminRolesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 admin roles internal server error response has a 5xx status code
func (o *PostAPIV1AdminRolesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 admin roles internal server error response a status code equal to that given
func (o *PostAPIV1AdminRolesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 admin roles internal server error response
func (o *PostAPIV1AdminRolesInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1AdminRolesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v1/admin/roles][%d] postApiV1AdminRolesInternalServerError", 500)
}

func (o *PostAPIV1AdminRolesInternalServerError) String() string {
	return fmt.Sprintf("[POST /api/v1/admin/roles][%d] postApiV1AdminRolesInternalServerError", 500)
}

func (o *PostAPIV1AdminRolesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
