// Code generated by go-swagger; DO NOT EDIT.

package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-auth-service/pkg/api/http/auth/v1/models"
)

// NewPutAPIV1AdminRolesIDParams creates a new PutAPIV1AdminRolesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPIV1AdminRolesIDParams() *PutAPIV1AdminRolesIDParams {
	return &PutAPIV1AdminRolesIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIV1AdminRolesIDParamsWithTimeout creates a new PutAPIV1AdminRolesIDParams object
// with the ability to set a timeout on a request.
func NewPutAPIV1AdminRolesIDParamsWithTimeout(timeout time.Duration) *PutAPIV1AdminRolesIDParams {
	return &PutAPIV1AdminRolesIDParams{
		timeout: timeout,
	}
}

// NewPutAPIV1AdminRolesIDParamsWithContext creates a new PutAPIV1AdminRolesIDParams object
// with the ability to set a context for a request.
func NewPutAPIV1AdminRolesIDParamsWithContext(ctx context.Context) *PutAPIV1AdminRolesIDParams {
	return &PutAPIV1AdminRolesIDParams{
		Context: ctx,
	}
}

// NewPutAPIV1AdminRolesIDParamsWithHTTPClient creates a new PutAPIV1AdminRolesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPIV1AdminRolesIDParamsWithHTTPClient(client *http.Client) *PutAPIV1AdminRolesIDParams {
	return &PutAPIV1AdminRolesIDParams{
		HTTPClient: client,
	}
}

/*
PutAPIV1AdminRolesIDParams contains all the parameters to send to the API endpoint

	for the put API v1 admin roles ID operation.

	Typically these are written to a http.Request.
*/
type PutAPIV1AdminRolesIDParams struct {

	/* ID.

	   ID записи

	   Format: string
	*/
	ID string

	/* Input.

	   Роль
	*/
	Input *models.RoleDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put API v1 admin roles ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIV1AdminRolesIDParams) WithDefaults() *PutAPIV1AdminRolesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put API v1 admin roles ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIV1AdminRolesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put API v1 admin roles ID params
func (o *PutAPIV1AdminRolesIDParams) WithTimeout(timeout time.Duration) *PutAPIV1AdminRolesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API v1 admin roles ID params
func (o *PutAPIV1AdminRolesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API v1 admin roles ID params
func (o *PutAPIV1AdminRolesIDParams) WithContext(ctx context.Context) *PutAPIV1AdminRolesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API v1 admin roles ID params
func (o *PutAPIV1AdminRolesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API v1 admin roles ID params
func (o *PutAPIV1AdminRolesIDParams) WithHTTPClient(client *http.Client) *PutAPIV1AdminRolesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API v1 admin roles ID params
func (o *PutAPIV1AdminRolesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put API v1 admin roles ID params
func (o *PutAPIV1AdminRolesIDParams) WithID(id string) *PutAPIV1AdminRolesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put API v1 admin roles ID params
func (o *PutAPIV1AdminRolesIDParams) SetID(id string) {
	o.ID = id
}

// WithInput adds the input to the put API v1 admin roles ID params
func (o *PutAPIV1AdminRolesIDParams) WithInput(input *models.RoleDTO) *PutAPIV1AdminRolesIDParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the put API v1 admin roles ID params
func (o *PutAPIV1AdminRolesIDParams) SetInput(input *models.RoleDTO) {
	o.Input = input
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIV1AdminRolesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
