// Code generated by go-swagger; DO NOT EDIT.

package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new role API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new role API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new role API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for role API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteAPIV1AdminRolesID(params *DeleteAPIV1AdminRolesIDParams, opts ...ClientOption) (*DeleteAPIV1AdminRolesIDNoContent, error)

	GetAPIV1AdminRoles(params *GetAPIV1AdminRolesParams, opts ...ClientOption) (*GetAPIV1AdminRolesOK, error)

	GetAPIV1AdminRolesID(params *GetAPIV1AdminRolesIDParams, opts ...ClientOption) (*GetAPIV1AdminRolesIDOK, error)

	GetAPIV1AdminRolesSearch(params *GetAPIV1AdminRolesSearchParams, opts ...ClientOption) (*GetAPIV1AdminRolesSearchOK, error)

	PostAPIV1AdminRoles(params *PostAPIV1AdminRolesParams, opts ...ClientOption) (*PostAPIV1AdminRolesCreated, error)

	PutAPIV1AdminRolesID(params *PutAPIV1AdminRolesIDParams, opts ...ClientOption) (*PutAPIV1AdminRolesIDOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteAPIV1AdminRolesID удалениеs роли

Удаляет запись по её ID
*/
func (a *Client) DeleteAPIV1AdminRolesID(params *DeleteAPIV1AdminRolesIDParams, opts ...ClientOption) (*DeleteAPIV1AdminRolesIDNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteAPIV1AdminRolesIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteAPIV1AdminRolesID",
		Method:             "DELETE",
		PathPattern:        "/api/v1/admin/roles/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteAPIV1AdminRolesIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteAPIV1AdminRolesIDNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteAPIV1AdminRolesID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1AdminRoles получитьs

Получить список
*/
func (a *Client) GetAPIV1AdminRoles(params *GetAPIV1AdminRolesParams, opts ...ClientOption) (*GetAPIV1AdminRolesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIV1AdminRolesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1AdminRoles",
		Method:             "GET",
		PathPattern:        "/api/v1/admin/roles",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1AdminRolesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIV1AdminRolesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1AdminRoles: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1AdminRolesID получитьs

Получает запись по её ID
*/
func (a *Client) GetAPIV1AdminRolesID(params *GetAPIV1AdminRolesIDParams, opts ...ClientOption) (*GetAPIV1AdminRolesIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIV1AdminRolesIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1AdminRolesID",
		Method:             "GET",
		PathPattern:        "/api/v1/admin/roles/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1AdminRolesIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIV1AdminRolesIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1AdminRolesID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1AdminRolesSearch получитьs

Поиск записи
*/
func (a *Client) GetAPIV1AdminRolesSearch(params *GetAPIV1AdminRolesSearchParams, opts ...ClientOption) (*GetAPIV1AdminRolesSearchOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIV1AdminRolesSearchParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1AdminRolesSearch",
		Method:             "GET",
		PathPattern:        "/api/v1/admin/roles/search",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1AdminRolesSearchReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIV1AdminRolesSearchOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1AdminRolesSearch: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPIV1AdminRoles созданиеs роли

Сохраняет новые тестовые данные
*/
func (a *Client) PostAPIV1AdminRoles(params *PostAPIV1AdminRolesParams, opts ...ClientOption) (*PostAPIV1AdminRolesCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAPIV1AdminRolesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAPIV1AdminRoles",
		Method:             "POST",
		PathPattern:        "/api/v1/admin/roles",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAPIV1AdminRolesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAPIV1AdminRolesCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAPIV1AdminRoles: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutAPIV1AdminRolesID изменяетs роль

Изменение атрибутов роли
*/
func (a *Client) PutAPIV1AdminRolesID(params *PutAPIV1AdminRolesIDParams, opts ...ClientOption) (*PutAPIV1AdminRolesIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutAPIV1AdminRolesIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutAPIV1AdminRolesID",
		Method:             "PUT",
		PathPattern:        "/api/v1/admin/roles/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutAPIV1AdminRolesIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutAPIV1AdminRolesIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutAPIV1AdminRolesID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
