// Code generated by go-swagger; DO NOT EDIT.

package auth

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new auth API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new auth API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new auth API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for auth API.
*/
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// PostAPIV1Auth аутентификация.
	PostAPIV1Auth(params *PostAPIV1AuthParams, opts ...ClientOption) (*PostAPIV1AuthOK, error)

	// PostAPIV1AuthContext аутентификация.
	PostAPIV1AuthContext(ctx context.Context, params *PostAPIV1AuthParams, opts ...ClientOption) (*PostAPIV1AuthOK, error)

	// PostAPIV1AuthSimple аутентификация.
	PostAPIV1AuthSimple(params *PostAPIV1AuthSimpleParams, opts ...ClientOption) (*PostAPIV1AuthSimpleOK, error)

	// PostAPIV1AuthSimpleContext аутентификация.
	PostAPIV1AuthSimpleContext(ctx context.Context, params *PostAPIV1AuthSimpleParams, opts ...ClientOption) (*PostAPIV1AuthSimpleOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

/*
PostAPIV1Authаутентификацияs.

Аутентификация и авторизация пользователя.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PostAPIV1AuthContext] instead.
*/
func (a *Client) PostAPIV1Auth(params *PostAPIV1AuthParams, opts ...ClientOption) (*PostAPIV1AuthOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostAPIV1AuthContext(ctx, params, opts...)
}

/*
PostAPIV1AuthContextаутентификацияs.

Аутентификация и авторизация пользователя.

Do not use the deprecated [PostAPIV1AuthParams.Context] with this method: it would be ignored.
*/
func (a *Client) PostAPIV1AuthContext(ctx context.Context, params *PostAPIV1AuthParams, opts ...ClientOption) (*PostAPIV1AuthOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAPIV1AuthParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostAPIV1Auth",
		Method:             "POST",
		PathPattern:        "/api/v1/auth",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAPIV1AuthReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAPIV1AuthOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAPIV1Auth: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPIV1AuthSimpleаутентификацияs.

Аутентификация и авторизация пользователя.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.PostAPIV1AuthSimpleContext] instead.
*/
func (a *Client) PostAPIV1AuthSimple(params *PostAPIV1AuthSimpleParams, opts ...ClientOption) (*PostAPIV1AuthSimpleOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.PostAPIV1AuthSimpleContext(ctx, params, opts...)
}

/*
PostAPIV1AuthSimpleContextаутентификацияs.

Аутентификация и авторизация пользователя.

Do not use the deprecated [PostAPIV1AuthSimpleParams.Context] with this method: it would be ignored.
*/
func (a *Client) PostAPIV1AuthSimpleContext(ctx context.Context, params *PostAPIV1AuthSimpleParams, opts ...ClientOption) (*PostAPIV1AuthSimpleOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAPIV1AuthSimpleParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "PostAPIV1AuthSimple",
		Method:             "POST",
		PathPattern:        "/api/v1/auth/simple",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAPIV1AuthSimpleReader{formats: a.formats},
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAPIV1AuthSimpleOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAPIV1AuthSimple: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [AuthParams].
	ctx context.Context
}
