// Code generated by go-swagger; DO NOT EDIT.

package auth

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-auth-service/pkg/api/http/auth/v1/models"
)

// PostAPIV1AuthSimpleReader is a Reader for the PostAPIV1AuthSimple structure.
type PostAPIV1AuthSimpleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1AuthSimpleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV1AuthSimpleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1AuthSimpleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAPIV1AuthSimpleUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1AuthSimpleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/auth/simple] PostAPIV1AuthSimple", response, response.Code())
	}
}

// NewPostAPIV1AuthSimpleOK creates a PostAPIV1AuthSimpleOK with default headers values
func NewPostAPIV1AuthSimpleOK() *PostAPIV1AuthSimpleOK {
	return &PostAPIV1AuthSimpleOK{}
}

/*
PostAPIV1AuthSimpleOK describes a response with status code 200, with default header values.

OK
*/
type PostAPIV1AuthSimpleOK struct {
	Payload *models.LoggedInDTO
}

// IsSuccess returns true when this post Api v1 auth simple o k response has a 2xx status code
func (o *PostAPIV1AuthSimpleOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 auth simple o k response has a 3xx status code
func (o *PostAPIV1AuthSimpleOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 auth simple o k response has a 4xx status code
func (o *PostAPIV1AuthSimpleOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 auth simple o k response has a 5xx status code
func (o *PostAPIV1AuthSimpleOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 auth simple o k response a status code equal to that given
func (o *PostAPIV1AuthSimpleOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api v1 auth simple o k response
func (o *PostAPIV1AuthSimpleOK) Code() int {
	return 200
}

func (o *PostAPIV1AuthSimpleOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth/simple][%d] postApiV1AuthSimpleOK %s", 200, payload)
}

func (o *PostAPIV1AuthSimpleOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth/simple][%d] postApiV1AuthSimpleOK %s", 200, payload)
}

func (o *PostAPIV1AuthSimpleOK) GetPayload() *models.LoggedInDTO {
	return o.Payload
}

func (o *PostAPIV1AuthSimpleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LoggedInDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuthSimpleBadRequest creates a PostAPIV1AuthSimpleBadRequest with default headers values
func NewPostAPIV1AuthSimpleBadRequest() *PostAPIV1AuthSimpleBadRequest {
	return &PostAPIV1AuthSimpleBadRequest{}
}

/*
PostAPIV1AuthSimpleBadRequest describes a response with status code 400, with default header values.

Кривые данные
*/
type PostAPIV1AuthSimpleBadRequest struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 auth simple bad request response has a 2xx status code
func (o *PostAPIV1AuthSimpleBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 auth simple bad request response has a 3xx status code
func (o *PostAPIV1AuthSimpleBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 auth simple bad request response has a 4xx status code
func (o *PostAPIV1AuthSimpleBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 auth simple bad request response has a 5xx status code
func (o *PostAPIV1AuthSimpleBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 auth simple bad request response a status code equal to that given
func (o *PostAPIV1AuthSimpleBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 auth simple bad request response
func (o *PostAPIV1AuthSimpleBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1AuthSimpleBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth/simple][%d] postApiV1AuthSimpleBadRequest %s", 400, payload)
}

func (o *PostAPIV1AuthSimpleBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth/simple][%d] postApiV1AuthSimpleBadRequest %s", 400, payload)
}

func (o *PostAPIV1AuthSimpleBadRequest) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuthSimpleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuthSimpleUnauthorized creates a PostAPIV1AuthSimpleUnauthorized with default headers values
func NewPostAPIV1AuthSimpleUnauthorized() *PostAPIV1AuthSimpleUnauthorized {
	return &PostAPIV1AuthSimpleUnauthorized{}
}

/*
PostAPIV1AuthSimpleUnauthorized describes a response with status code 401, with default header values.

Не авторизован
*/
type PostAPIV1AuthSimpleUnauthorized struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 auth simple unauthorized response has a 2xx status code
func (o *PostAPIV1AuthSimpleUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 auth simple unauthorized response has a 3xx status code
func (o *PostAPIV1AuthSimpleUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 auth simple unauthorized response has a 4xx status code
func (o *PostAPIV1AuthSimpleUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 auth simple unauthorized response has a 5xx status code
func (o *PostAPIV1AuthSimpleUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 auth simple unauthorized response a status code equal to that given
func (o *PostAPIV1AuthSimpleUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 auth simple unauthorized response
func (o *PostAPIV1AuthSimpleUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1AuthSimpleUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth/simple][%d] postApiV1AuthSimpleUnauthorized %s", 401, payload)
}

func (o *PostAPIV1AuthSimpleUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth/simple][%d] postApiV1AuthSimpleUnauthorized %s", 401, payload)
}

func (o *PostAPIV1AuthSimpleUnauthorized) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuthSimpleUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuthSimpleInternalServerError creates a PostAPIV1AuthSimpleInternalServerError with default headers values
func NewPostAPIV1AuthSimpleInternalServerError() *PostAPIV1AuthSimpleInternalServerError {
	return &PostAPIV1AuthSimpleInternalServerError{}
}

/*
PostAPIV1AuthSimpleInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера (пустое тело)
*/
type PostAPIV1AuthSimpleInternalServerError struct {
}

// IsSuccess returns true when this post Api v1 auth simple internal server error response has a 2xx status code
func (o *PostAPIV1AuthSimpleInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 auth simple internal server error response has a 3xx status code
func (o *PostAPIV1AuthSimpleInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 auth simple internal server error response has a 4xx status code
func (o *PostAPIV1AuthSimpleInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 auth simple internal server error response has a 5xx status code
func (o *PostAPIV1AuthSimpleInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 auth simple internal server error response a status code equal to that given
func (o *PostAPIV1AuthSimpleInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 auth simple internal server error response
func (o *PostAPIV1AuthSimpleInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1AuthSimpleInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v1/auth/simple][%d] postApiV1AuthSimpleInternalServerError", 500)
}

func (o *PostAPIV1AuthSimpleInternalServerError) String() string {
	return fmt.Sprintf("[POST /api/v1/auth/simple][%d] postApiV1AuthSimpleInternalServerError", 500)
}

func (o *PostAPIV1AuthSimpleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
