// Code generated by go-swagger; DO NOT EDIT.

package auth

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-auth-service/pkg/api/http/auth/v1/models"
)

// NewPostAPIV1AuthSimpleParams creates a new PostAPIV1AuthSimpleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1AuthSimpleParams() *PostAPIV1AuthSimpleParams {
	return &PostAPIV1AuthSimpleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1AuthSimpleParamsWithTimeout creates a new PostAPIV1AuthSimpleParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1AuthSimpleParamsWithTimeout(timeout time.Duration) *PostAPIV1AuthSimpleParams {
	return &PostAPIV1AuthSimpleParams{
		timeout: timeout,
	}
}

// NewPostAPIV1AuthSimpleParamsWithContext creates a new PostAPIV1AuthSimpleParams object
// with the ability to set a context for a request.
func NewPostAPIV1AuthSimpleParamsWithContext(ctx context.Context) *PostAPIV1AuthSimpleParams {
	return &PostAPIV1AuthSimpleParams{
		Context: ctx,
	}
}

// NewPostAPIV1AuthSimpleParamsWithHTTPClient creates a new PostAPIV1AuthSimpleParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1AuthSimpleParamsWithHTTPClient(client *http.Client) *PostAPIV1AuthSimpleParams {
	return &PostAPIV1AuthSimpleParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1AuthSimpleParams contains all the parameters to send to the API endpoint

	for the post API v1 auth simple operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1AuthSimpleParams struct {

	/* Input.

	   login информация
	*/
	Input *models.LoginDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 auth simple params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AuthSimpleParams) WithDefaults() *PostAPIV1AuthSimpleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 auth simple params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AuthSimpleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 auth simple params
func (o *PostAPIV1AuthSimpleParams) WithTimeout(timeout time.Duration) *PostAPIV1AuthSimpleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 auth simple params
func (o *PostAPIV1AuthSimpleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 auth simple params
func (o *PostAPIV1AuthSimpleParams) WithContext(ctx context.Context) *PostAPIV1AuthSimpleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 auth simple params
func (o *PostAPIV1AuthSimpleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 auth simple params
func (o *PostAPIV1AuthSimpleParams) WithHTTPClient(client *http.Client) *PostAPIV1AuthSimpleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 auth simple params
func (o *PostAPIV1AuthSimpleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInput adds the input to the post API v1 auth simple params
func (o *PostAPIV1AuthSimpleParams) WithInput(input *models.LoginDTO) *PostAPIV1AuthSimpleParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the post API v1 auth simple params
func (o *PostAPIV1AuthSimpleParams) SetInput(input *models.LoginDTO) {
	o.Input = input
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1AuthSimpleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
