// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-auth-service/pkg/api/http/auth/v1/models"
)

// NewPostAPIV1AuthParams creates a new PostAPIV1AuthParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1AuthParams() *PostAPIV1AuthParams {
	return &PostAPIV1AuthParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1AuthParamsWithTimeout creates a new PostAPIV1AuthParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1AuthParamsWithTimeout(timeout time.Duration) *PostAPIV1AuthParams {
	return &PostAPIV1AuthParams{
		timeout: timeout,
	}
}

// NewPostAPIV1AuthParamsWithContext creates a new PostAPIV1AuthParams object
// with the ability to set a context for a request.
func NewPostAPIV1AuthParamsWithContext(ctx context.Context) *PostAPIV1AuthParams {
	return &PostAPIV1AuthParams{
		Context: ctx,
	}
}

// NewPostAPIV1AuthParamsWithHTTPClient creates a new PostAPIV1AuthParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1AuthParamsWithHTTPClient(client *http.Client) *PostAPIV1AuthParams {
	return &PostAPIV1AuthParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1AuthParams contains all the parameters to send to the API endpoint

	for the post API v1 auth operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1AuthParams struct {

	/* Input.

	   login информация
	*/
	Input *models.LoginDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 auth params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AuthParams) WithDefaults() *PostAPIV1AuthParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 auth params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AuthParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 auth params
func (o *PostAPIV1AuthParams) WithTimeout(timeout time.Duration) *PostAPIV1AuthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 auth params
func (o *PostAPIV1AuthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 auth params
func (o *PostAPIV1AuthParams) WithContext(ctx context.Context) *PostAPIV1AuthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 auth params
func (o *PostAPIV1AuthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 auth params
func (o *PostAPIV1AuthParams) WithHTTPClient(client *http.Client) *PostAPIV1AuthParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 auth params
func (o *PostAPIV1AuthParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInput adds the input to the post API v1 auth params
func (o *PostAPIV1AuthParams) WithInput(input *models.LoginDTO) *PostAPIV1AuthParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the post API v1 auth params
func (o *PostAPIV1AuthParams) SetInput(input *models.LoginDTO) {
	o.Input = input
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1AuthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
