// Code generated by go-swagger; DO NOT EDIT.

package auth

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-auth-service/pkg/api/http/auth/v1/models"
)

// PostAPIV1AuthReader is a Reader for the PostAPIV1Auth structure.
type PostAPIV1AuthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1AuthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV1AuthOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1AuthBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAPIV1AuthUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1AuthInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/auth] PostAPIV1Auth", response, response.Code())
	}
}

// NewPostAPIV1AuthOK creates a PostAPIV1AuthOK with default headers values
func NewPostAPIV1AuthOK() *PostAPIV1AuthOK {
	return &PostAPIV1AuthOK{}
}

/*
PostAPIV1AuthOK describes a response with status code 200, with default header values.

OK
*/
type PostAPIV1AuthOK struct {
	Payload *models.LoggedInDTO
}

// IsSuccess returns true when this post Api v1 auth o k response has a 2xx status code
func (o *PostAPIV1AuthOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 auth o k response has a 3xx status code
func (o *PostAPIV1AuthOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 auth o k response has a 4xx status code
func (o *PostAPIV1AuthOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 auth o k response has a 5xx status code
func (o *PostAPIV1AuthOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 auth o k response a status code equal to that given
func (o *PostAPIV1AuthOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api v1 auth o k response
func (o *PostAPIV1AuthOK) Code() int {
	return 200
}

func (o *PostAPIV1AuthOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth][%d] postApiV1AuthOK %s", 200, payload)
}

func (o *PostAPIV1AuthOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth][%d] postApiV1AuthOK %s", 200, payload)
}

func (o *PostAPIV1AuthOK) GetPayload() *models.LoggedInDTO {
	return o.Payload
}

func (o *PostAPIV1AuthOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LoggedInDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuthBadRequest creates a PostAPIV1AuthBadRequest with default headers values
func NewPostAPIV1AuthBadRequest() *PostAPIV1AuthBadRequest {
	return &PostAPIV1AuthBadRequest{}
}

/*
PostAPIV1AuthBadRequest describes a response with status code 400, with default header values.

Кривые данные
*/
type PostAPIV1AuthBadRequest struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 auth bad request response has a 2xx status code
func (o *PostAPIV1AuthBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 auth bad request response has a 3xx status code
func (o *PostAPIV1AuthBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 auth bad request response has a 4xx status code
func (o *PostAPIV1AuthBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 auth bad request response has a 5xx status code
func (o *PostAPIV1AuthBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 auth bad request response a status code equal to that given
func (o *PostAPIV1AuthBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 auth bad request response
func (o *PostAPIV1AuthBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1AuthBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth][%d] postApiV1AuthBadRequest %s", 400, payload)
}

func (o *PostAPIV1AuthBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth][%d] postApiV1AuthBadRequest %s", 400, payload)
}

func (o *PostAPIV1AuthBadRequest) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuthBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuthUnauthorized creates a PostAPIV1AuthUnauthorized with default headers values
func NewPostAPIV1AuthUnauthorized() *PostAPIV1AuthUnauthorized {
	return &PostAPIV1AuthUnauthorized{}
}

/*
PostAPIV1AuthUnauthorized describes a response with status code 401, with default header values.

Не авторизован
*/
type PostAPIV1AuthUnauthorized struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this post Api v1 auth unauthorized response has a 2xx status code
func (o *PostAPIV1AuthUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 auth unauthorized response has a 3xx status code
func (o *PostAPIV1AuthUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 auth unauthorized response has a 4xx status code
func (o *PostAPIV1AuthUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 auth unauthorized response has a 5xx status code
func (o *PostAPIV1AuthUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 auth unauthorized response a status code equal to that given
func (o *PostAPIV1AuthUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 auth unauthorized response
func (o *PostAPIV1AuthUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1AuthUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth][%d] postApiV1AuthUnauthorized %s", 401, payload)
}

func (o *PostAPIV1AuthUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/auth][%d] postApiV1AuthUnauthorized %s", 401, payload)
}

func (o *PostAPIV1AuthUnauthorized) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PostAPIV1AuthUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1AuthInternalServerError creates a PostAPIV1AuthInternalServerError with default headers values
func NewPostAPIV1AuthInternalServerError() *PostAPIV1AuthInternalServerError {
	return &PostAPIV1AuthInternalServerError{}
}

/*
PostAPIV1AuthInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера (пустое тело)
*/
type PostAPIV1AuthInternalServerError struct {
}

// IsSuccess returns true when this post Api v1 auth internal server error response has a 2xx status code
func (o *PostAPIV1AuthInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 auth internal server error response has a 3xx status code
func (o *PostAPIV1AuthInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 auth internal server error response has a 4xx status code
func (o *PostAPIV1AuthInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 auth internal server error response has a 5xx status code
func (o *PostAPIV1AuthInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 auth internal server error response a status code equal to that given
func (o *PostAPIV1AuthInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 auth internal server error response
func (o *PostAPIV1AuthInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1AuthInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v1/auth][%d] postApiV1AuthInternalServerError", 500)
}

func (o *PostAPIV1AuthInternalServerError) String() string {
	return fmt.Sprintf("[POST /api/v1/auth][%d] postApiV1AuthInternalServerError", 500)
}

func (o *PostAPIV1AuthInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
