### GET resoruce (find)
GET http://localhost:8080/api/v1/admin/roles/1

### GET resource by name (find by name)
GET http://localhost:8080/api/v1/admin/roles/search?name=guest

### GET resource list (list)
GET http://localhost:8080/api/v1/admin/roles

### POST resource (create)
POST http://localhost:8080/api/v1/admin/roles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0aW55LWF1dGgtc2VydmljZSIsInN1YiI6ImVsZiIsImV4cCI6MTc3NjAxOTI5OCwiaWF0IjoxNzc2MDE4Mzk4LCJqdGkiOiJ0YXMtYjUwYWRkYzItMDljOC00ZWQzLTg1NTgtNTdiNWNiMzQ0MTE3Iiwic3ViamVjdF9pZCI6ImJmOThmZTkyLWU5MzItNGMxYi1iNDU1LTJmNWVhNjY3MWEyOSIsInN1YmplY3RfdHlwZSI6InVzZXIiLCJyb2xlcyI6WyJhdWRpdC1yZWFkZXIiLCJhdWRpdC1hZG1pbiIsImFkbWluIiwidXNlciIsImF1ZGl0LXdyaXRlciJdfQ.aRZDC9VRFx3qP_UQPDwDChqJZXboYvHGq2fudE1RUcQ

{
  "name": "test004",
  "description": "test 001 role"
}

### PUT resource (change)
PUT http://localhost:8080/api/v1/admin/roles/ee6a2882-8a32-479c-8988-963d6f8367c7
Content-Type: application/json

{
  "id": "ee6a2882-8a32-479c-8988-963d6f8367c7",
  "name": "test001 changed",
  "description": "test 001 role changed",
  "deleted": true,
  "created_at": "2026-03-28T18:28:36.363786+03:00"
}

### DELETE resource (delete)
DELETE http://localhost:8080/api/v1/admin/roles/b461e33f-4dd6-4011-abfa-731ac076df76


