### GET resoruce (find)
GET http://localhost:8080/api/v1/admin/roles/1

### GET resource by name (find by name)
GET http://localhost:8080/api/v1/admin/roles/search?name=guest

### GET resource list (list)
GET http://localhost:8080/api/v1/admin/roles

### POST resource (create)
POST http://localhost:8080/api/v1/admin/roles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0aW55LWF1dGgtc2VydmljZSIsInN1YiI6InN2Y19hdXRoIiwiZXhwIjoxNzc2MTAxNjExLCJpYXQiOjE3NzYxMDA3MTEsImp0aSI6InRhcy0yY2EyNGFjMC0xZGE1LTQ5MGQtODkyMi0yNjNiMGYxZGUwMjUiLCJzdWJqZWN0X2lkIjoiNjY0MzViNWMtNThkOC00MDQ2LWFkNDctZmZiNmIxYmZmNDYxIiwic3ViamVjdF90eXBlIjoic2VydmljZSIsInJvbGVzIjpbInVzZXIiLCJhdWRpdC13cml0ZXIiXX0.JERpjh94bmTK29-pXn1nbb_k-k7OO2XBPHb8pgSzoNI

{
  "name": "test006",
  "description": "test 006 role"
}

### PUT resource (change)
PUT http://localhost:8080/api/v1/admin/roles/ee6a2882-8a32-479c-8988-963d6f8367c7
Content-Type: application/json

{
  "id": "ee6a2882-8a32-479c-8988-963d6f8367c7",
  "name": "test001 changed",
  "description": "test 001 role changed",
  "deleted": true,
  "created_at": "2026-03-28T18:28:36.363786+03:00"
}

### DELETE resource (delete)
DELETE http://localhost:8080/api/v1/admin/roles/b461e33f-4dd6-4011-abfa-731ac076df76


