### POST user register
POST http://localhost:8080/api/v1/users/register
Content-Type: application/json

{
  "username": "test",
  "password": "password"
}

### GET user profile
GET http://localhost:8080/api/v1/users/profile
Cookie: Authorization=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0aW55LWFpdGgtc2VydmljZSIsInN1YiI6InRlc3QiLCJleHAiOjE3NzQ4NTk5MDUsImlhdCI6MTc3NDg1OTAwNSwianRpIjoidGFzLTNjMDQ4OTJiLTVkY2EtNDQ3Yi1hMWIzLTdhMzU2ODY1MWNmNSIsInN1YmplY3RfaWQiOiI1OTMzNGY1NS04MzMxLTRmZTItOTY5My1iY2RkZjgxYzc5NWMiLCJzdWJqZWN0X3R5cGUiOiJ1c2VyIiwicm9sZXMiOlsidXNlciJdfQ.bdazqeDwa5a08yGiDisnZZkaLTpsc6KlphZC_BVj7uI



###