### POST user register (not in prod env)
POST http://localhost:8080/api/v1/users/register
Content-Type: application/json

{
  "username": "test",
  "password": "password"
}

### GET user profile (cookie based auth)
GET http://localhost:8080/api/v1/users/profile
Cookie: Authorization=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0aW55LWF1dGgtc2VydmljZSIsInN1YiI6InRlc3QiLCJleHAiOjE3NzU0NzY1OTMsImlhdCI6MTc3NTQ3NTY5MywianRpIjoidGFzLTE3OWRmOTE2LWM0OGUtNGNjYi04NGYzLTRmOTgwMjVmMWZlNCIsInN1YmplY3RfaWQiOiI1OTMzNGY1NS04MzMxLTRmZTItOTY5My1iY2RkZjgxYzc5NWMiLCJzdWJqZWN0X3R5cGUiOiJndWVzdCIsInJvbGVzIjpbImF1ZGl0LXJlYWRlciIsInVzZXIiLCJhdWRpdC13cml0ZXIiXX0.8cR6x6g6rZfaGj6ZNqX4wm980cmtgPeRObliBZ94D6o

### GET user profile (header based auth)
GET http://localhost:8080/api/v1/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0aW55LWFpdGgtc2VydmljZSIsInN1YiI6InRlc3QiLCJleHAiOjE3NzQ4NzAwNDEsImlhdCI6MTc3NDg2OTE0MSwianRpIjoidGFzLTQ2NjRhMDZiLWNiZWUtNGMxYi04NWExLWNkZTVhZDhmN2FlZSIsInN1YmplY3RfaWQiOiI1OTMzNGY1NS04MzMxLTRmZTItOTY5My1iY2RkZjgxYzc5NWMiLCJzdWJqZWN0X3R5cGUiOiJ1c2VyIiwicm9sZXMiOlsidXNlciJdfQ.0o3hG7p7iSlAFEdHltnqEtSm5UPDkrogbmai0l67zu0

### PUT user password change
PUT http://localhost:8080/api/v1/users/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0aW55LWFpdGgtc2VydmljZSIsInN1YiI6InRlc3QiLCJleHAiOjE3NzQ4NzAwNDEsImlhdCI6MTc3NDg2OTE0MSwianRpIjoidGFzLTQ2NjRhMDZiLWNiZWUtNGMxYi04NWExLWNkZTVhZDhmN2FlZSIsInN1YmplY3RfaWQiOiI1OTMzNGY1NS04MzMxLTRmZTItOTY5My1iY2RkZjgxYzc5NWMiLCJzdWJqZWN0X3R5cGUiOiJ1c2VyIiwicm9sZXMiOlsidXNlciJdfQ.0o3hG7p7iSlAFEdHltnqEtSm5UPDkrogbmai0l67zu0

{
  "old_password": "password",
  "new_password": "password2"
}

### PUT user new RSA keys generation
PUT http://localhost:8080/api/v1/users/keys
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0aW55LWFpdGgtc2VydmljZSIsInN1YiI6InRlc3QiLCJleHAiOjE3NzQ4NzAwNDEsImlhdCI6MTc3NDg2OTE0MSwianRpIjoidGFzLTQ2NjRhMDZiLWNiZWUtNGMxYi04NWExLWNkZTVhZDhmN2FlZSIsInN1YmplY3RfaWQiOiI1OTMzNGY1NS04MzMxLTRmZTItOTY5My1iY2RkZjgxYzc5NWMiLCJzdWJqZWN0X3R5cGUiOiJ1c2VyIiwicm9sZXMiOlsidXNlciJdfQ.0o3hG7p7iSlAFEdHltnqEtSm5UPDkrogbmai0l67zu0

###
