// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoginSimpleUseCase creates a new instance of MockLoginSimpleUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginSimpleUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginSimpleUseCase {
	mock := &MockLoginSimpleUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoginSimpleUseCase is an autogenerated mock type for the LoginSimpleUseCase type
type MockLoginSimpleUseCase struct {
	mock.Mock
}

type MockLoginSimpleUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginSimpleUseCase) EXPECT() *MockLoginSimpleUseCase_Expecter {
	return &MockLoginSimpleUseCase_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockLoginSimpleUseCase
func (_mock *MockLoginSimpleUseCase) Login(ctx context.Context, username string, encryptedPassword string) (*jwt.Token, *jwt.Token, error) {
	ret := _mock.Called(ctx, username, encryptedPassword)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *jwt.Token
	var r1 *jwt.Token
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*jwt.Token, *jwt.Token, error)); ok {
		return returnFunc(ctx, username, encryptedPassword)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *jwt.Token); ok {
		r0 = returnFunc(ctx, username, encryptedPassword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *jwt.Token); ok {
		r1 = returnFunc(ctx, username, encryptedPassword)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*jwt.Token)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, username, encryptedPassword)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockLoginSimpleUseCase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockLoginSimpleUseCase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - encryptedPassword string
func (_e *MockLoginSimpleUseCase_Expecter) Login(ctx interface{}, username interface{}, encryptedPassword interface{}) *MockLoginSimpleUseCase_Login_Call {
	return &MockLoginSimpleUseCase_Login_Call{Call: _e.mock.On("Login", ctx, username, encryptedPassword)}
}

func (_c *MockLoginSimpleUseCase_Login_Call) Run(run func(ctx context.Context, username string, encryptedPassword string)) *MockLoginSimpleUseCase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLoginSimpleUseCase_Login_Call) Return(token *jwt.Token, refreshToken *jwt.Token, err error) *MockLoginSimpleUseCase_Login_Call {
	_c.Call.Return(token, refreshToken, err)
	return _c
}

func (_c *MockLoginSimpleUseCase_Login_Call) RunAndReturn(run func(ctx context.Context, username string, encryptedPassword string) (*jwt.Token, *jwt.Token, error)) *MockLoginSimpleUseCase_Login_Call {
	_c.Call.Return(run)
	return _c
}
