// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockChangeKeysUseCase creates a new instance of MockChangeKeysUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChangeKeysUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChangeKeysUseCase {
	mock := &MockChangeKeysUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChangeKeysUseCase is an autogenerated mock type for the ChangeKeysUseCase type
type MockChangeKeysUseCase struct {
	mock.Mock
}

type MockChangeKeysUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChangeKeysUseCase) EXPECT() *MockChangeKeysUseCase_Expecter {
	return &MockChangeKeysUseCase_Expecter{mock: &_m.Mock}
}

// ChangeKeys provides a mock function for the type MockChangeKeysUseCase
func (_mock *MockChangeKeysUseCase) ChangeKeys(ctx context.Context, userID string) (string, string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ChangeKeys")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockChangeKeysUseCase_ChangeKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeKeys'
type MockChangeKeysUseCase_ChangeKeys_Call struct {
	*mock.Call
}

// ChangeKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockChangeKeysUseCase_Expecter) ChangeKeys(ctx interface{}, userID interface{}) *MockChangeKeysUseCase_ChangeKeys_Call {
	return &MockChangeKeysUseCase_ChangeKeys_Call{Call: _e.mock.On("ChangeKeys", ctx, userID)}
}

func (_c *MockChangeKeysUseCase_ChangeKeys_Call) Run(run func(ctx context.Context, userID string)) *MockChangeKeysUseCase_ChangeKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChangeKeysUseCase_ChangeKeys_Call) Return(privateKey string, publicKey string, err error) *MockChangeKeysUseCase_ChangeKeys_Call {
	_c.Call.Return(privateKey, publicKey, err)
	return _c
}

func (_c *MockChangeKeysUseCase_ChangeKeys_Call) RunAndReturn(run func(ctx context.Context, userID string) (string, string, error)) *MockChangeKeysUseCase_ChangeKeys_Call {
	_c.Call.Return(run)
	return _c
}
