// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/tiny-auth-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRegisterUseCase creates a new instance of MockRegisterUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegisterUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegisterUseCase {
	mock := &MockRegisterUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegisterUseCase is an autogenerated mock type for the RegisterUseCase type
type MockRegisterUseCase struct {
	mock.Mock
}

type MockRegisterUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegisterUseCase) EXPECT() *MockRegisterUseCase_Expecter {
	return &MockRegisterUseCase_Expecter{mock: &_m.Mock}
}

// Register provides a mock function for the type MockRegisterUseCase
func (_mock *MockRegisterUseCase) Register(ctx context.Context, username string, password string) (*domain.User, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegisterUseCase_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockRegisterUseCase_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockRegisterUseCase_Expecter) Register(ctx interface{}, username interface{}, password interface{}) *MockRegisterUseCase_Register_Call {
	return &MockRegisterUseCase_Register_Call{Call: _e.mock.On("Register", ctx, username, password)}
}

func (_c *MockRegisterUseCase_Register_Call) Run(run func(ctx context.Context, username string, password string)) *MockRegisterUseCase_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRegisterUseCase_Register_Call) Return(user *domain.User, err error) *MockRegisterUseCase_Register_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRegisterUseCase_Register_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (*domain.User, error)) *MockRegisterUseCase_Register_Call {
	_c.Call.Return(run)
	return _c
}
