// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/tiny-auth-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserAdminSaveUseCase creates a new instance of MockUserAdminSaveUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserAdminSaveUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserAdminSaveUseCase {
	mock := &MockUserAdminSaveUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserAdminSaveUseCase is an autogenerated mock type for the UserAdminSaveUseCase type
type MockUserAdminSaveUseCase struct {
	mock.Mock
}

type MockUserAdminSaveUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserAdminSaveUseCase) EXPECT() *MockUserAdminSaveUseCase_Expecter {
	return &MockUserAdminSaveUseCase_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type MockUserAdminSaveUseCase
func (_mock *MockUserAdminSaveUseCase) Save(ctx context.Context, model *domain.User) (*domain.User, error) {
	ret := _mock.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) (*domain.User, error)); ok {
		return returnFunc(ctx, model)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) *domain.User); ok {
		r0 = returnFunc(ctx, model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.User) error); ok {
		r1 = returnFunc(ctx, model)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAdminSaveUseCase_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockUserAdminSaveUseCase_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - model *domain.User
func (_e *MockUserAdminSaveUseCase_Expecter) Save(ctx interface{}, model interface{}) *MockUserAdminSaveUseCase_Save_Call {
	return &MockUserAdminSaveUseCase_Save_Call{Call: _e.mock.On("Save", ctx, model)}
}

func (_c *MockUserAdminSaveUseCase_Save_Call) Run(run func(ctx context.Context, model *domain.User)) *MockUserAdminSaveUseCase_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserAdminSaveUseCase_Save_Call) Return(user *domain.User, err error) *MockUserAdminSaveUseCase_Save_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserAdminSaveUseCase_Save_Call) RunAndReturn(run func(ctx context.Context, model *domain.User) (*domain.User, error)) *MockUserAdminSaveUseCase_Save_Call {
	_c.Call.Return(run)
	return _c
}
