// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/tiny-auth-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRoleAdminListUseCase creates a new instance of MockRoleAdminListUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleAdminListUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleAdminListUseCase {
	mock := &MockRoleAdminListUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoleAdminListUseCase is an autogenerated mock type for the RoleAdminListUseCase type
type MockRoleAdminListUseCase struct {
	mock.Mock
}

type MockRoleAdminListUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleAdminListUseCase) EXPECT() *MockRoleAdminListUseCase_Expecter {
	return &MockRoleAdminListUseCase_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockRoleAdminListUseCase
func (_mock *MockRoleAdminListUseCase) List(ctx context.Context, limit int, offset int) ([]*domain.Role, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain.Role, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*domain.Role); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleAdminListUseCase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRoleAdminListUseCase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockRoleAdminListUseCase_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *MockRoleAdminListUseCase_List_Call {
	return &MockRoleAdminListUseCase_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockRoleAdminListUseCase_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockRoleAdminListUseCase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRoleAdminListUseCase_List_Call) Return(roles []*domain.Role, err error) *MockRoleAdminListUseCase_List_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *MockRoleAdminListUseCase_List_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*domain.Role, error)) *MockRoleAdminListUseCase_List_Call {
	_c.Call.Return(run)
	return _c
}
