// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/tiny-auth-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRoleAdminGetUseCase creates a new instance of MockRoleAdminGetUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleAdminGetUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleAdminGetUseCase {
	mock := &MockRoleAdminGetUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoleAdminGetUseCase is an autogenerated mock type for the RoleAdminGetUseCase type
type MockRoleAdminGetUseCase struct {
	mock.Mock
}

type MockRoleAdminGetUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleAdminGetUseCase) EXPECT() *MockRoleAdminGetUseCase_Expecter {
	return &MockRoleAdminGetUseCase_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockRoleAdminGetUseCase
func (_mock *MockRoleAdminGetUseCase) Get(ctx context.Context, ID string) (*domain.Role, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Role, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Role); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleAdminGetUseCase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRoleAdminGetUseCase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ID string
func (_e *MockRoleAdminGetUseCase_Expecter) Get(ctx interface{}, ID interface{}) *MockRoleAdminGetUseCase_Get_Call {
	return &MockRoleAdminGetUseCase_Get_Call{Call: _e.mock.On("Get", ctx, ID)}
}

func (_c *MockRoleAdminGetUseCase_Get_Call) Run(run func(ctx context.Context, ID string)) *MockRoleAdminGetUseCase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleAdminGetUseCase_Get_Call) Return(role *domain.Role, err error) *MockRoleAdminGetUseCase_Get_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockRoleAdminGetUseCase_Get_Call) RunAndReturn(run func(ctx context.Context, ID string) (*domain.Role, error)) *MockRoleAdminGetUseCase_Get_Call {
	_c.Call.Return(run)
	return _c
}
