// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRoleAdminDeleteUseCase creates a new instance of MockRoleAdminDeleteUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleAdminDeleteUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleAdminDeleteUseCase {
	mock := &MockRoleAdminDeleteUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoleAdminDeleteUseCase is an autogenerated mock type for the RoleAdminDeleteUseCase type
type MockRoleAdminDeleteUseCase struct {
	mock.Mock
}

type MockRoleAdminDeleteUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleAdminDeleteUseCase) EXPECT() *MockRoleAdminDeleteUseCase_Expecter {
	return &MockRoleAdminDeleteUseCase_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockRoleAdminDeleteUseCase
func (_mock *MockRoleAdminDeleteUseCase) Delete(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoleAdminDeleteUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRoleAdminDeleteUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockRoleAdminDeleteUseCase_Expecter) Delete(context1 interface{}, s interface{}) *MockRoleAdminDeleteUseCase_Delete_Call {
	return &MockRoleAdminDeleteUseCase_Delete_Call{Call: _e.mock.On("Delete", context1, s)}
}

func (_c *MockRoleAdminDeleteUseCase_Delete_Call) Run(run func(context1 context.Context, s string)) *MockRoleAdminDeleteUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleAdminDeleteUseCase_Delete_Call) Return(err error) *MockRoleAdminDeleteUseCase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoleAdminDeleteUseCase_Delete_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockRoleAdminDeleteUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}
