// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/tiny-auth-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProfileUseCase creates a new instance of MockProfileUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileUseCase {
	mock := &MockProfileUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfileUseCase is an autogenerated mock type for the ProfileUseCase type
type MockProfileUseCase struct {
	mock.Mock
}

type MockProfileUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileUseCase) EXPECT() *MockProfileUseCase_Expecter {
	return &MockProfileUseCase_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockProfileUseCase
func (_mock *MockProfileUseCase) Get(ctx context.Context, username string) (*domain.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileUseCase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockProfileUseCase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockProfileUseCase_Expecter) Get(ctx interface{}, username interface{}) *MockProfileUseCase_Get_Call {
	return &MockProfileUseCase_Get_Call{Call: _e.mock.On("Get", ctx, username)}
}

func (_c *MockProfileUseCase_Get_Call) Run(run func(ctx context.Context, username string)) *MockProfileUseCase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileUseCase_Get_Call) Return(user *domain.User, err error) *MockProfileUseCase_Get_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockProfileUseCase_Get_Call) RunAndReturn(run func(ctx context.Context, username string) (*domain.User, error)) *MockProfileUseCase_Get_Call {
	_c.Call.Return(run)
	return _c
}
