// Code generated by go-swagger; DO NOT EDIT.

package user

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-auth-service/pkg/api/http/auth/v1/models"
)

// DeleteAPIV1AdminUsersIDReader is a Reader for the DeleteAPIV1AdminUsersID structure.
type DeleteAPIV1AdminUsersIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIV1AdminUsersIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAPIV1AdminUsersIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewDeleteAPIV1AdminUsersIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAPIV1AdminUsersIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteAPIV1AdminUsersIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api/v1/admin/users/{id}] DeleteAPIV1AdminUsersID", response, response.Code())
	}
}

// NewDeleteAPIV1AdminUsersIDNoContent creates a DeleteAPIV1AdminUsersIDNoContent with default headers values
func NewDeleteAPIV1AdminUsersIDNoContent() *DeleteAPIV1AdminUsersIDNoContent {
	return &DeleteAPIV1AdminUsersIDNoContent{}
}

/*
DeleteAPIV1AdminUsersIDNoContent describes a response with status code 204, with default header values.

Запись успешно удалена, тело ответа отсутствует
*/
type DeleteAPIV1AdminUsersIDNoContent struct {
}

// IsSuccess returns true when this delete Api v1 admin users Id no content response has a 2xx status code
func (o *DeleteAPIV1AdminUsersIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api v1 admin users Id no content response has a 3xx status code
func (o *DeleteAPIV1AdminUsersIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api v1 admin users Id no content response has a 4xx status code
func (o *DeleteAPIV1AdminUsersIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api v1 admin users Id no content response has a 5xx status code
func (o *DeleteAPIV1AdminUsersIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api v1 admin users Id no content response a status code equal to that given
func (o *DeleteAPIV1AdminUsersIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete Api v1 admin users Id no content response
func (o *DeleteAPIV1AdminUsersIDNoContent) Code() int {
	return 204
}

func (o *DeleteAPIV1AdminUsersIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/admin/users/{id}][%d] deleteApiV1AdminUsersIdNoContent", 204)
}

func (o *DeleteAPIV1AdminUsersIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/v1/admin/users/{id}][%d] deleteApiV1AdminUsersIdNoContent", 204)
}

func (o *DeleteAPIV1AdminUsersIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIV1AdminUsersIDForbidden creates a DeleteAPIV1AdminUsersIDForbidden with default headers values
func NewDeleteAPIV1AdminUsersIDForbidden() *DeleteAPIV1AdminUsersIDForbidden {
	return &DeleteAPIV1AdminUsersIDForbidden{}
}

/*
DeleteAPIV1AdminUsersIDForbidden describes a response with status code 403, with default header values.

В доступе отказано
*/
type DeleteAPIV1AdminUsersIDForbidden struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this delete Api v1 admin users Id forbidden response has a 2xx status code
func (o *DeleteAPIV1AdminUsersIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete Api v1 admin users Id forbidden response has a 3xx status code
func (o *DeleteAPIV1AdminUsersIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api v1 admin users Id forbidden response has a 4xx status code
func (o *DeleteAPIV1AdminUsersIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete Api v1 admin users Id forbidden response has a 5xx status code
func (o *DeleteAPIV1AdminUsersIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api v1 admin users Id forbidden response a status code equal to that given
func (o *DeleteAPIV1AdminUsersIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete Api v1 admin users Id forbidden response
func (o *DeleteAPIV1AdminUsersIDForbidden) Code() int {
	return 403
}

func (o *DeleteAPIV1AdminUsersIDForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/admin/users/{id}][%d] deleteApiV1AdminUsersIdForbidden %s", 403, payload)
}

func (o *DeleteAPIV1AdminUsersIDForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/admin/users/{id}][%d] deleteApiV1AdminUsersIdForbidden %s", 403, payload)
}

func (o *DeleteAPIV1AdminUsersIDForbidden) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *DeleteAPIV1AdminUsersIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteAPIV1AdminUsersIDNotFound creates a DeleteAPIV1AdminUsersIDNotFound with default headers values
func NewDeleteAPIV1AdminUsersIDNotFound() *DeleteAPIV1AdminUsersIDNotFound {
	return &DeleteAPIV1AdminUsersIDNotFound{}
}

/*
DeleteAPIV1AdminUsersIDNotFound describes a response with status code 404, with default header values.

Запись не найдена
*/
type DeleteAPIV1AdminUsersIDNotFound struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this delete Api v1 admin users Id not found response has a 2xx status code
func (o *DeleteAPIV1AdminUsersIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete Api v1 admin users Id not found response has a 3xx status code
func (o *DeleteAPIV1AdminUsersIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api v1 admin users Id not found response has a 4xx status code
func (o *DeleteAPIV1AdminUsersIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete Api v1 admin users Id not found response has a 5xx status code
func (o *DeleteAPIV1AdminUsersIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api v1 admin users Id not found response a status code equal to that given
func (o *DeleteAPIV1AdminUsersIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete Api v1 admin users Id not found response
func (o *DeleteAPIV1AdminUsersIDNotFound) Code() int {
	return 404
}

func (o *DeleteAPIV1AdminUsersIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/admin/users/{id}][%d] deleteApiV1AdminUsersIdNotFound %s", 404, payload)
}

func (o *DeleteAPIV1AdminUsersIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/admin/users/{id}][%d] deleteApiV1AdminUsersIdNotFound %s", 404, payload)
}

func (o *DeleteAPIV1AdminUsersIDNotFound) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *DeleteAPIV1AdminUsersIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteAPIV1AdminUsersIDInternalServerError creates a DeleteAPIV1AdminUsersIDInternalServerError with default headers values
func NewDeleteAPIV1AdminUsersIDInternalServerError() *DeleteAPIV1AdminUsersIDInternalServerError {
	return &DeleteAPIV1AdminUsersIDInternalServerError{}
}

/*
DeleteAPIV1AdminUsersIDInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера (пустое тело)
*/
type DeleteAPIV1AdminUsersIDInternalServerError struct {
}

// IsSuccess returns true when this delete Api v1 admin users Id internal server error response has a 2xx status code
func (o *DeleteAPIV1AdminUsersIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete Api v1 admin users Id internal server error response has a 3xx status code
func (o *DeleteAPIV1AdminUsersIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api v1 admin users Id internal server error response has a 4xx status code
func (o *DeleteAPIV1AdminUsersIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api v1 admin users Id internal server error response has a 5xx status code
func (o *DeleteAPIV1AdminUsersIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete Api v1 admin users Id internal server error response a status code equal to that given
func (o *DeleteAPIV1AdminUsersIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete Api v1 admin users Id internal server error response
func (o *DeleteAPIV1AdminUsersIDInternalServerError) Code() int {
	return 500
}

func (o *DeleteAPIV1AdminUsersIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/admin/users/{id}][%d] deleteApiV1AdminUsersIdInternalServerError", 500)
}

func (o *DeleteAPIV1AdminUsersIDInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /api/v1/admin/users/{id}][%d] deleteApiV1AdminUsersIdInternalServerError", 500)
}

func (o *DeleteAPIV1AdminUsersIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
