// Code generated by go-swagger; DO NOT EDIT.

package user

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-auth-service/pkg/api/http/auth/v1/models"
)

// GetAPIV1AdminUsersReader is a Reader for the GetAPIV1AdminUsers structure.
type GetAPIV1AdminUsersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1AdminUsersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1AdminUsersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV1AdminUsersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAPIV1AdminUsersForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1AdminUsersInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/admin/users] GetAPIV1AdminUsers", response, response.Code())
	}
}

// NewGetAPIV1AdminUsersOK creates a GetAPIV1AdminUsersOK with default headers values
func NewGetAPIV1AdminUsersOK() *GetAPIV1AdminUsersOK {
	return &GetAPIV1AdminUsersOK{}
}

/*
GetAPIV1AdminUsersOK describes a response with status code 200, with default header values.

Набор пользователей
*/
type GetAPIV1AdminUsersOK struct {
	Payload []*models.UserDTO
}

// IsSuccess returns true when this get Api v1 admin users o k response has a 2xx status code
func (o *GetAPIV1AdminUsersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 admin users o k response has a 3xx status code
func (o *GetAPIV1AdminUsersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 admin users o k response has a 4xx status code
func (o *GetAPIV1AdminUsersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 admin users o k response has a 5xx status code
func (o *GetAPIV1AdminUsersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 admin users o k response a status code equal to that given
func (o *GetAPIV1AdminUsersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 admin users o k response
func (o *GetAPIV1AdminUsersOK) Code() int {
	return 200
}

func (o *GetAPIV1AdminUsersOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/admin/users][%d] getApiV1AdminUsersOK %s", 200, payload)
}

func (o *GetAPIV1AdminUsersOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/admin/users][%d] getApiV1AdminUsersOK %s", 200, payload)
}

func (o *GetAPIV1AdminUsersOK) GetPayload() []*models.UserDTO {
	return o.Payload
}

func (o *GetAPIV1AdminUsersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1AdminUsersBadRequest creates a GetAPIV1AdminUsersBadRequest with default headers values
func NewGetAPIV1AdminUsersBadRequest() *GetAPIV1AdminUsersBadRequest {
	return &GetAPIV1AdminUsersBadRequest{}
}

/*
GetAPIV1AdminUsersBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAPIV1AdminUsersBadRequest struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this get Api v1 admin users bad request response has a 2xx status code
func (o *GetAPIV1AdminUsersBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 admin users bad request response has a 3xx status code
func (o *GetAPIV1AdminUsersBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 admin users bad request response has a 4xx status code
func (o *GetAPIV1AdminUsersBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 admin users bad request response has a 5xx status code
func (o *GetAPIV1AdminUsersBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 admin users bad request response a status code equal to that given
func (o *GetAPIV1AdminUsersBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api v1 admin users bad request response
func (o *GetAPIV1AdminUsersBadRequest) Code() int {
	return 400
}

func (o *GetAPIV1AdminUsersBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/admin/users][%d] getApiV1AdminUsersBadRequest %s", 400, payload)
}

func (o *GetAPIV1AdminUsersBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/admin/users][%d] getApiV1AdminUsersBadRequest %s", 400, payload)
}

func (o *GetAPIV1AdminUsersBadRequest) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *GetAPIV1AdminUsersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1AdminUsersForbidden creates a GetAPIV1AdminUsersForbidden with default headers values
func NewGetAPIV1AdminUsersForbidden() *GetAPIV1AdminUsersForbidden {
	return &GetAPIV1AdminUsersForbidden{}
}

/*
GetAPIV1AdminUsersForbidden describes a response with status code 403, with default header values.

В доступе отказано
*/
type GetAPIV1AdminUsersForbidden struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this get Api v1 admin users forbidden response has a 2xx status code
func (o *GetAPIV1AdminUsersForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 admin users forbidden response has a 3xx status code
func (o *GetAPIV1AdminUsersForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 admin users forbidden response has a 4xx status code
func (o *GetAPIV1AdminUsersForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 admin users forbidden response has a 5xx status code
func (o *GetAPIV1AdminUsersForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 admin users forbidden response a status code equal to that given
func (o *GetAPIV1AdminUsersForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get Api v1 admin users forbidden response
func (o *GetAPIV1AdminUsersForbidden) Code() int {
	return 403
}

func (o *GetAPIV1AdminUsersForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/admin/users][%d] getApiV1AdminUsersForbidden %s", 403, payload)
}

func (o *GetAPIV1AdminUsersForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/admin/users][%d] getApiV1AdminUsersForbidden %s", 403, payload)
}

func (o *GetAPIV1AdminUsersForbidden) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *GetAPIV1AdminUsersForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1AdminUsersInternalServerError creates a GetAPIV1AdminUsersInternalServerError with default headers values
func NewGetAPIV1AdminUsersInternalServerError() *GetAPIV1AdminUsersInternalServerError {
	return &GetAPIV1AdminUsersInternalServerError{}
}

/*
GetAPIV1AdminUsersInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера (пустое тело)
*/
type GetAPIV1AdminUsersInternalServerError struct {
}

// IsSuccess returns true when this get Api v1 admin users internal server error response has a 2xx status code
func (o *GetAPIV1AdminUsersInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 admin users internal server error response has a 3xx status code
func (o *GetAPIV1AdminUsersInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 admin users internal server error response has a 4xx status code
func (o *GetAPIV1AdminUsersInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 admin users internal server error response has a 5xx status code
func (o *GetAPIV1AdminUsersInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 admin users internal server error response a status code equal to that given
func (o *GetAPIV1AdminUsersInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 admin users internal server error response
func (o *GetAPIV1AdminUsersInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1AdminUsersInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/admin/users][%d] getApiV1AdminUsersInternalServerError", 500)
}

func (o *GetAPIV1AdminUsersInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v1/admin/users][%d] getApiV1AdminUsersInternalServerError", 500)
}

func (o *GetAPIV1AdminUsersInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
