// Code generated by go-swagger; DO NOT EDIT.

package user

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIV1AdminUsersParams creates a new GetAPIV1AdminUsersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1AdminUsersParams() *GetAPIV1AdminUsersParams {
	return &GetAPIV1AdminUsersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1AdminUsersParamsWithTimeout creates a new GetAPIV1AdminUsersParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1AdminUsersParamsWithTimeout(timeout time.Duration) *GetAPIV1AdminUsersParams {
	return &GetAPIV1AdminUsersParams{
		timeout: timeout,
	}
}

// NewGetAPIV1AdminUsersParamsWithContext creates a new GetAPIV1AdminUsersParams object
// with the ability to set a context for a request.
func NewGetAPIV1AdminUsersParamsWithContext(ctx context.Context) *GetAPIV1AdminUsersParams {
	return &GetAPIV1AdminUsersParams{
		Context: ctx,
	}
}

// NewGetAPIV1AdminUsersParamsWithHTTPClient creates a new GetAPIV1AdminUsersParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1AdminUsersParamsWithHTTPClient(client *http.Client) *GetAPIV1AdminUsersParams {
	return &GetAPIV1AdminUsersParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1AdminUsersParams contains all the parameters to send to the API endpoint

	for the get API v1 admin users operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1AdminUsersParams struct {

	/* Limit.

	   limit row count, max 1000

	   Format: int
	*/
	Limit *int64

	/* Offset.

	   offset, min 0, max n

	   Format: int
	*/
	Offset *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 admin users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1AdminUsersParams) WithDefaults() *GetAPIV1AdminUsersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 admin users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1AdminUsersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v1 admin users params
func (o *GetAPIV1AdminUsersParams) WithTimeout(timeout time.Duration) *GetAPIV1AdminUsersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 admin users params
func (o *GetAPIV1AdminUsersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 admin users params
func (o *GetAPIV1AdminUsersParams) WithContext(ctx context.Context) *GetAPIV1AdminUsersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 admin users params
func (o *GetAPIV1AdminUsersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 admin users params
func (o *GetAPIV1AdminUsersParams) WithHTTPClient(client *http.Client) *GetAPIV1AdminUsersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 admin users params
func (o *GetAPIV1AdminUsersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get API v1 admin users params
func (o *GetAPIV1AdminUsersParams) WithLimit(limit *int64) *GetAPIV1AdminUsersParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get API v1 admin users params
func (o *GetAPIV1AdminUsersParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get API v1 admin users params
func (o *GetAPIV1AdminUsersParams) WithOffset(offset *int64) *GetAPIV1AdminUsersParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get API v1 admin users params
func (o *GetAPIV1AdminUsersParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1AdminUsersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
