// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1AdminUsersSearchParams creates a new GetAPIV1AdminUsersSearchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1AdminUsersSearchParams() *GetAPIV1AdminUsersSearchParams {
	return &GetAPIV1AdminUsersSearchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1AdminUsersSearchParamsWithTimeout creates a new GetAPIV1AdminUsersSearchParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1AdminUsersSearchParamsWithTimeout(timeout time.Duration) *GetAPIV1AdminUsersSearchParams {
	return &GetAPIV1AdminUsersSearchParams{
		timeout: timeout,
	}
}

// NewGetAPIV1AdminUsersSearchParamsWithContext creates a new GetAPIV1AdminUsersSearchParams object
// with the ability to set a context for a request.
func NewGetAPIV1AdminUsersSearchParamsWithContext(ctx context.Context) *GetAPIV1AdminUsersSearchParams {
	return &GetAPIV1AdminUsersSearchParams{
		Context: ctx,
	}
}

// NewGetAPIV1AdminUsersSearchParamsWithHTTPClient creates a new GetAPIV1AdminUsersSearchParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1AdminUsersSearchParamsWithHTTPClient(client *http.Client) *GetAPIV1AdminUsersSearchParams {
	return &GetAPIV1AdminUsersSearchParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1AdminUsersSearchParams contains all the parameters to send to the API endpoint

	for the get API v1 admin users search operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1AdminUsersSearchParams struct {

	/* Name.

	   name записи

	   Format: string
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 admin users search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1AdminUsersSearchParams) WithDefaults() *GetAPIV1AdminUsersSearchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 admin users search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1AdminUsersSearchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v1 admin users search params
func (o *GetAPIV1AdminUsersSearchParams) WithTimeout(timeout time.Duration) *GetAPIV1AdminUsersSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 admin users search params
func (o *GetAPIV1AdminUsersSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 admin users search params
func (o *GetAPIV1AdminUsersSearchParams) WithContext(ctx context.Context) *GetAPIV1AdminUsersSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 admin users search params
func (o *GetAPIV1AdminUsersSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 admin users search params
func (o *GetAPIV1AdminUsersSearchParams) WithHTTPClient(client *http.Client) *GetAPIV1AdminUsersSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 admin users search params
func (o *GetAPIV1AdminUsersSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get API v1 admin users search params
func (o *GetAPIV1AdminUsersSearchParams) WithName(name string) *GetAPIV1AdminUsersSearchParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get API v1 admin users search params
func (o *GetAPIV1AdminUsersSearchParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1AdminUsersSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param name
	qrName := o.Name
	qName := qrName
	if qName != "" {

		if err := r.SetQueryParam("name", qName); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
