// Code generated by go-swagger; DO NOT EDIT.

package user

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-auth-service/pkg/api/http/auth/v1/models"
)

// GetAPIV1AdminUsersSearchReader is a Reader for the GetAPIV1AdminUsersSearch structure.
type GetAPIV1AdminUsersSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1AdminUsersSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1AdminUsersSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetAPIV1AdminUsersSearchForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV1AdminUsersSearchNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1AdminUsersSearchInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/admin/users/search] GetAPIV1AdminUsersSearch", response, response.Code())
	}
}

// NewGetAPIV1AdminUsersSearchOK creates a GetAPIV1AdminUsersSearchOK with default headers values
func NewGetAPIV1AdminUsersSearchOK() *GetAPIV1AdminUsersSearchOK {
	return &GetAPIV1AdminUsersSearchOK{}
}

/*
GetAPIV1AdminUsersSearchOK describes a response with status code 200, with default header values.

Пользователь
*/
type GetAPIV1AdminUsersSearchOK struct {
	Payload *models.UserDTO
}

// IsSuccess returns true when this get Api v1 admin users search o k response has a 2xx status code
func (o *GetAPIV1AdminUsersSearchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 admin users search o k response has a 3xx status code
func (o *GetAPIV1AdminUsersSearchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 admin users search o k response has a 4xx status code
func (o *GetAPIV1AdminUsersSearchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 admin users search o k response has a 5xx status code
func (o *GetAPIV1AdminUsersSearchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 admin users search o k response a status code equal to that given
func (o *GetAPIV1AdminUsersSearchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 admin users search o k response
func (o *GetAPIV1AdminUsersSearchOK) Code() int {
	return 200
}

func (o *GetAPIV1AdminUsersSearchOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/admin/users/search][%d] getApiV1AdminUsersSearchOK %s", 200, payload)
}

func (o *GetAPIV1AdminUsersSearchOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/admin/users/search][%d] getApiV1AdminUsersSearchOK %s", 200, payload)
}

func (o *GetAPIV1AdminUsersSearchOK) GetPayload() *models.UserDTO {
	return o.Payload
}

func (o *GetAPIV1AdminUsersSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1AdminUsersSearchForbidden creates a GetAPIV1AdminUsersSearchForbidden with default headers values
func NewGetAPIV1AdminUsersSearchForbidden() *GetAPIV1AdminUsersSearchForbidden {
	return &GetAPIV1AdminUsersSearchForbidden{}
}

/*
GetAPIV1AdminUsersSearchForbidden describes a response with status code 403, with default header values.

В доступе отказано
*/
type GetAPIV1AdminUsersSearchForbidden struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this get Api v1 admin users search forbidden response has a 2xx status code
func (o *GetAPIV1AdminUsersSearchForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 admin users search forbidden response has a 3xx status code
func (o *GetAPIV1AdminUsersSearchForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 admin users search forbidden response has a 4xx status code
func (o *GetAPIV1AdminUsersSearchForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 admin users search forbidden response has a 5xx status code
func (o *GetAPIV1AdminUsersSearchForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 admin users search forbidden response a status code equal to that given
func (o *GetAPIV1AdminUsersSearchForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get Api v1 admin users search forbidden response
func (o *GetAPIV1AdminUsersSearchForbidden) Code() int {
	return 403
}

func (o *GetAPIV1AdminUsersSearchForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/admin/users/search][%d] getApiV1AdminUsersSearchForbidden %s", 403, payload)
}

func (o *GetAPIV1AdminUsersSearchForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/admin/users/search][%d] getApiV1AdminUsersSearchForbidden %s", 403, payload)
}

func (o *GetAPIV1AdminUsersSearchForbidden) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *GetAPIV1AdminUsersSearchForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1AdminUsersSearchNotFound creates a GetAPIV1AdminUsersSearchNotFound with default headers values
func NewGetAPIV1AdminUsersSearchNotFound() *GetAPIV1AdminUsersSearchNotFound {
	return &GetAPIV1AdminUsersSearchNotFound{}
}

/*
GetAPIV1AdminUsersSearchNotFound describes a response with status code 404, with default header values.

Запись не найдена
*/
type GetAPIV1AdminUsersSearchNotFound struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this get Api v1 admin users search not found response has a 2xx status code
func (o *GetAPIV1AdminUsersSearchNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 admin users search not found response has a 3xx status code
func (o *GetAPIV1AdminUsersSearchNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 admin users search not found response has a 4xx status code
func (o *GetAPIV1AdminUsersSearchNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 admin users search not found response has a 5xx status code
func (o *GetAPIV1AdminUsersSearchNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 admin users search not found response a status code equal to that given
func (o *GetAPIV1AdminUsersSearchNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api v1 admin users search not found response
func (o *GetAPIV1AdminUsersSearchNotFound) Code() int {
	return 404
}

func (o *GetAPIV1AdminUsersSearchNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/admin/users/search][%d] getApiV1AdminUsersSearchNotFound %s", 404, payload)
}

func (o *GetAPIV1AdminUsersSearchNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/admin/users/search][%d] getApiV1AdminUsersSearchNotFound %s", 404, payload)
}

func (o *GetAPIV1AdminUsersSearchNotFound) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *GetAPIV1AdminUsersSearchNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1AdminUsersSearchInternalServerError creates a GetAPIV1AdminUsersSearchInternalServerError with default headers values
func NewGetAPIV1AdminUsersSearchInternalServerError() *GetAPIV1AdminUsersSearchInternalServerError {
	return &GetAPIV1AdminUsersSearchInternalServerError{}
}

/*
GetAPIV1AdminUsersSearchInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера (пустое тело)
*/
type GetAPIV1AdminUsersSearchInternalServerError struct {
}

// IsSuccess returns true when this get Api v1 admin users search internal server error response has a 2xx status code
func (o *GetAPIV1AdminUsersSearchInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 admin users search internal server error response has a 3xx status code
func (o *GetAPIV1AdminUsersSearchInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 admin users search internal server error response has a 4xx status code
func (o *GetAPIV1AdminUsersSearchInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 admin users search internal server error response has a 5xx status code
func (o *GetAPIV1AdminUsersSearchInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 admin users search internal server error response a status code equal to that given
func (o *GetAPIV1AdminUsersSearchInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 admin users search internal server error response
func (o *GetAPIV1AdminUsersSearchInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1AdminUsersSearchInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/admin/users/search][%d] getApiV1AdminUsersSearchInternalServerError", 500)
}

func (o *GetAPIV1AdminUsersSearchInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v1/admin/users/search][%d] getApiV1AdminUsersSearchInternalServerError", 500)
}

func (o *GetAPIV1AdminUsersSearchInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
