// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-auth-service/pkg/api/http/auth/v1/models"
)

// NewPostAPIV1AdminUsersParams creates a new PostAPIV1AdminUsersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1AdminUsersParams() *PostAPIV1AdminUsersParams {
	return &PostAPIV1AdminUsersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1AdminUsersParamsWithTimeout creates a new PostAPIV1AdminUsersParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1AdminUsersParamsWithTimeout(timeout time.Duration) *PostAPIV1AdminUsersParams {
	return &PostAPIV1AdminUsersParams{
		timeout: timeout,
	}
}

// NewPostAPIV1AdminUsersParamsWithContext creates a new PostAPIV1AdminUsersParams object
// with the ability to set a context for a request.
func NewPostAPIV1AdminUsersParamsWithContext(ctx context.Context) *PostAPIV1AdminUsersParams {
	return &PostAPIV1AdminUsersParams{
		Context: ctx,
	}
}

// NewPostAPIV1AdminUsersParamsWithHTTPClient creates a new PostAPIV1AdminUsersParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1AdminUsersParamsWithHTTPClient(client *http.Client) *PostAPIV1AdminUsersParams {
	return &PostAPIV1AdminUsersParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1AdminUsersParams contains all the parameters to send to the API endpoint

	for the post API v1 admin users operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1AdminUsersParams struct {

	/* Input.

	   Пользователь
	*/
	Input *models.UserDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 admin users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AdminUsersParams) WithDefaults() *PostAPIV1AdminUsersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 admin users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1AdminUsersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 admin users params
func (o *PostAPIV1AdminUsersParams) WithTimeout(timeout time.Duration) *PostAPIV1AdminUsersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 admin users params
func (o *PostAPIV1AdminUsersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 admin users params
func (o *PostAPIV1AdminUsersParams) WithContext(ctx context.Context) *PostAPIV1AdminUsersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 admin users params
func (o *PostAPIV1AdminUsersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 admin users params
func (o *PostAPIV1AdminUsersParams) WithHTTPClient(client *http.Client) *PostAPIV1AdminUsersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 admin users params
func (o *PostAPIV1AdminUsersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInput adds the input to the post API v1 admin users params
func (o *PostAPIV1AdminUsersParams) WithInput(input *models.UserDTO) *PostAPIV1AdminUsersParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the post API v1 admin users params
func (o *PostAPIV1AdminUsersParams) SetInput(input *models.UserDTO) {
	o.Input = input
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1AdminUsersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
