// Code generated by go-swagger; DO NOT EDIT.

package user

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-auth-service/pkg/api/http/auth/v1/models"
)

// PutAPIV1AdminUsersIDReader is a Reader for the PutAPIV1AdminUsersID structure.
type PutAPIV1AdminUsersIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIV1AdminUsersIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPutAPIV1AdminUsersIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutAPIV1AdminUsersIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutAPIV1AdminUsersIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPutAPIV1AdminUsersIDConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutAPIV1AdminUsersIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /api/v1/admin/users/{id}] PutAPIV1AdminUsersID", response, response.Code())
	}
}

// NewPutAPIV1AdminUsersIDOK creates a PutAPIV1AdminUsersIDOK with default headers values
func NewPutAPIV1AdminUsersIDOK() *PutAPIV1AdminUsersIDOK {
	return &PutAPIV1AdminUsersIDOK{}
}

/*
PutAPIV1AdminUsersIDOK describes a response with status code 200, with default header values.

OK
*/
type PutAPIV1AdminUsersIDOK struct {
	Payload *models.UserDTO
}

// IsSuccess returns true when this put Api v1 admin users Id o k response has a 2xx status code
func (o *PutAPIV1AdminUsersIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put Api v1 admin users Id o k response has a 3xx status code
func (o *PutAPIV1AdminUsersIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api v1 admin users Id o k response has a 4xx status code
func (o *PutAPIV1AdminUsersIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put Api v1 admin users Id o k response has a 5xx status code
func (o *PutAPIV1AdminUsersIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api v1 admin users Id o k response a status code equal to that given
func (o *PutAPIV1AdminUsersIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put Api v1 admin users Id o k response
func (o *PutAPIV1AdminUsersIDOK) Code() int {
	return 200
}

func (o *PutAPIV1AdminUsersIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/admin/users/{id}][%d] putApiV1AdminUsersIdOK %s", 200, payload)
}

func (o *PutAPIV1AdminUsersIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/admin/users/{id}][%d] putApiV1AdminUsersIdOK %s", 200, payload)
}

func (o *PutAPIV1AdminUsersIDOK) GetPayload() *models.UserDTO {
	return o.Payload
}

func (o *PutAPIV1AdminUsersIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutAPIV1AdminUsersIDBadRequest creates a PutAPIV1AdminUsersIDBadRequest with default headers values
func NewPutAPIV1AdminUsersIDBadRequest() *PutAPIV1AdminUsersIDBadRequest {
	return &PutAPIV1AdminUsersIDBadRequest{}
}

/*
PutAPIV1AdminUsersIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PutAPIV1AdminUsersIDBadRequest struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this put Api v1 admin users Id bad request response has a 2xx status code
func (o *PutAPIV1AdminUsersIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put Api v1 admin users Id bad request response has a 3xx status code
func (o *PutAPIV1AdminUsersIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api v1 admin users Id bad request response has a 4xx status code
func (o *PutAPIV1AdminUsersIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this put Api v1 admin users Id bad request response has a 5xx status code
func (o *PutAPIV1AdminUsersIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api v1 admin users Id bad request response a status code equal to that given
func (o *PutAPIV1AdminUsersIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the put Api v1 admin users Id bad request response
func (o *PutAPIV1AdminUsersIDBadRequest) Code() int {
	return 400
}

func (o *PutAPIV1AdminUsersIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/admin/users/{id}][%d] putApiV1AdminUsersIdBadRequest %s", 400, payload)
}

func (o *PutAPIV1AdminUsersIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/admin/users/{id}][%d] putApiV1AdminUsersIdBadRequest %s", 400, payload)
}

func (o *PutAPIV1AdminUsersIDBadRequest) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PutAPIV1AdminUsersIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutAPIV1AdminUsersIDNotFound creates a PutAPIV1AdminUsersIDNotFound with default headers values
func NewPutAPIV1AdminUsersIDNotFound() *PutAPIV1AdminUsersIDNotFound {
	return &PutAPIV1AdminUsersIDNotFound{}
}

/*
PutAPIV1AdminUsersIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PutAPIV1AdminUsersIDNotFound struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this put Api v1 admin users Id not found response has a 2xx status code
func (o *PutAPIV1AdminUsersIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put Api v1 admin users Id not found response has a 3xx status code
func (o *PutAPIV1AdminUsersIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api v1 admin users Id not found response has a 4xx status code
func (o *PutAPIV1AdminUsersIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this put Api v1 admin users Id not found response has a 5xx status code
func (o *PutAPIV1AdminUsersIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api v1 admin users Id not found response a status code equal to that given
func (o *PutAPIV1AdminUsersIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the put Api v1 admin users Id not found response
func (o *PutAPIV1AdminUsersIDNotFound) Code() int {
	return 404
}

func (o *PutAPIV1AdminUsersIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/admin/users/{id}][%d] putApiV1AdminUsersIdNotFound %s", 404, payload)
}

func (o *PutAPIV1AdminUsersIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/admin/users/{id}][%d] putApiV1AdminUsersIdNotFound %s", 404, payload)
}

func (o *PutAPIV1AdminUsersIDNotFound) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PutAPIV1AdminUsersIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutAPIV1AdminUsersIDConflict creates a PutAPIV1AdminUsersIDConflict with default headers values
func NewPutAPIV1AdminUsersIDConflict() *PutAPIV1AdminUsersIDConflict {
	return &PutAPIV1AdminUsersIDConflict{}
}

/*
PutAPIV1AdminUsersIDConflict describes a response with status code 409, with default header values.

Conflict
*/
type PutAPIV1AdminUsersIDConflict struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this put Api v1 admin users Id conflict response has a 2xx status code
func (o *PutAPIV1AdminUsersIDConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put Api v1 admin users Id conflict response has a 3xx status code
func (o *PutAPIV1AdminUsersIDConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api v1 admin users Id conflict response has a 4xx status code
func (o *PutAPIV1AdminUsersIDConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this put Api v1 admin users Id conflict response has a 5xx status code
func (o *PutAPIV1AdminUsersIDConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api v1 admin users Id conflict response a status code equal to that given
func (o *PutAPIV1AdminUsersIDConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the put Api v1 admin users Id conflict response
func (o *PutAPIV1AdminUsersIDConflict) Code() int {
	return 409
}

func (o *PutAPIV1AdminUsersIDConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/admin/users/{id}][%d] putApiV1AdminUsersIdConflict %s", 409, payload)
}

func (o *PutAPIV1AdminUsersIDConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/admin/users/{id}][%d] putApiV1AdminUsersIdConflict %s", 409, payload)
}

func (o *PutAPIV1AdminUsersIDConflict) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PutAPIV1AdminUsersIDConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutAPIV1AdminUsersIDInternalServerError creates a PutAPIV1AdminUsersIDInternalServerError with default headers values
func NewPutAPIV1AdminUsersIDInternalServerError() *PutAPIV1AdminUsersIDInternalServerError {
	return &PutAPIV1AdminUsersIDInternalServerError{}
}

/*
PutAPIV1AdminUsersIDInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера (пустое тело)
*/
type PutAPIV1AdminUsersIDInternalServerError struct {
}

// IsSuccess returns true when this put Api v1 admin users Id internal server error response has a 2xx status code
func (o *PutAPIV1AdminUsersIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put Api v1 admin users Id internal server error response has a 3xx status code
func (o *PutAPIV1AdminUsersIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api v1 admin users Id internal server error response has a 4xx status code
func (o *PutAPIV1AdminUsersIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this put Api v1 admin users Id internal server error response has a 5xx status code
func (o *PutAPIV1AdminUsersIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this put Api v1 admin users Id internal server error response a status code equal to that given
func (o *PutAPIV1AdminUsersIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the put Api v1 admin users Id internal server error response
func (o *PutAPIV1AdminUsersIDInternalServerError) Code() int {
	return 500
}

func (o *PutAPIV1AdminUsersIDInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /api/v1/admin/users/{id}][%d] putApiV1AdminUsersIdInternalServerError", 500)
}

func (o *PutAPIV1AdminUsersIDInternalServerError) String() string {
	return fmt.Sprintf("[PUT /api/v1/admin/users/{id}][%d] putApiV1AdminUsersIdInternalServerError", 500)
}

func (o *PutAPIV1AdminUsersIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
