// Code generated by go-swagger; DO NOT EDIT.

package user

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-auth-service/pkg/api/http/auth/v1/models"
)

// NewPutAPIV1AdminUsersIDParams creates a new PutAPIV1AdminUsersIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPIV1AdminUsersIDParams() *PutAPIV1AdminUsersIDParams {
	return &PutAPIV1AdminUsersIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIV1AdminUsersIDParamsWithTimeout creates a new PutAPIV1AdminUsersIDParams object
// with the ability to set a timeout on a request.
func NewPutAPIV1AdminUsersIDParamsWithTimeout(timeout time.Duration) *PutAPIV1AdminUsersIDParams {
	return &PutAPIV1AdminUsersIDParams{
		timeout: timeout,
	}
}

// NewPutAPIV1AdminUsersIDParamsWithContext creates a new PutAPIV1AdminUsersIDParams object
// with the ability to set a context for a request.
func NewPutAPIV1AdminUsersIDParamsWithContext(ctx context.Context) *PutAPIV1AdminUsersIDParams {
	return &PutAPIV1AdminUsersIDParams{
		Context: ctx,
	}
}

// NewPutAPIV1AdminUsersIDParamsWithHTTPClient creates a new PutAPIV1AdminUsersIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPIV1AdminUsersIDParamsWithHTTPClient(client *http.Client) *PutAPIV1AdminUsersIDParams {
	return &PutAPIV1AdminUsersIDParams{
		HTTPClient: client,
	}
}

/*
PutAPIV1AdminUsersIDParams contains all the parameters to send to the API endpoint

	for the put API v1 admin users ID operation.

	Typically these are written to a http.Request.
*/
type PutAPIV1AdminUsersIDParams struct {

	/* ID.

	   ID записи

	   Format: string
	*/
	ID string

	/* Input.

	   Роль
	*/
	Input *models.UserDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put API v1 admin users ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIV1AdminUsersIDParams) WithDefaults() *PutAPIV1AdminUsersIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put API v1 admin users ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIV1AdminUsersIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put API v1 admin users ID params
func (o *PutAPIV1AdminUsersIDParams) WithTimeout(timeout time.Duration) *PutAPIV1AdminUsersIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API v1 admin users ID params
func (o *PutAPIV1AdminUsersIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API v1 admin users ID params
func (o *PutAPIV1AdminUsersIDParams) WithContext(ctx context.Context) *PutAPIV1AdminUsersIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API v1 admin users ID params
func (o *PutAPIV1AdminUsersIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API v1 admin users ID params
func (o *PutAPIV1AdminUsersIDParams) WithHTTPClient(client *http.Client) *PutAPIV1AdminUsersIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API v1 admin users ID params
func (o *PutAPIV1AdminUsersIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put API v1 admin users ID params
func (o *PutAPIV1AdminUsersIDParams) WithID(id string) *PutAPIV1AdminUsersIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put API v1 admin users ID params
func (o *PutAPIV1AdminUsersIDParams) SetID(id string) {
	o.ID = id
}

// WithInput adds the input to the put API v1 admin users ID params
func (o *PutAPIV1AdminUsersIDParams) WithInput(input *models.UserDTO) *PutAPIV1AdminUsersIDParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the put API v1 admin users ID params
func (o *PutAPIV1AdminUsersIDParams) SetInput(input *models.UserDTO) {
	o.Input = input
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIV1AdminUsersIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
