// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/tiny-auth-service/internal/facade/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRoleAdminFacade creates a new instance of MockRoleAdminFacade. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleAdminFacade(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleAdminFacade {
	mock := &MockRoleAdminFacade{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoleAdminFacade is an autogenerated mock type for the RoleAdminFacade type
type MockRoleAdminFacade struct {
	mock.Mock
}

type MockRoleAdminFacade_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleAdminFacade) EXPECT() *MockRoleAdminFacade_Expecter {
	return &MockRoleAdminFacade_Expecter{mock: &_m.Mock}
}

// Change provides a mock function for the type MockRoleAdminFacade
func (_mock *MockRoleAdminFacade) Change(ctx context.Context, ID string, role *dto.RoleDTO) (*dto.RoleDTO, error) {
	ret := _mock.Called(ctx, ID, role)

	if len(ret) == 0 {
		panic("no return value specified for Change")
	}

	var r0 *dto.RoleDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *dto.RoleDTO) (*dto.RoleDTO, error)); ok {
		return returnFunc(ctx, ID, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *dto.RoleDTO) *dto.RoleDTO); ok {
		r0 = returnFunc(ctx, ID, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RoleDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *dto.RoleDTO) error); ok {
		r1 = returnFunc(ctx, ID, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleAdminFacade_Change_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Change'
type MockRoleAdminFacade_Change_Call struct {
	*mock.Call
}

// Change is a helper method to define mock.On call
//   - ctx context.Context
//   - ID string
//   - role *dto.RoleDTO
func (_e *MockRoleAdminFacade_Expecter) Change(ctx interface{}, ID interface{}, role interface{}) *MockRoleAdminFacade_Change_Call {
	return &MockRoleAdminFacade_Change_Call{Call: _e.mock.On("Change", ctx, ID, role)}
}

func (_c *MockRoleAdminFacade_Change_Call) Run(run func(ctx context.Context, ID string, role *dto.RoleDTO)) *MockRoleAdminFacade_Change_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *dto.RoleDTO
		if args[2] != nil {
			arg2 = args[2].(*dto.RoleDTO)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRoleAdminFacade_Change_Call) Return(roleDTO *dto.RoleDTO, err error) *MockRoleAdminFacade_Change_Call {
	_c.Call.Return(roleDTO, err)
	return _c
}

func (_c *MockRoleAdminFacade_Change_Call) RunAndReturn(run func(ctx context.Context, ID string, role *dto.RoleDTO) (*dto.RoleDTO, error)) *MockRoleAdminFacade_Change_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRoleAdminFacade
func (_mock *MockRoleAdminFacade) Create(ctx context.Context, role *dto.RoleDTO) (*dto.RoleDTO, error) {
	ret := _mock.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.RoleDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.RoleDTO) (*dto.RoleDTO, error)); ok {
		return returnFunc(ctx, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.RoleDTO) *dto.RoleDTO); ok {
		r0 = returnFunc(ctx, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RoleDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.RoleDTO) error); ok {
		r1 = returnFunc(ctx, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleAdminFacade_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoleAdminFacade_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - role *dto.RoleDTO
func (_e *MockRoleAdminFacade_Expecter) Create(ctx interface{}, role interface{}) *MockRoleAdminFacade_Create_Call {
	return &MockRoleAdminFacade_Create_Call{Call: _e.mock.On("Create", ctx, role)}
}

func (_c *MockRoleAdminFacade_Create_Call) Run(run func(ctx context.Context, role *dto.RoleDTO)) *MockRoleAdminFacade_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.RoleDTO
		if args[1] != nil {
			arg1 = args[1].(*dto.RoleDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleAdminFacade_Create_Call) Return(roleDTO *dto.RoleDTO, err error) *MockRoleAdminFacade_Create_Call {
	_c.Call.Return(roleDTO, err)
	return _c
}

func (_c *MockRoleAdminFacade_Create_Call) RunAndReturn(run func(ctx context.Context, role *dto.RoleDTO) (*dto.RoleDTO, error)) *MockRoleAdminFacade_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRoleAdminFacade
func (_mock *MockRoleAdminFacade) Delete(ctx context.Context, ID string) error {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoleAdminFacade_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRoleAdminFacade_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ID string
func (_e *MockRoleAdminFacade_Expecter) Delete(ctx interface{}, ID interface{}) *MockRoleAdminFacade_Delete_Call {
	return &MockRoleAdminFacade_Delete_Call{Call: _e.mock.On("Delete", ctx, ID)}
}

func (_c *MockRoleAdminFacade_Delete_Call) Run(run func(ctx context.Context, ID string)) *MockRoleAdminFacade_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleAdminFacade_Delete_Call) Return(err error) *MockRoleAdminFacade_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoleAdminFacade_Delete_Call) RunAndReturn(run func(ctx context.Context, ID string) error) *MockRoleAdminFacade_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockRoleAdminFacade
func (_mock *MockRoleAdminFacade) Get(ctx context.Context, ID string) (*dto.RoleDTO, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *dto.RoleDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*dto.RoleDTO, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *dto.RoleDTO); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RoleDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleAdminFacade_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRoleAdminFacade_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ID string
func (_e *MockRoleAdminFacade_Expecter) Get(ctx interface{}, ID interface{}) *MockRoleAdminFacade_Get_Call {
	return &MockRoleAdminFacade_Get_Call{Call: _e.mock.On("Get", ctx, ID)}
}

func (_c *MockRoleAdminFacade_Get_Call) Run(run func(ctx context.Context, ID string)) *MockRoleAdminFacade_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleAdminFacade_Get_Call) Return(roleDTO *dto.RoleDTO, err error) *MockRoleAdminFacade_Get_Call {
	_c.Call.Return(roleDTO, err)
	return _c
}

func (_c *MockRoleAdminFacade_Get_Call) RunAndReturn(run func(ctx context.Context, ID string) (*dto.RoleDTO, error)) *MockRoleAdminFacade_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type MockRoleAdminFacade
func (_mock *MockRoleAdminFacade) GetByName(ctx context.Context, name string) (*dto.RoleDTO, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *dto.RoleDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*dto.RoleDTO, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *dto.RoleDTO); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RoleDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleAdminFacade_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockRoleAdminFacade_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRoleAdminFacade_Expecter) GetByName(ctx interface{}, name interface{}) *MockRoleAdminFacade_GetByName_Call {
	return &MockRoleAdminFacade_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockRoleAdminFacade_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockRoleAdminFacade_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleAdminFacade_GetByName_Call) Return(roleDTO *dto.RoleDTO, err error) *MockRoleAdminFacade_GetByName_Call {
	_c.Call.Return(roleDTO, err)
	return _c
}

func (_c *MockRoleAdminFacade_GetByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*dto.RoleDTO, error)) *MockRoleAdminFacade_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRoleAdminFacade
func (_mock *MockRoleAdminFacade) List(ctx context.Context, limit int, offset int) ([]*dto.RoleDTO, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*dto.RoleDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*dto.RoleDTO, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*dto.RoleDTO); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.RoleDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleAdminFacade_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRoleAdminFacade_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockRoleAdminFacade_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *MockRoleAdminFacade_List_Call {
	return &MockRoleAdminFacade_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockRoleAdminFacade_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockRoleAdminFacade_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRoleAdminFacade_List_Call) Return(roleDTOs []*dto.RoleDTO, err error) *MockRoleAdminFacade_List_Call {
	_c.Call.Return(roleDTOs, err)
	return _c
}

func (_c *MockRoleAdminFacade_List_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*dto.RoleDTO, error)) *MockRoleAdminFacade_List_Call {
	_c.Call.Return(run)
	return _c
}
