// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/tiny-auth-service/internal/facade/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserAdminFacade creates a new instance of MockUserAdminFacade. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserAdminFacade(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserAdminFacade {
	mock := &MockUserAdminFacade{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserAdminFacade is an autogenerated mock type for the UserAdminFacade type
type MockUserAdminFacade struct {
	mock.Mock
}

type MockUserAdminFacade_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserAdminFacade) EXPECT() *MockUserAdminFacade_Expecter {
	return &MockUserAdminFacade_Expecter{mock: &_m.Mock}
}

// Change provides a mock function for the type MockUserAdminFacade
func (_mock *MockUserAdminFacade) Change(ctx context.Context, ID string, user *dto.UserDTO) (*dto.UserDTO, error) {
	ret := _mock.Called(ctx, ID, user)

	if len(ret) == 0 {
		panic("no return value specified for Change")
	}

	var r0 *dto.UserDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *dto.UserDTO) (*dto.UserDTO, error)); ok {
		return returnFunc(ctx, ID, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *dto.UserDTO) *dto.UserDTO); ok {
		r0 = returnFunc(ctx, ID, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *dto.UserDTO) error); ok {
		r1 = returnFunc(ctx, ID, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAdminFacade_Change_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Change'
type MockUserAdminFacade_Change_Call struct {
	*mock.Call
}

// Change is a helper method to define mock.On call
//   - ctx context.Context
//   - ID string
//   - user *dto.UserDTO
func (_e *MockUserAdminFacade_Expecter) Change(ctx interface{}, ID interface{}, user interface{}) *MockUserAdminFacade_Change_Call {
	return &MockUserAdminFacade_Change_Call{Call: _e.mock.On("Change", ctx, ID, user)}
}

func (_c *MockUserAdminFacade_Change_Call) Run(run func(ctx context.Context, ID string, user *dto.UserDTO)) *MockUserAdminFacade_Change_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *dto.UserDTO
		if args[2] != nil {
			arg2 = args[2].(*dto.UserDTO)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserAdminFacade_Change_Call) Return(userDTO *dto.UserDTO, err error) *MockUserAdminFacade_Change_Call {
	_c.Call.Return(userDTO, err)
	return _c
}

func (_c *MockUserAdminFacade_Change_Call) RunAndReturn(run func(ctx context.Context, ID string, user *dto.UserDTO) (*dto.UserDTO, error)) *MockUserAdminFacade_Change_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockUserAdminFacade
func (_mock *MockUserAdminFacade) Create(ctx context.Context, user *dto.UserDTO) (*dto.UserDTO, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.UserDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.UserDTO) (*dto.UserDTO, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.UserDTO) *dto.UserDTO); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.UserDTO) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAdminFacade_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserAdminFacade_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *dto.UserDTO
func (_e *MockUserAdminFacade_Expecter) Create(ctx interface{}, user interface{}) *MockUserAdminFacade_Create_Call {
	return &MockUserAdminFacade_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserAdminFacade_Create_Call) Run(run func(ctx context.Context, user *dto.UserDTO)) *MockUserAdminFacade_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.UserDTO
		if args[1] != nil {
			arg1 = args[1].(*dto.UserDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserAdminFacade_Create_Call) Return(userDTO *dto.UserDTO, err error) *MockUserAdminFacade_Create_Call {
	_c.Call.Return(userDTO, err)
	return _c
}

func (_c *MockUserAdminFacade_Create_Call) RunAndReturn(run func(ctx context.Context, user *dto.UserDTO) (*dto.UserDTO, error)) *MockUserAdminFacade_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserAdminFacade
func (_mock *MockUserAdminFacade) Delete(ctx context.Context, ID string) error {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserAdminFacade_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserAdminFacade_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ID string
func (_e *MockUserAdminFacade_Expecter) Delete(ctx interface{}, ID interface{}) *MockUserAdminFacade_Delete_Call {
	return &MockUserAdminFacade_Delete_Call{Call: _e.mock.On("Delete", ctx, ID)}
}

func (_c *MockUserAdminFacade_Delete_Call) Run(run func(ctx context.Context, ID string)) *MockUserAdminFacade_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserAdminFacade_Delete_Call) Return(err error) *MockUserAdminFacade_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserAdminFacade_Delete_Call) RunAndReturn(run func(ctx context.Context, ID string) error) *MockUserAdminFacade_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockUserAdminFacade
func (_mock *MockUserAdminFacade) Get(ctx context.Context, ID string) (*dto.UserDTO, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *dto.UserDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*dto.UserDTO, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *dto.UserDTO); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAdminFacade_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserAdminFacade_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ID string
func (_e *MockUserAdminFacade_Expecter) Get(ctx interface{}, ID interface{}) *MockUserAdminFacade_Get_Call {
	return &MockUserAdminFacade_Get_Call{Call: _e.mock.On("Get", ctx, ID)}
}

func (_c *MockUserAdminFacade_Get_Call) Run(run func(ctx context.Context, ID string)) *MockUserAdminFacade_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserAdminFacade_Get_Call) Return(userDTO *dto.UserDTO, err error) *MockUserAdminFacade_Get_Call {
	_c.Call.Return(userDTO, err)
	return _c
}

func (_c *MockUserAdminFacade_Get_Call) RunAndReturn(run func(ctx context.Context, ID string) (*dto.UserDTO, error)) *MockUserAdminFacade_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type MockUserAdminFacade
func (_mock *MockUserAdminFacade) GetByName(ctx context.Context, name string) (*dto.UserDTO, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *dto.UserDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*dto.UserDTO, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *dto.UserDTO); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAdminFacade_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockUserAdminFacade_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockUserAdminFacade_Expecter) GetByName(ctx interface{}, name interface{}) *MockUserAdminFacade_GetByName_Call {
	return &MockUserAdminFacade_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockUserAdminFacade_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockUserAdminFacade_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserAdminFacade_GetByName_Call) Return(userDTO *dto.UserDTO, err error) *MockUserAdminFacade_GetByName_Call {
	_c.Call.Return(userDTO, err)
	return _c
}

func (_c *MockUserAdminFacade_GetByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*dto.UserDTO, error)) *MockUserAdminFacade_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockUserAdminFacade
func (_mock *MockUserAdminFacade) List(ctx context.Context, limit int, offset int) ([]*dto.UserDTO, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*dto.UserDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*dto.UserDTO, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*dto.UserDTO); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.UserDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAdminFacade_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUserAdminFacade_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockUserAdminFacade_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *MockUserAdminFacade_List_Call {
	return &MockUserAdminFacade_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockUserAdminFacade_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockUserAdminFacade_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserAdminFacade_List_Call) Return(userDTOs []*dto.UserDTO, err error) *MockUserAdminFacade_List_Call {
	_c.Call.Return(userDTOs, err)
	return _c
}

func (_c *MockUserAdminFacade_List_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*dto.UserDTO, error)) *MockUserAdminFacade_List_Call {
	_c.Call.Return(run)
	return _c
}
