// Code generated by go-swagger; DO NOT EDIT.

package profile

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1UsersProfileParams creates a new GetAPIV1UsersProfileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1UsersProfileParams() *GetAPIV1UsersProfileParams {
	return &GetAPIV1UsersProfileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1UsersProfileParamsWithTimeout creates a new GetAPIV1UsersProfileParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1UsersProfileParamsWithTimeout(timeout time.Duration) *GetAPIV1UsersProfileParams {
	return &GetAPIV1UsersProfileParams{
		timeout: timeout,
	}
}

// NewGetAPIV1UsersProfileParamsWithContext creates a new GetAPIV1UsersProfileParams object
// with the ability to set a context for a request.
func NewGetAPIV1UsersProfileParamsWithContext(ctx context.Context) *GetAPIV1UsersProfileParams {
	return &GetAPIV1UsersProfileParams{
		Context: ctx,
	}
}

// NewGetAPIV1UsersProfileParamsWithHTTPClient creates a new GetAPIV1UsersProfileParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1UsersProfileParamsWithHTTPClient(client *http.Client) *GetAPIV1UsersProfileParams {
	return &GetAPIV1UsersProfileParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1UsersProfileParams contains all the parameters to send to the API endpoint

	for the get API v1 users profile operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1UsersProfileParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 users profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1UsersProfileParams) WithDefaults() *GetAPIV1UsersProfileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 users profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1UsersProfileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v1 users profile params
func (o *GetAPIV1UsersProfileParams) WithTimeout(timeout time.Duration) *GetAPIV1UsersProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 users profile params
func (o *GetAPIV1UsersProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 users profile params
func (o *GetAPIV1UsersProfileParams) WithContext(ctx context.Context) *GetAPIV1UsersProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 users profile params
func (o *GetAPIV1UsersProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 users profile params
func (o *GetAPIV1UsersProfileParams) WithHTTPClient(client *http.Client) *GetAPIV1UsersProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 users profile params
func (o *GetAPIV1UsersProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1UsersProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
