// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-auth-service/pkg/api/http/auth/v1/models"
)

// GetAPIV1UsersProfileReader is a Reader for the GetAPIV1UsersProfile structure.
type GetAPIV1UsersProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1UsersProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1UsersProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetAPIV1UsersProfileForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV1UsersProfileNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1UsersProfileInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/users/profile] GetAPIV1UsersProfile", response, response.Code())
	}
}

// NewGetAPIV1UsersProfileOK creates a GetAPIV1UsersProfileOK with default headers values
func NewGetAPIV1UsersProfileOK() *GetAPIV1UsersProfileOK {
	return &GetAPIV1UsersProfileOK{}
}

/*
GetAPIV1UsersProfileOK describes a response with status code 200, with default header values.

Профиль
*/
type GetAPIV1UsersProfileOK struct {
	Payload *models.ProfileDTO
}

// IsSuccess returns true when this get Api v1 users profile o k response has a 2xx status code
func (o *GetAPIV1UsersProfileOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 users profile o k response has a 3xx status code
func (o *GetAPIV1UsersProfileOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 users profile o k response has a 4xx status code
func (o *GetAPIV1UsersProfileOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 users profile o k response has a 5xx status code
func (o *GetAPIV1UsersProfileOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 users profile o k response a status code equal to that given
func (o *GetAPIV1UsersProfileOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 users profile o k response
func (o *GetAPIV1UsersProfileOK) Code() int {
	return 200
}

func (o *GetAPIV1UsersProfileOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/users/profile][%d] getApiV1UsersProfileOK %s", 200, payload)
}

func (o *GetAPIV1UsersProfileOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/users/profile][%d] getApiV1UsersProfileOK %s", 200, payload)
}

func (o *GetAPIV1UsersProfileOK) GetPayload() *models.ProfileDTO {
	return o.Payload
}

func (o *GetAPIV1UsersProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProfileDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1UsersProfileForbidden creates a GetAPIV1UsersProfileForbidden with default headers values
func NewGetAPIV1UsersProfileForbidden() *GetAPIV1UsersProfileForbidden {
	return &GetAPIV1UsersProfileForbidden{}
}

/*
GetAPIV1UsersProfileForbidden describes a response with status code 403, with default header values.

В доступе отказано
*/
type GetAPIV1UsersProfileForbidden struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this get Api v1 users profile forbidden response has a 2xx status code
func (o *GetAPIV1UsersProfileForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 users profile forbidden response has a 3xx status code
func (o *GetAPIV1UsersProfileForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 users profile forbidden response has a 4xx status code
func (o *GetAPIV1UsersProfileForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 users profile forbidden response has a 5xx status code
func (o *GetAPIV1UsersProfileForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 users profile forbidden response a status code equal to that given
func (o *GetAPIV1UsersProfileForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get Api v1 users profile forbidden response
func (o *GetAPIV1UsersProfileForbidden) Code() int {
	return 403
}

func (o *GetAPIV1UsersProfileForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/users/profile][%d] getApiV1UsersProfileForbidden %s", 403, payload)
}

func (o *GetAPIV1UsersProfileForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/users/profile][%d] getApiV1UsersProfileForbidden %s", 403, payload)
}

func (o *GetAPIV1UsersProfileForbidden) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *GetAPIV1UsersProfileForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1UsersProfileNotFound creates a GetAPIV1UsersProfileNotFound with default headers values
func NewGetAPIV1UsersProfileNotFound() *GetAPIV1UsersProfileNotFound {
	return &GetAPIV1UsersProfileNotFound{}
}

/*
GetAPIV1UsersProfileNotFound describes a response with status code 404, with default header values.

Запись не найдена
*/
type GetAPIV1UsersProfileNotFound struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this get Api v1 users profile not found response has a 2xx status code
func (o *GetAPIV1UsersProfileNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 users profile not found response has a 3xx status code
func (o *GetAPIV1UsersProfileNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 users profile not found response has a 4xx status code
func (o *GetAPIV1UsersProfileNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 users profile not found response has a 5xx status code
func (o *GetAPIV1UsersProfileNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 users profile not found response a status code equal to that given
func (o *GetAPIV1UsersProfileNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api v1 users profile not found response
func (o *GetAPIV1UsersProfileNotFound) Code() int {
	return 404
}

func (o *GetAPIV1UsersProfileNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/users/profile][%d] getApiV1UsersProfileNotFound %s", 404, payload)
}

func (o *GetAPIV1UsersProfileNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/users/profile][%d] getApiV1UsersProfileNotFound %s", 404, payload)
}

func (o *GetAPIV1UsersProfileNotFound) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *GetAPIV1UsersProfileNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1UsersProfileInternalServerError creates a GetAPIV1UsersProfileInternalServerError with default headers values
func NewGetAPIV1UsersProfileInternalServerError() *GetAPIV1UsersProfileInternalServerError {
	return &GetAPIV1UsersProfileInternalServerError{}
}

/*
GetAPIV1UsersProfileInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера (пустое тело)
*/
type GetAPIV1UsersProfileInternalServerError struct {
}

// IsSuccess returns true when this get Api v1 users profile internal server error response has a 2xx status code
func (o *GetAPIV1UsersProfileInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 users profile internal server error response has a 3xx status code
func (o *GetAPIV1UsersProfileInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 users profile internal server error response has a 4xx status code
func (o *GetAPIV1UsersProfileInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 users profile internal server error response has a 5xx status code
func (o *GetAPIV1UsersProfileInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 users profile internal server error response a status code equal to that given
func (o *GetAPIV1UsersProfileInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 users profile internal server error response
func (o *GetAPIV1UsersProfileInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1UsersProfileInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/users/profile][%d] getApiV1UsersProfileInternalServerError", 500)
}

func (o *GetAPIV1UsersProfileInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v1/users/profile][%d] getApiV1UsersProfileInternalServerError", 500)
}

func (o *GetAPIV1UsersProfileInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
