// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new profile API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new profile API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new profile API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for profile API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetAPIV1UsersProfile(params *GetAPIV1UsersProfileParams, opts ...ClientOption) (*GetAPIV1UsersProfileOK, error)

	PostAPIV1UserRegister(params *PostAPIV1UserRegisterParams, opts ...ClientOption) (*PostAPIV1UserRegisterOK, error)

	PutAPIV1UsersKeys(params *PutAPIV1UsersKeysParams, opts ...ClientOption) (*PutAPIV1UsersKeysOK, error)

	PutAPIV1UsersPassword(params *PutAPIV1UsersPasswordParams, opts ...ClientOption) (*PutAPIV1UsersPasswordOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetAPIV1UsersProfile получитьs

Получает запись по её ID
*/
func (a *Client) GetAPIV1UsersProfile(params *GetAPIV1UsersProfileParams, opts ...ClientOption) (*GetAPIV1UsersProfileOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIV1UsersProfileParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1UsersProfile",
		Method:             "GET",
		PathPattern:        "/api/v1/users/profile",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1UsersProfileReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIV1UsersProfileOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1UsersProfile: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPIV1UserRegister регистрацияs

Регистрация пользователя
*/
func (a *Client) PostAPIV1UserRegister(params *PostAPIV1UserRegisterParams, opts ...ClientOption) (*PostAPIV1UserRegisterOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAPIV1UserRegisterParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAPIV1UserRegister",
		Method:             "POST",
		PathPattern:        "/api/v1/user/register",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAPIV1UserRegisterReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAPIV1UserRegisterOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAPIV1UserRegister: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutAPIV1UsersKeys изменяетs роль

Изменение атрибутов роли
*/
func (a *Client) PutAPIV1UsersKeys(params *PutAPIV1UsersKeysParams, opts ...ClientOption) (*PutAPIV1UsersKeysOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutAPIV1UsersKeysParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutAPIV1UsersKeys",
		Method:             "PUT",
		PathPattern:        "/api/v1/users/keys",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutAPIV1UsersKeysReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutAPIV1UsersKeysOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutAPIV1UsersKeys: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutAPIV1UsersPassword сменаs пароля пользователя

Изменяет пароль пользователя
*/
func (a *Client) PutAPIV1UsersPassword(params *PutAPIV1UsersPasswordParams, opts ...ClientOption) (*PutAPIV1UsersPasswordOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutAPIV1UsersPasswordParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutAPIV1UsersPassword",
		Method:             "PUT",
		PathPattern:        "/api/v1/users/password",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutAPIV1UsersPasswordReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutAPIV1UsersPasswordOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutAPIV1UsersPassword: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
