// Code generated by go-swagger; DO NOT EDIT.

package profile

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutAPIV1UsersKeysParams creates a new PutAPIV1UsersKeysParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPIV1UsersKeysParams() *PutAPIV1UsersKeysParams {
	return &PutAPIV1UsersKeysParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIV1UsersKeysParamsWithTimeout creates a new PutAPIV1UsersKeysParams object
// with the ability to set a timeout on a request.
func NewPutAPIV1UsersKeysParamsWithTimeout(timeout time.Duration) *PutAPIV1UsersKeysParams {
	return &PutAPIV1UsersKeysParams{
		timeout: timeout,
	}
}

// NewPutAPIV1UsersKeysParamsWithContext creates a new PutAPIV1UsersKeysParams object
// with the ability to set a context for a request.
func NewPutAPIV1UsersKeysParamsWithContext(ctx context.Context) *PutAPIV1UsersKeysParams {
	return &PutAPIV1UsersKeysParams{
		Context: ctx,
	}
}

// NewPutAPIV1UsersKeysParamsWithHTTPClient creates a new PutAPIV1UsersKeysParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPIV1UsersKeysParamsWithHTTPClient(client *http.Client) *PutAPIV1UsersKeysParams {
	return &PutAPIV1UsersKeysParams{
		HTTPClient: client,
	}
}

/*
PutAPIV1UsersKeysParams contains all the parameters to send to the API endpoint

	for the put API v1 users keys operation.

	Typically these are written to a http.Request.
*/
type PutAPIV1UsersKeysParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put API v1 users keys params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIV1UsersKeysParams) WithDefaults() *PutAPIV1UsersKeysParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put API v1 users keys params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIV1UsersKeysParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put API v1 users keys params
func (o *PutAPIV1UsersKeysParams) WithTimeout(timeout time.Duration) *PutAPIV1UsersKeysParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API v1 users keys params
func (o *PutAPIV1UsersKeysParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API v1 users keys params
func (o *PutAPIV1UsersKeysParams) WithContext(ctx context.Context) *PutAPIV1UsersKeysParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API v1 users keys params
func (o *PutAPIV1UsersKeysParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API v1 users keys params
func (o *PutAPIV1UsersKeysParams) WithHTTPClient(client *http.Client) *PutAPIV1UsersKeysParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API v1 users keys params
func (o *PutAPIV1UsersKeysParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIV1UsersKeysParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
