// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-auth-service/pkg/api/http/auth/v1/models"
)

// PutAPIV1UsersKeysReader is a Reader for the PutAPIV1UsersKeys structure.
type PutAPIV1UsersKeysReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIV1UsersKeysReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPutAPIV1UsersKeysOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutAPIV1UsersKeysBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutAPIV1UsersKeysNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPutAPIV1UsersKeysConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutAPIV1UsersKeysInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /api/v1/users/keys] PutAPIV1UsersKeys", response, response.Code())
	}
}

// NewPutAPIV1UsersKeysOK creates a PutAPIV1UsersKeysOK with default headers values
func NewPutAPIV1UsersKeysOK() *PutAPIV1UsersKeysOK {
	return &PutAPIV1UsersKeysOK{}
}

/*
PutAPIV1UsersKeysOK describes a response with status code 200, with default header values.

OK
*/
type PutAPIV1UsersKeysOK struct {
	Payload *models.ChangedKeysDTO
}

// IsSuccess returns true when this put Api v1 users keys o k response has a 2xx status code
func (o *PutAPIV1UsersKeysOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put Api v1 users keys o k response has a 3xx status code
func (o *PutAPIV1UsersKeysOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api v1 users keys o k response has a 4xx status code
func (o *PutAPIV1UsersKeysOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put Api v1 users keys o k response has a 5xx status code
func (o *PutAPIV1UsersKeysOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api v1 users keys o k response a status code equal to that given
func (o *PutAPIV1UsersKeysOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put Api v1 users keys o k response
func (o *PutAPIV1UsersKeysOK) Code() int {
	return 200
}

func (o *PutAPIV1UsersKeysOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/users/keys][%d] putApiV1UsersKeysOK %s", 200, payload)
}

func (o *PutAPIV1UsersKeysOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/users/keys][%d] putApiV1UsersKeysOK %s", 200, payload)
}

func (o *PutAPIV1UsersKeysOK) GetPayload() *models.ChangedKeysDTO {
	return o.Payload
}

func (o *PutAPIV1UsersKeysOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ChangedKeysDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutAPIV1UsersKeysBadRequest creates a PutAPIV1UsersKeysBadRequest with default headers values
func NewPutAPIV1UsersKeysBadRequest() *PutAPIV1UsersKeysBadRequest {
	return &PutAPIV1UsersKeysBadRequest{}
}

/*
PutAPIV1UsersKeysBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PutAPIV1UsersKeysBadRequest struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this put Api v1 users keys bad request response has a 2xx status code
func (o *PutAPIV1UsersKeysBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put Api v1 users keys bad request response has a 3xx status code
func (o *PutAPIV1UsersKeysBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api v1 users keys bad request response has a 4xx status code
func (o *PutAPIV1UsersKeysBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this put Api v1 users keys bad request response has a 5xx status code
func (o *PutAPIV1UsersKeysBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api v1 users keys bad request response a status code equal to that given
func (o *PutAPIV1UsersKeysBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the put Api v1 users keys bad request response
func (o *PutAPIV1UsersKeysBadRequest) Code() int {
	return 400
}

func (o *PutAPIV1UsersKeysBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/users/keys][%d] putApiV1UsersKeysBadRequest %s", 400, payload)
}

func (o *PutAPIV1UsersKeysBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/users/keys][%d] putApiV1UsersKeysBadRequest %s", 400, payload)
}

func (o *PutAPIV1UsersKeysBadRequest) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PutAPIV1UsersKeysBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutAPIV1UsersKeysNotFound creates a PutAPIV1UsersKeysNotFound with default headers values
func NewPutAPIV1UsersKeysNotFound() *PutAPIV1UsersKeysNotFound {
	return &PutAPIV1UsersKeysNotFound{}
}

/*
PutAPIV1UsersKeysNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PutAPIV1UsersKeysNotFound struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this put Api v1 users keys not found response has a 2xx status code
func (o *PutAPIV1UsersKeysNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put Api v1 users keys not found response has a 3xx status code
func (o *PutAPIV1UsersKeysNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api v1 users keys not found response has a 4xx status code
func (o *PutAPIV1UsersKeysNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this put Api v1 users keys not found response has a 5xx status code
func (o *PutAPIV1UsersKeysNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api v1 users keys not found response a status code equal to that given
func (o *PutAPIV1UsersKeysNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the put Api v1 users keys not found response
func (o *PutAPIV1UsersKeysNotFound) Code() int {
	return 404
}

func (o *PutAPIV1UsersKeysNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/users/keys][%d] putApiV1UsersKeysNotFound %s", 404, payload)
}

func (o *PutAPIV1UsersKeysNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/users/keys][%d] putApiV1UsersKeysNotFound %s", 404, payload)
}

func (o *PutAPIV1UsersKeysNotFound) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PutAPIV1UsersKeysNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutAPIV1UsersKeysConflict creates a PutAPIV1UsersKeysConflict with default headers values
func NewPutAPIV1UsersKeysConflict() *PutAPIV1UsersKeysConflict {
	return &PutAPIV1UsersKeysConflict{}
}

/*
PutAPIV1UsersKeysConflict describes a response with status code 409, with default header values.

Conflict
*/
type PutAPIV1UsersKeysConflict struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this put Api v1 users keys conflict response has a 2xx status code
func (o *PutAPIV1UsersKeysConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put Api v1 users keys conflict response has a 3xx status code
func (o *PutAPIV1UsersKeysConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api v1 users keys conflict response has a 4xx status code
func (o *PutAPIV1UsersKeysConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this put Api v1 users keys conflict response has a 5xx status code
func (o *PutAPIV1UsersKeysConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api v1 users keys conflict response a status code equal to that given
func (o *PutAPIV1UsersKeysConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the put Api v1 users keys conflict response
func (o *PutAPIV1UsersKeysConflict) Code() int {
	return 409
}

func (o *PutAPIV1UsersKeysConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/users/keys][%d] putApiV1UsersKeysConflict %s", 409, payload)
}

func (o *PutAPIV1UsersKeysConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/users/keys][%d] putApiV1UsersKeysConflict %s", 409, payload)
}

func (o *PutAPIV1UsersKeysConflict) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PutAPIV1UsersKeysConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutAPIV1UsersKeysInternalServerError creates a PutAPIV1UsersKeysInternalServerError with default headers values
func NewPutAPIV1UsersKeysInternalServerError() *PutAPIV1UsersKeysInternalServerError {
	return &PutAPIV1UsersKeysInternalServerError{}
}

/*
PutAPIV1UsersKeysInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера (пустое тело)
*/
type PutAPIV1UsersKeysInternalServerError struct {
}

// IsSuccess returns true when this put Api v1 users keys internal server error response has a 2xx status code
func (o *PutAPIV1UsersKeysInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put Api v1 users keys internal server error response has a 3xx status code
func (o *PutAPIV1UsersKeysInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api v1 users keys internal server error response has a 4xx status code
func (o *PutAPIV1UsersKeysInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this put Api v1 users keys internal server error response has a 5xx status code
func (o *PutAPIV1UsersKeysInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this put Api v1 users keys internal server error response a status code equal to that given
func (o *PutAPIV1UsersKeysInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the put Api v1 users keys internal server error response
func (o *PutAPIV1UsersKeysInternalServerError) Code() int {
	return 500
}

func (o *PutAPIV1UsersKeysInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /api/v1/users/keys][%d] putApiV1UsersKeysInternalServerError", 500)
}

func (o *PutAPIV1UsersKeysInternalServerError) String() string {
	return fmt.Sprintf("[PUT /api/v1/users/keys][%d] putApiV1UsersKeysInternalServerError", 500)
}

func (o *PutAPIV1UsersKeysInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
