// Code generated by go-swagger; DO NOT EDIT.

package profile

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/tiny-auth-service/pkg/api/http/auth/v1/models"
)

// NewPutAPIV1UsersPasswordParams creates a new PutAPIV1UsersPasswordParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPIV1UsersPasswordParams() *PutAPIV1UsersPasswordParams {
	return &PutAPIV1UsersPasswordParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIV1UsersPasswordParamsWithTimeout creates a new PutAPIV1UsersPasswordParams object
// with the ability to set a timeout on a request.
func NewPutAPIV1UsersPasswordParamsWithTimeout(timeout time.Duration) *PutAPIV1UsersPasswordParams {
	return &PutAPIV1UsersPasswordParams{
		timeout: timeout,
	}
}

// NewPutAPIV1UsersPasswordParamsWithContext creates a new PutAPIV1UsersPasswordParams object
// with the ability to set a context for a request.
func NewPutAPIV1UsersPasswordParamsWithContext(ctx context.Context) *PutAPIV1UsersPasswordParams {
	return &PutAPIV1UsersPasswordParams{
		Context: ctx,
	}
}

// NewPutAPIV1UsersPasswordParamsWithHTTPClient creates a new PutAPIV1UsersPasswordParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPIV1UsersPasswordParamsWithHTTPClient(client *http.Client) *PutAPIV1UsersPasswordParams {
	return &PutAPIV1UsersPasswordParams{
		HTTPClient: client,
	}
}

/*
PutAPIV1UsersPasswordParams contains all the parameters to send to the API endpoint

	for the put API v1 users password operation.

	Typically these are written to a http.Request.
*/
type PutAPIV1UsersPasswordParams struct {

	/* Input.

	   Смена пароля
	*/
	Input *models.ChangePasswordDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put API v1 users password params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIV1UsersPasswordParams) WithDefaults() *PutAPIV1UsersPasswordParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put API v1 users password params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIV1UsersPasswordParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put API v1 users password params
func (o *PutAPIV1UsersPasswordParams) WithTimeout(timeout time.Duration) *PutAPIV1UsersPasswordParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API v1 users password params
func (o *PutAPIV1UsersPasswordParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API v1 users password params
func (o *PutAPIV1UsersPasswordParams) WithContext(ctx context.Context) *PutAPIV1UsersPasswordParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API v1 users password params
func (o *PutAPIV1UsersPasswordParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API v1 users password params
func (o *PutAPIV1UsersPasswordParams) WithHTTPClient(client *http.Client) *PutAPIV1UsersPasswordParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API v1 users password params
func (o *PutAPIV1UsersPasswordParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInput adds the input to the put API v1 users password params
func (o *PutAPIV1UsersPasswordParams) WithInput(input *models.ChangePasswordDTO) *PutAPIV1UsersPasswordParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the put API v1 users password params
func (o *PutAPIV1UsersPasswordParams) SetInput(input *models.ChangePasswordDTO) {
	o.Input = input
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIV1UsersPasswordParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
