// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChangedKeysDTO changed keys d t o
//
// swagger:model ChangedKeysDTO
type ChangedKeysDTO struct {

	// private key
	PrivateKey string `json:"private_key,omitempty"`

	// public key
	PublicKey string `json:"public_key,omitempty"`
}

// Validate validates this changed keys d t o
func (m *ChangedKeysDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this changed keys d t o based on context it is used
func (m *ChangedKeysDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChangedKeysDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChangedKeysDTO) UnmarshalBinary(b []byte) error {
	var res ChangedKeysDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
