// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChangePasswordDTO change password d t o
//
// swagger:model ChangePasswordDTO
type ChangePasswordDTO struct {

	// new password
	NewPassword string `json:"new_password,omitempty"`

	// old password
	OldPassword string `json:"old_password,omitempty"`
}

// Validate validates this change password d t o
func (m *ChangePasswordDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this change password d t o based on context it is used
func (m *ChangePasswordDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChangePasswordDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChangePasswordDTO) UnmarshalBinary(b []byte) error {
	var res ChangePasswordDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
